import {PageHero} from '@/components/plantpal/page-hero';
import {glossary} from '@/lib/glossary';
import {Breadcrumbs,pageMetadata,JsonLd} from '@/lib/seo';
import {SITE_URL} from '@/lib/config';
import {Input} from '@/components/ui/input';
import {AppCTA} from '@/components/plantpal/shared';
import {ArrowUpRight} from 'lucide-react';
export async function generateMetadata({searchParams}:{searchParams:Promise<{q?:string}>}){return {...pageMetadata('מילון מושגים לצמחי בית','הסברים ברורים למושגים מעולם הטיפול בצמחים, מאדמה וניקוז ועד ריבוי ודישון.','/glossary'),...((await searchParams).q?{robots:{index:false,follow:true}}:{})}}
export default async function Glossary({searchParams}:{searchParams:Promise<{q?:string}>}){const q=String((await searchParams).q||'').slice(0,100);const terms=glossary.filter(t=>(t.name+' '+t.definition).toLowerCase().includes(q.toLowerCase()));const letters=[...new Set(terms.map(t=>t.name[0]))];return <main id="main"><PageHero eyebrow="מדברים צמחים, בשפה ברורה" title={<>פחות מושגים מסובכים.<br/><em>יותר הבנה.</em></>} description="מילון ידידותי שעושה סדר במילים החשובות של עולם הצמחים." image="/images/leaf-detail-hero.webp" imageAlt="טיפות מים ואור שמש על עלים ירוקים" breadcrumbs={<Breadcrumbs items={[{name:'מילון מושגים',href:'/glossary'}]}/>} linkLabel="לכל המושגים"/><section className="shell page-top visual-page-content" id="browse-content"><form action="/glossary" className="library-search"><label htmlFor="term-search">חיפוש במילון</label><div><Input id="term-search" name="q" defaultValue={q} placeholder="נסו: פרלייט או מפרק" maxLength={100}/><button type="submit" className="button">חיפוש</button></div></form><nav className="alphabet" aria-label="אותיות המילון">{letters.map(l=><a key={l} href={`#letter-${l}`}>{l}</a>)}</nav>{q&&<div className="results-summary"><span>{terms.length} תוצאות עבור „{q}”</span><a href="/glossary">ניקוי החיפוש</a></div>}{letters.map(l=><section className="glossary-group" id={`letter-${l}`} key={l}><h2>{l}</h2><div>{terms.filter(t=>t.name[0]===l).map(t=><a key={t.slug} href={`/glossary/${t.slug}`}><h3>{t.name}<ArrowUpRight size={18}/></h3><p>{t.definition}</p></a>)}</div></section>)}{!terms.length&&<div className="empty-state"><h2>לא מצאנו מושג מתאים.</h2><p>נסו מילה קצרה יותר או עיינו בכל המילון.</p><a className="button" href="/glossary">לכל המושגים</a></div>}</section><AppCTA/><JsonLd data={{'@context':'https://schema.org','@type':'DefinedTermSet',name:'מילון הטיפול בצמחים של PlantPal',url:SITE_URL+'/glossary',inLanguage:'he-IL',hasDefinedTerm:terms.map(t=>({'@type':'DefinedTerm',name:t.name,description:t.definition,url:SITE_URL+'/glossary/'+t.slug}))}}/></main>}
