import {PageHero} from '@/components/plantpal/page-hero';
import {Camera,Bell,Sun,Plane,MessageCircle,MapPin,NotebookPen,BookOpen,ArrowRight} from 'lucide-react';
import {DownloadButton,AppCTA} from '@/components/plantpal/shared';
import {FAQ} from '@/components/plantpal/faq';
import {pageMetadata,JsonLd} from '@/lib/seo';
import {PLAY_URL,APP_STORE_URL,SITE_URL} from '@/lib/config';
export const metadata=pageMetadata('PlantPal: אפליקציה חכמה לטיפול בצמחים','זיהוי צמחים, הנחיות AI, תזכורות השקיה ודישון, מד אור ו־Plant Sitter.','/app');
export default function AppPage(){return <main id="main"><PageHero eyebrow="PLANTPAL: טיפול חכם בצמחים" title={<>נותנים לכל צמח<br/>את הטיפול <em>שמגיע לו.</em></>} description="זיהוי צמחים, שגרת טיפול ומעקב אחר האוסף — מהעציץ הראשון ועד ג׳ונגל ביתי שלם." imageAlt="אור שמש בין עלים ירוקים ושופעים" target="app-features" linkLabel="להכיר את העוזר שלכם לטיפול בצמחים" side={<div className="phone"><img src="/images/app-garden.webp" alt="מסך הגינה של PlantPal עם תזכורות טיפול" width="1080" height="2340"/></div>}><DownloadButton/><span className="hero-platform-note">זמינה ל־iOS ול־Android</span></PageHero><section className="shell section app-features" id="app-features"><span className="eyebrow">פחות ניחושים. יותר צמיחה.</span><h2>כל מה שצריך כדי לטפל בצמחים, במקום אחד.</h2><div className="features-grid">{[[Camera,'זיהוי צמחים בעזרת AI','מצלמים צמח ומקבלים זיהוי, הנחיות השקיה, צורכי אור ומידע מותאם.'],[Bell,'תזכורות השקיה ודישון','יוצרים תזכורות לכל צמח ומקבלים הודעה כשהגיע הזמן לבדוק מה הוא צריך.'],[Sun,'מד אור מובנה','מודדים את עוצמת האור בלוקס ובודקים אם המיקום מתאים לצמח.'],[Plane,'Plant Sitter','עוזרים לחבר, לבן משפחה או לעמית לטפל בצמחים בזמן שאתם לא בבית.'],[MessageCircle,'עוזר טיפול מבוסס AI','שואלים על עלים צהובים, מזיקים, השקיה, אדמה וצמיחה ומבינים מה לבדוק.'],[MapPin,'ארגון לפי אזורים','מסדרים את הצמחים לפי סלון, משרד, מרפסת או כל אזור אחר.'],[NotebookPen,'כל אוסף הצמחים במקום אחד','עוקבים אחר צורכי טיפול, מועדים, מיקום, אור ומידע שימושי לכל צמח.'],[BookOpen,'מדריכי טיפול אישיים','מקבלים מידע על השקיה, דישון, אור וטיפול כללי שמתאים לצמחים שלכם.']].map(([Icon,title,desc]:any)=><div key={title}><Icon size={27}/><h3>{title}</h3><p>{desc}</p></div>)}</div></section><section className="app-screens shell"><img src="/images/app-plants.webp" alt="מסך אוסף הצמחים באפליקציה" width="1080" height="2340" loading="lazy"/><img src="/images/app-care.webp" alt="מסך הטיפול בצמח באפליקציה" width="1080" height="2340" loading="lazy"/><div><span className="eyebrow">הג׳ונגל הביתי, מסודר</span><h2>צעד קטן אחד<br/>לבית מלא ירוק.</h2><p>שומרים את האוסף ואת כל פרטי הטיפול במקום אחד, כדי להשאיר יותר זמן ליהנות מהצמחים.</p><a className="text-link" href="/learn">למדריך הבא <ArrowRight size={18}/></a></div></section><section className="shell section faq-section"><span className="eyebrow">כמה דברים שכדאי לדעת</span><h2>עושים סדר.</h2><FAQ/></section><AppCTA/><JsonLd data={{'@context':'https://schema.org','@type':'SoftwareApplication',name:'PlantPal: AI Plant Care',operatingSystem:'Android, iOS',applicationCategory:'LifestyleApplication',url:SITE_URL+'/app',downloadUrl:[PLAY_URL,APP_STORE_URL],description:'אפליקציה לזיהוי צמחים, מדריכי טיפול, תזכורות, מד אור ומעקב אחר אוסף הצמחים.'}}/></main>}

