import {AppProductHero,AppScreenshots} from '@/components/plantpal/app-showcase';
import {GardenDesignTeaser} from '@/components/plantpal/garden-design-feature';
import {Camera,Bell,Sun,Plane,MessageCircle,MapPin,NotebookPen,BookOpen} from 'lucide-react';
import {DownloadButton,AppCTA} from '@/components/plantpal/shared';
import {FAQ} from '@/components/plantpal/faq';
import {pageMetadata,JsonLd} from '@/lib/seo';
import {PLAY_URL,APP_STORE_URL,SITE_URL} from '@/lib/config';
export const metadata=pageMetadata('PlantPal: אפליקציה חכמה לטיפול בצמחים','זיהוי צמחים, הנחיות AI, תזכורות השקיה ודישון, מד אור ו־Plant Sitter.','/app');
export default function AppPage(){return <main id="main"><AppProductHero locale="he" eyebrow="PLANTPAL: טיפול חכם בצמחים" title={<>הצמחים שלכם.<br/>שגרת הטיפול שלכם.<br/><em>הכול יחד.</em></>} description="מכירים את הצמחים, עוקבים אחר הטיפול ורואים את האוסף גדל עם PlantPal."><DownloadButton/><span className="hero-platform-note">זמינה ל־iOS ול־Android</span></AppProductHero><AppScreenshots locale="he"/><GardenDesignTeaser locale="he"/><section className="shell section app-features" id="app-features"><span className="eyebrow">פחות ניחושים. יותר צמיחה.</span><h2>כל מה שצריך כדי לטפל בצמחים, במקום אחד.</h2><div className="features-grid">{[[Camera,'זיהוי צמחים בעזרת AI','מצלמים צמח ומקבלים זיהוי, הנחיות השקיה, צורכי אור ומידע מותאם.'],[Bell,'תזכורות השקיה ודישון','יוצרים תזכורות לכל צמח ומקבלים הודעה כשהגיע הזמן לבדוק מה הוא צריך.'],[Sun,'מד אור מובנה','מודדים את עוצמת האור בלוקס ובודקים אם המיקום מתאים לצמח.'],[Plane,'Plant Sitter','עוזרים לחבר, לבן משפחה או לעמית לטפל בצמחים בזמן שאתם לא בבית.'],[MessageCircle,'עוזר טיפול מבוסס AI','שואלים על עלים צהובים, מזיקים, השקיה, אדמה וצמיחה ומבינים מה לבדוק.'],[MapPin,'ארגון לפי אזורים','מסדרים את הצמחים לפי סלון, משרד, מרפסת או כל אזור אחר.'],[NotebookPen,'כל אוסף הצמחים במקום אחד','עוקבים אחר צורכי טיפול, מועדים, מיקום, אור ומידע שימושי לכל צמח.'],[BookOpen,'מדריכי טיפול אישיים','מקבלים מידע על השקיה, דישון, אור וטיפול כללי שמתאים לצמחים שלכם.']].map(([Icon,title,desc]:any)=><div key={title}><Icon size={27}/><h3>{title}</h3><p>{desc}</p></div>)}</div></section><section className="shell section faq-section"><span className="eyebrow">כמה דברים שכדאי לדעת</span><h2>עושים סדר.</h2><FAQ/></section><AppCTA/><JsonLd data={{'@context':'https://schema.org','@type':'SoftwareApplication',name:'PlantPal: AI Plant Care',operatingSystem:'Android, iOS',applicationCategory:'LifestyleApplication',url:SITE_URL+'/app',downloadUrl:[PLAY_URL,APP_STORE_URL],description:'אפליקציה לזיהוי צמחים, מדריכי טיפול, תזכורות, מד אור ומעקב אחר אוסף הצמחים.'}}/></main>}

