import {ArrowDown, ArrowUpRight, Gamepad2, Sparkles, Sun} from 'lucide-react';
import {PlantPlayground} from './plant-playground';
import {JsonLd} from '@/lib/seo';
import {SITE_URL} from '@/lib/config';

type GameLocale='en'|'he';

const copy={
  en:{eyebrow:'A LITTLE ADVENTURE',bannerTitle:'Take a little garden break.',bannerText:'Three tiny worlds. A trail of sunshine. One very determined plant.',bannerAction:'Play the garden game',home:'Home',game:'Garden game',title:'A little sunshine goes a long way.',intro:'Guide your plant through three playful gardens. Collect the sunshine, jump past the thorns, and see how far you can grow.',jump:'Jump into the game',titleTag:'PlantPal garden game: a little plant adventure',description:'Play a free three-stage garden game. Guide your plant, collect sunshine, and jump past thorns on desktop or mobile.'},
  he:{eyebrow:'הרפתקה קטנה בגן',bannerTitle:'רגע קטן של משחק.',bannerText:'שלושה גנים, קרני שמש וצמח אחד שלא מוותר.',bannerAction:'למשחק הגינה',home:'דף הבית',game:'משחק הגינה',title:'קצת שמש. הרבה הרפתקה.',intro:'מובילים את הצמח דרך שלושה גנים, אוספים קרני שמש ומדלגים מעל הקוצים. כמה רחוק תצליחו להגיע?',jump:'מתחילים לשחק',titleTag:'משחק הגינה של PlantPal: הרפתקת צמחים קטנה',description:'משחק גינה חינמי עם שלושה שלבים: אוספים קרני שמש, מדלגים מעל קוצים ומשחקים במחשב או בטלפון.'},
} as const;

export function gameMetadata(locale:GameLocale){const c=copy[locale];const path=locale==='he'?'/he/game':'/game';return {title:c.titleTag,description:c.description,alternates:{canonical:`${SITE_URL}${path}`,languages:{en:`${SITE_URL}/game`,'he-IL':`${SITE_URL}/he/game`,'x-default':`${SITE_URL}/game`}},openGraph:{title:c.titleTag,description:c.description,url:`${SITE_URL}${path}`,locale:locale==='he'?'he_IL':'en_US',type:'website' as const},twitter:{card:'summary' as const,title:c.titleTag,description:c.description}}}

export function GameInvitation({locale}:{locale:GameLocale}){const c=copy[locale],href=locale==='he'?'/he/game':'/game';return <aside className="game-invitation-wrap" aria-label={c.game}><a className="game-invitation shell" href={href}><span className="game-invitation-icon" aria-hidden="true"><Sun size={38}/><Sparkles size={18}/></span><span className="game-invitation-copy"><span className="eyebrow">{c.eyebrow}</span><strong>{c.bannerTitle}</strong><span>{c.bannerText}</span></span><span className="game-invitation-action">{c.bannerAction}<ArrowUpRight size={19}/></span></a></aside>}

export function GamePage({locale}:{locale:GameLocale}){const c=copy[locale],prefix=locale==='he'?'/he':'';return <div className="game-page" lang={locale==='he'?'he-IL':'en'} dir={locale==='he'?'rtl':'ltr'}><div className="game-page-intro"><div className="shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={prefix||'/'}>{c.home}</a><span><span aria-hidden="true">/</span>{c.game}</span></nav><div className="game-page-intro-content"><div><span className="eyebrow"><Gamepad2 size={17}/>{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><a className="button" href="#plant-playground">{c.jump}<ArrowDown size={17}/></a></div><div className="game-page-art" aria-hidden="true"><span className="game-page-sun"><Sun size={72}/></span><span className="game-page-hill game-page-hill-back"/><span className="game-page-hill game-page-hill-front"/><span className="game-page-sprout">✿</span><span className="game-page-orb game-page-orb-one"/><span className="game-page-orb game-page-orb-two"/><span className="game-page-orb game-page-orb-three"/></div></div></div></div><PlantPlayground locale={locale}/><JsonLd data={{'@context':'https://schema.org','@type':'VideoGame',name:c.titleTag,description:c.description,url:`${SITE_URL}${prefix}/game`,inLanguage:locale==='he'?'he-IL':'en',applicationCategory:'Game',gamePlatform:['Web browser','Mobile web browser'],isAccessibleForFree:true,publisher:{'@type':'Organization',name:'PlantPal',url:SITE_URL}}}/></div>}
