import {Search,ArrowUpRight,Clock,BookOpen} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Pagination,PaginationContent,PaginationItem,PaginationLink,PaginationPrevious,PaginationNext} from '@/components/ui/pagination';
import {categories,type Category} from '@/lib/config';
import {type Article,readingMinutes} from '@/lib/content';
import {icons} from './shared';
export function ArticleCard({article:a}:{article:Article}){const c=categories.find(c=>c.slug===a.category)!;const Icon=icons[c.icon];return <a className={`library-card category-${a.category}`} href={`/learn/${a.slug}`}><div className="library-card-icon"><Icon size={25} strokeWidth={1.4}/><ArrowUpRight size={18}/></div><span className="eyebrow">{c.name}</span><h3>{a.title}</h3><p>{a.description}</p><span className="card-more"><span><Clock size={14}/> {readingMinutes(a)} דקות קריאה</span><span>למדריך <ArrowUpRight size={15}/></span></span></a>}
export function Library({articles,category,q='',page=1}:{articles:Article[],category?:Category,q?:string,page?:number}){
 const terms=q.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const filtered=articles.filter(a=>(!category||a.category===category)&&terms.every(t=>`${a.title} ${a.description} ${a.sections.map(s=>s.heading+' '+s.paragraphs.join(' ')).join(' ')}`.toLowerCase().includes(t)));
 const pages=Math.max(1,Math.ceil(filtered.length/12));const current=Math.min(Math.max(1,page),pages);const path=category?`/${category}`:'/learn';
 const url=(n:number)=>{const p=new URLSearchParams();if(q)p.set('q',q);if(n>1)p.set('page',String(n));return path+(p.size?'?'+p:'')};
 return <><form action={path} method="get" className="library-search" role="search"><label htmlFor="article-search">מחפשים תשובה לצמח?</label><div><Search size={20}/><Input id="article-search" name="q" defaultValue={q} placeholder="נסו: עלים צהובים, פוטוס או דשן" maxLength={120}/><button className="button" type="submit">חיפוש</button></div></form><nav className="category-pills" aria-label="קטגוריות מדריכים"><a href="/learn" aria-current={!category?'page':undefined}>כל המדריכים</a>{categories.map(c=><a key={c.slug} href={`/${c.slug}`} aria-current={c.slug===category?'page':undefined}>{c.name}</a>)}</nav><div className="results-summary"><span>{filtered.length} {filtered.length===1?'מדריך':'מדריכים'}{q?` עבור „${q}”`:''}</span>{q&&<a href={path}>ניקוי החיפוש</a>}</div>{filtered.length?<div className="library-grid">{filtered.slice((current-1)*12,current*12).map(a=><ArticleCard key={a.slug} article={a}/>)}</div>:<div className="empty-state"><BookOpen size={36}/><h2>לא מצאנו מדריך מתאים.</h2><p>נסו שם של צמח או נושא רחב יותר כמו מים, אור או אדמה.</p><a className="button" href={path}>לכל המדריכים</a></div>}{pages>1&&<Pagination className="library-pagination"><PaginationContent>{current>1&&<PaginationItem><PaginationPrevious href={url(current-1)} aria-label="לעמוד הקודם"/></PaginationItem>}{Array.from({length:pages},(_,i)=>i+1).map(n=><PaginationItem key={n}><PaginationLink href={url(n)} isActive={n===current}>{n}</PaginationLink></PaginationItem>)}{current<pages&&<PaginationItem><PaginationNext href={url(current+1)} aria-label="לעמוד הבא"/></PaginationItem>}</PaginationContent></Pagination>}</>;
}
