import {notFound} from 'next/navigation';
import {ArrowUpRight,Bell,Camera,Clock,Leaf,Plane,Sun} from 'lucide-react';
import {englishSeedArticles} from '@/lib/repository';
import {englishGlossary} from '@/lib/glossary';
import {packs,localizeFor,type NewLocale} from '@/lib/multilingual';
import {APP_STORE_URL,PLAY_URL,SITE_URL} from '@/lib/config';
import {readingMinutes,type Article} from '@/lib/content';
import {privacyContent} from '@/lib/privacy-content';

const localePaths=['fr','it','hi','zh','ar','pt','ru','es'] as const;
const route=(parts?:string[])=>parts?.join('/')||'';
export function localizedMetadata(locale:NewLocale,parts?:string[]){const p=packs[locale];const r=route(parts);let title=`PlantPal — ${p.heroTitle} ${p.heroAccent}`;let description=p.heroText;if(r==='learn'){title=p.libraryTitle;description=p.libraryText}else if(r==='app'){title=p.download;description=p.ctaText}else if(r==='glossary'){title=p.glossary;description=p.libraryText}else if(r==='privacy'){title=privacyContent[locale].title;description=privacyContent[locale].intro}else{const [first,second]=r.split('/');if(first==='learn'&&second){const a=englishSeedArticles.find(x=>x.slug===second);if(a){const l=localizeFor(a,locale);title=l.title;description=l.description}}else if(first&&p.categories[first]){title=p.categories[first];description=p.libraryText}}
 const path=r?`/${r}`:'';const languages:Record<string,string>={'he-IL':SITE_URL+'/he'+path,en:SITE_URL+(path||'/')};for(const code of localePaths)languages[packs[code].lang]=SITE_URL+'/'+code+path;return {title,description,alternates:{canonical:SITE_URL+'/'+locale+path,languages},openGraph:{title,description,url:SITE_URL+'/'+locale+path,locale:p.lang.replace('-','_'),type:'website' as const}}}
function Stores({p}:{p:(typeof packs)[NewLocale]}){return <div className="store-buttons"><a className="button" href={APP_STORE_URL} target="_blank" rel="noopener noreferrer">App Store <ArrowUpRight size={15}/></a><a className="button" href={PLAY_URL} target="_blank" rel="noopener noreferrer">Google Play <ArrowUpRight size={15}/></a></div>}
function CTA({locale}:{locale:NewLocale}){const p=packs[locale];return <section className="app-cta shell"><div><span className="eyebrow">PLANTPAL</span><h2>{p.ctaTitle}</h2><p>{p.ctaText}</p><Stores p={p}/></div><div className="cta-side"><img src="/images/app-icon.webp" width="125" height="125" alt="PlantPal"/><span>PlantPal: AI Plant Care</span></div></section>}
function Hero({locale,library=false,image='/images/greenhouse-hero.webp'}:{locale:NewLocale;library?:boolean;image?:string}){const p=packs[locale];return <section className={`immersive-hero${library?' page-visual-hero':''}`}><img className="immersive-hero-image" src={image} alt="PlantPal"/><div className="hero-shade"/><div className={`shell ${library?'page-visual-inner':'immersive-hero-content'}`}><div className={library?'page-visual-copy':'immersive-hero-copy'}><span className="eyebrow"><Leaf size={16}/>{library?p.learn:p.heroEyebrow}</span><h1>{library?p.libraryTitle:<>{p.heroTitle}<br/><em>{p.heroAccent}</em></>}</h1><p>{library?p.libraryText:p.heroText}</p>{!library&&<><Stores p={p}/><a className="hero-learn-link" href={`/${locale}/learn`}>{p.explore}<ArrowUpRight size={18}/></a></>}</div></div></section>}
function Card({article,locale}:{article:Article;locale:NewLocale}){const p=packs[locale],a=localizeFor(article,locale);return <a className={`library-card category-${a.category}`} href={`/${locale}/learn/${a.slug}`}><div className="library-card-icon"><Leaf size={25}/><ArrowUpRight size={18}/></div><span className="eyebrow">{p.categories[a.category]}</span><h3>{a.title}</h3><p>{a.description}</p><span className="card-more"><span><Clock size={14}/>{readingMinutes(a)} {p.minutes}</span><span>{p.read}<ArrowUpRight size={15}/></span></span></a>}
function Library({locale,category,q=''}:{locale:NewLocale;category?:string;q?:string}){const p=packs[locale],needle=q.toLocaleLowerCase(p.lang);const list=englishSeedArticles.filter(a=>(!category||a.category===category)&&(!needle||localizeFor(a,locale).title.toLocaleLowerCase(p.lang).includes(needle)));return <section className="shell page-top visual-page-content"><form className="library-search" action={category?`/${locale}/${category}`:`/${locale}/learn`}><label htmlFor="localized-search">{p.search}</label><div><input id="localized-search" name="q" defaultValue={q}/><button className="button">{p.search}</button></div></form><nav className="category-pills" aria-label={p.learn}><a href={`/${locale}/learn`}>{p.all}</a>{Object.entries(p.categories).map(([slug,name])=><a href={`/${locale}/${slug}`} key={slug}>{name}</a>)}</nav><div className="results-summary"><span>{list.length} {p.guides}</span></div><div className="library-grid">{list.map(a=><Card article={a} locale={locale} key={a.slug}/>)}</div></section>}
function Home({locale}:{locale:NewLocale}){const p=packs[locale];return <><Hero locale={locale}/><div className="promise-strip"><div className="shell"><span><Camera/>{p.guides}</span><span><Bell/>{p.categories['plant-care']}</span><span><Sun/>{p.soil}</span><span><Plane/>{p.app}</span></div></div><section className="section shell"><div className="section-title"><div><span className="eyebrow">PLANTPAL</span><h2>{p.libraryTitle}</h2></div></div><div className="category-grid">{Object.entries(p.categories).map(([slug,name])=><a className="category-card" href={`/${locale}/${slug}`} key={slug}><Leaf size={27}/><h3>{name}</h3><p>{p.libraryText}</p><ArrowUpRight size={18}/></a>)}</div></section><section className="section shell"><div className="library-grid">{englishSeedArticles.slice(0,6).map(a=><Card article={a} locale={locale} key={a.slug}/>)}</div></section><CTA locale={locale}/></>}
function ArticlePage({locale,slug}:{locale:NewLocale;slug:string}){const source=englishSeedArticles.find(a=>a.slug===slug);if(!source)notFound();const p=packs[locale],a=localizeFor(source,locale);return <><div className="shell article-shell"><nav className="breadcrumbs"><a href={`/${locale}`}>{p.home}</a><span>/</span><a href={`/${locale}/${a.category}`}>{p.categories[a.category]}</a></nav><header className="article-header"><span className="eyebrow">{p.categories[a.category]}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><span><Leaf size={16}/>PlantPal</span><span><Clock size={15}/>{readingMinutes(a)} {p.minutes}</span></div></header><div className="article-layout"><article className="article-prose"><div className="takeaway"><p>{a.takeaway}</p></div>{a.sections.map((s,i)=><section key={s.heading} id={`section-${i+1}`}><h2>{s.heading}</h2>{s.paragraphs.map(x=><p key={x}>{x}</p>)}</section>)}</article><aside className="article-sidebar"><div className="toc">{a.sections.map((s,i)=><a key={s.heading} href={`#section-${i+1}`}><span>{String(i+1).padStart(2,'0')}</span>{s.heading}</a>)}</div></aside></div></div><CTA locale={locale}/></>}
function Glossary({locale,slug}:{locale:NewLocale;slug?:string}){const p=packs[locale];if(slug){const t=englishGlossary.find(x=>x.slug===slug);if(!t)notFound();return <><div className="shell article-shell"><article className="term-article"><span className="eyebrow">{p.glossary}</span><h1>{t.name}</h1><p className="term-definition">{p.desc(t.name)}</p><h2>{p.headings[0]}</h2><p>{p.paragraphs(t.name)[0]}</p><div className="takeaway"><p>{p.takeaway(t.name)}</p></div></article></div><CTA locale={locale}/></>}return <><Hero locale={locale} library/><section className="shell page-top"><div className="glossary-group"><h2>A–Z</h2><div>{englishGlossary.map(t=><a href={`/${locale}/glossary/${t.slug}`} key={t.slug}><h3>{t.name}<ArrowUpRight size={18}/></h3><p>{p.desc(t.name)}</p></a>)}</div></div></section><CTA locale={locale}/></>}
function AppPage({locale}:{locale:NewLocale}){const p=packs[locale];const featureIcons=[Camera,Bell,Sun,Plane,Leaf];return <><Hero locale={locale}/><section className="shell section app-features"><span className="eyebrow">PLANTPAL: AI PLANT CARE</span><h2>{p.ctaTitle}</h2><div className="features-grid">{Object.values(p.categories).map((name,i)=>{const Icon=featureIcons[i];return <div key={name}><Icon size={27}/><h3>{name}</h3><p>{p.desc(name)}</p></div>})}</div></section><CTA locale={locale}/></>}
function MailText({text}:{text:string}){const parts=text.split('support@appsgiant.com');return <>{parts.map((part,i)=><span key={`${i}-${part}`}>{part}{i<parts.length-1&&<a href="mailto:support@appsgiant.com">support@appsgiant.com</a>}</span>)}</>}
function PrivacyPage({locale}:{locale:NewLocale}){const d=privacyContent[locale];return <><div className="shell article-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={`/${locale}`}>{packs[locale].home}</a><span><span aria-hidden="true">/</span><a href={`/${locale}/privacy`}>{d.title}</a></span></nav><article className="term-article legal-content"><span className="eyebrow">{d.eyebrow}</span><h1>{d.title}</h1><p className="legal-note">{d.updated}</p><p className="term-definition">{d.intro}</p>{d.sections.map((section,i)=><section key={section.heading} id={i===5?'account-deletion':undefined}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}><MailText text={paragraph}/></p>)}</section>)}</article></div><CTA locale={locale}/></>}
export async function LocalizedSite({locale,parts,q}:{locale:NewLocale;parts?:string[];q?:string}){const p=packs[locale],r=route(parts);let content:React.ReactNode;if(!r)content=<Home locale={locale}/>;else if(r==='learn')content=<><Hero locale={locale} library/><Library locale={locale} q={q}/><CTA locale={locale}/></>;else if(r==='app')content=<AppPage locale={locale}/>;else if(r==='glossary')content=<Glossary locale={locale}/>;else if(r==='privacy')content=<PrivacyPage locale={locale}/>;else if(parts?.[0]==='learn'&&parts[1])content=<ArticlePage locale={locale} slug={parts[1]}/>;else if(parts?.[0]==='glossary'&&parts[1])content=<Glossary locale={locale} slug={parts[1]}/>;else if(parts?.length===1&&p.categories[parts[0]])content=<><Hero locale={locale} library image={parts[0]==='soil-fertilizer'?'/images/soil-care-hero.webp':undefined}/><Library locale={locale} category={parts[0]} q={q}/><CTA locale={locale}/></>;else notFound();return <main id="main" className="localized-site" lang={p.lang} dir={p.dir}>{content}</main>}

