import {AppProductHero,AppScreenshots} from './app-showcase';
import {notFound} from 'next/navigation';
import {ArrowUpRight,Bell,BookOpen,Camera,Clock,Leaf,MapPin,MessageCircle,NotebookPen,Plane,Sun} from 'lucide-react';
import {englishSeedArticles} from '@/lib/repository';
import {articleForLocale,articlesForLocale} from '@/lib/published-locales';
import {englishGlossary,type Term} from '@/lib/glossary';
import {packs,type NewLocale} from '@/lib/multilingual';
import {localizeFor,extrasFor} from '@/lib/localized';
import {APP_STORE_URL,PLAY_URL,SITE_URL} from '@/lib/config';
import {readingMinutes,type Article} from '@/lib/content';
import {privacyContent} from '@/lib/privacy-content';
import {PlantsIndex,PlantDetail,plantsMetadata,plantMetadata} from './plants-pages';
import {plantBySlug} from '@/lib/plants';

const localePaths=['fr','it','hi','zh','ar','pt','ru','es'] as const;
const route=(parts?:string[])=>parts?.join('/')||'';
const categoryText=(locale:NewLocale,slug:string)=>(extrasFor(locale)?.categoryDescriptions as Record<string,string>|undefined)?.[slug]??packs[locale].libraryText;
function term(locale:NewLocale,t:Term){const l=extrasFor(locale)?.glossary[t.slug];return l?{...t,...l}:t}
export async function localizedMetadata(locale:NewLocale,parts?:string[]){const p=packs[locale],x=extrasFor(locale);const r=route(parts);if(r==='plants')return plantsMetadata(locale);if(parts?.[0]==='plants'&&parts[1]&&parts.length===2){const plant=plantBySlug(parts[1]);if(plant)return plantMetadata(plant,locale)}let title=`PlantPal — ${p.heroTitle} ${p.heroAccent}`;let description=p.heroText;if(r==='learn'){title=p.libraryTitle;description=p.libraryText}else if(r==='app'){title=p.download;description=p.ctaText}else if(r==='glossary'){title=x?.ui.glossaryTitle??p.glossary;description=x?.ui.glossaryText??p.libraryText}else if(r==='privacy'){title=privacyContent[locale].title;description=privacyContent[locale].intro}else{const [first,second]=r.split('/');if(first==='learn'&&second){const a=await articleForLocale(second,locale);if(a){const l=localizeFor(a,locale);title=l.title;description=l.description}}else if(first==='glossary'&&second){const t=englishGlossary.find(x=>x.slug===second);if(t){const l=term(locale,t);title=`${l.name} — ${p.glossary}`;description=l.definition}}else if(first&&p.categories[first]){title=p.categories[first];description=categoryText(locale,first)}}
 const path=r?`/${r}`:'';const languages:Record<string,string>={'he-IL':SITE_URL+'/he'+path,en:SITE_URL+(path||'/')};for(const code of localePaths)languages[packs[code].lang]=SITE_URL+'/'+code+path;return {title,description,alternates:{canonical:SITE_URL+'/'+locale+path,languages},openGraph:{title,description,url:SITE_URL+'/'+locale+path,locale:p.lang.replace('-','_'),type:'website' as const}}}
function Stores({p}:{p:(typeof packs)[NewLocale]}){return <div className="store-buttons"><a className="button" href={APP_STORE_URL} target="_blank" rel="noopener noreferrer">App Store <ArrowUpRight size={15}/></a><a className="button" href={PLAY_URL} target="_blank" rel="noopener noreferrer">Google Play <ArrowUpRight size={15}/></a></div>}
function CTA({locale}:{locale:NewLocale}){const p=packs[locale];return <section className="app-cta shell"><div><span className="eyebrow">PLANTPAL</span><h2>{p.ctaTitle}</h2><p>{p.ctaText}</p><Stores p={p}/></div><div className="cta-side"><img src="/images/app-icon.webp" width="125" height="125" alt="PlantPal"/><span>PlantPal: AI Plant Care</span></div></section>}
function Hero({locale,library=false,image='/images/greenhouse-hero.webp',eyebrow,title,text}:{locale:NewLocale;library?:boolean;image?:string;eyebrow?:string;title?:string;text?:string}){const p=packs[locale];return <section className={`immersive-hero${library?' page-visual-hero':''}`}><img className="immersive-hero-image" src={image} alt="PlantPal"/><div className="hero-shade"/><div className={`shell ${library?'page-visual-inner':'immersive-hero-content'}`}><div className={library?'page-visual-copy':'immersive-hero-copy'}><span className="eyebrow"><Leaf size={16}/>{eyebrow??(library?p.learn:p.heroEyebrow)}</span><h1>{library?(title??p.libraryTitle):<>{p.heroTitle}<br/><em>{p.heroAccent}</em></>}</h1><p>{library?(text??p.libraryText):p.heroText}</p>{!library&&<><Stores p={p}/><a className="hero-learn-link" href={`/${locale}/learn`}>{p.explore}<ArrowUpRight size={18}/></a></>}</div></div></section>}
function Card({article,locale}:{article:Article;locale:NewLocale}){const p=packs[locale],a=localizeFor(article,locale);return <a className={`library-card category-${a.category}`} href={`/${locale}/learn/${a.slug}`}><div className="library-card-icon"><Leaf size={25}/><ArrowUpRight size={18}/></div><span className="eyebrow">{p.categories[a.category]}</span><h3>{a.title}</h3><p>{a.description}</p><span className="card-more"><span><Clock size={14}/>{readingMinutes(a)} {p.minutes}</span><span>{p.read}<ArrowUpRight size={15}/></span></span></a>}
async function Library({locale,category,q=''}:{locale:NewLocale;category?:string;q?:string}){const p=packs[locale],needle=q.toLocaleLowerCase(p.lang);const list=(await articlesForLocale(locale)).filter(a=>{if(category&&a.category!==category)return false;if(!needle)return true;const l=localizeFor(a,locale);return (l.title+' '+l.description).toLocaleLowerCase(p.lang).includes(needle)});return <section className="shell page-top visual-page-content"><form className="library-search" action={category?`/${locale}/${category}`:`/${locale}/learn`}><label htmlFor="localized-search">{p.search}</label><div><input id="localized-search" name="q" defaultValue={q}/><button className="button">{p.search}</button></div></form><nav className="category-pills" aria-label={p.learn}><a href={`/${locale}/learn`}>{p.all}</a>{Object.entries(p.categories).map(([slug,name])=><a href={`/${locale}/${slug}`} key={slug}>{name}</a>)}</nav><div className="results-summary"><span>{list.length} {p.guides}</span></div><div className="library-grid">{list.map(a=><Card article={a} locale={locale} key={a.slug}/>)}</div></section>}
function Home({locale}:{locale:NewLocale}){const p=packs[locale];return <><Hero locale={locale}/><div className="promise-strip"><div className="shell"><span><Camera/>{p.guides}</span><span><Bell/>{p.categories['plant-care']}</span><span><Sun/>{p.soil}</span><span><Plane/>{p.app}</span></div></div><section className="section shell"><div className="section-title"><div><span className="eyebrow">PLANTPAL</span><h2>{p.libraryTitle}</h2></div></div><div className="category-grid">{Object.entries(p.categories).map(([slug,name])=><a className="category-card" href={`/${locale}/${slug}`} key={slug}><Leaf size={27}/><h3>{name}</h3><p>{categoryText(locale,slug)}</p><ArrowUpRight size={18}/></a>)}</div></section><section className="section shell"><div className="library-grid">{englishSeedArticles.slice(0,6).map(a=><Card article={a} locale={locale} key={a.slug}/>)}</div></section><CTA locale={locale}/></>}
async function ArticlePage({locale,slug}:{locale:NewLocale;slug:string}){const source=await articleForLocale(slug,locale);if(!source)notFound();const p=packs[locale],x=extrasFor(locale),a=localizeFor(source,locale);const available=await articlesForLocale(locale);const related=a.related.map(s=>available.find(r=>r.slug===s)).filter(Boolean).slice(0,3) as Article[];return <><div className="shell article-shell"><nav className="breadcrumbs"><a href={`/${locale}`}>{p.home}</a><span>/</span><a href={`/${locale}/${a.category}`}>{p.categories[a.category]}</a></nav><header className="article-header"><span className="eyebrow">{p.categories[a.category]}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><span><Leaf size={16}/>PlantPal</span><span><Clock size={15}/>{readingMinutes(a)} {p.minutes}</span></div></header><div className="article-layout"><article className="article-prose"><div className="takeaway">{x&&<span className="eyebrow">{x.ui.takeawayEyebrow}</span>}<p>{a.takeaway}</p></div>{a.sections.map((s,i)=><section key={s.heading} id={`section-${i+1}`}><h2>{s.heading}</h2>{s.paragraphs.map(t=><p key={t}>{t}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}{a.sources.length>0&&<section className="sources"><h2>{x?.ui.sources??'Sources'}</h2><ul>{a.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a></li>)}</ul></section>}</article><aside className="article-sidebar"><div className="toc">{x&&<span className="eyebrow">{x.ui.tocEyebrow}</span>}{a.sections.map((s,i)=><a key={s.heading} href={`#section-${i+1}`}><span>{String(i+1).padStart(2,'0')}</span>{s.heading}</a>)}</div></aside></div>{related.length>0&&<section className="related-section"><span className="eyebrow">PLANTPAL</span><h2>{x?.ui.relatedTitle??p.all}</h2><div className="library-grid">{related.map(r=><Card article={r} locale={locale} key={r.slug}/>)}</div></section>}</div><CTA locale={locale}/></>}
function Glossary({locale,slug}:{locale:NewLocale;slug?:string}){const p=packs[locale],x=extrasFor(locale);if(slug){const source=englishGlossary.find(t=>t.slug===slug);if(!source)notFound();const t=term(locale,source);const guideSource=englishSeedArticles.find(a=>a.slug===t.related);const guide=guideSource&&localizeFor(guideSource,locale);return <><div className="shell article-shell"><nav className="breadcrumbs"><a href={`/${locale}`}>{p.home}</a><span>/</span><a href={`/${locale}/glossary`}>{p.glossary}</a></nav><article className="term-article"><span className="eyebrow">{x?.ui.glossaryEyebrow??p.glossary}</span><h1>{t.name}</h1><p className="term-definition">{t.definition}</p><h2>{x?.ui.termMeaning??p.glossary}</h2><p>{t.practice}</p><div className="takeaway">{x&&<span className="eyebrow">{x.ui.termInPractice}</span>}<p>{t.example}</p></div>{guide&&<><h2>{x?.ui.termGuide??p.read}</h2><p>{guide.description}</p><a className="button" href={`/${locale}/learn/${guide.slug}`}>{guide.title}</a></>}<div className="related-terms"><a href={`/${locale}/glossary`}>{x?.ui.backToGlossary??p.glossary}</a></div></article></div><CTA locale={locale}/></>}
 const terms=englishGlossary.map(t=>term(locale,t)).sort((a,b)=>a.name.localeCompare(b.name,p.lang));return <><Hero locale={locale} library image="/images/leaf-detail-hero.webp" eyebrow={x?.ui.glossaryEyebrow} title={x?.ui.glossaryTitle} text={x?.ui.glossaryText}/><section className="shell page-top"><div className="glossary-group"><h2>A–Z</h2><div>{terms.map(t=><a href={`/${locale}/glossary/${t.slug}`} key={t.slug}><h3>{t.name}<ArrowUpRight size={18}/></h3><p>{t.definition}</p></a>)}</div></div></section><CTA locale={locale}/></>}
const featureIcons=[Camera,Bell,Sun,Plane,MessageCircle,MapPin,NotebookPen,BookOpen];
function AppPage({locale}:{locale:NewLocale}){const p=packs[locale],x=extrasFor(locale);const features:[string,string][]=x?.appFeatures??Object.entries(p.categories).map(([slug,name])=>[name,categoryText(locale,slug)]);return <><AppProductHero locale={locale} eyebrow="PLANTPAL" title={<>{p.heroTitle}<br/><em>{p.heroAccent}</em></>} description={p.heroText}><Stores p={p}/></AppProductHero><AppScreenshots locale={locale}/><section className="shell section app-features"><span className="eyebrow">PLANTPAL: AI PLANT CARE</span><h2>{p.ctaTitle}</h2><div className="features-grid">{features.map(([title,text],i)=>{const Icon=featureIcons[i%featureIcons.length];return <div key={title}><Icon size={27}/><h3>{title}</h3><p>{text}</p></div>})}</div></section><CTA locale={locale}/></>}
function MailText({text}:{text:string}){const parts=text.split('support@appsgiant.com');return <>{parts.map((part,i)=><span key={`${i}-${part}`}>{part}{i<parts.length-1&&<a href="mailto:support@appsgiant.com">support@appsgiant.com</a>}</span>)}</>}
function PrivacyPage({locale}:{locale:NewLocale}){const d=privacyContent[locale];return <><div className="shell article-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={`/${locale}`}>{packs[locale].home}</a><span><span aria-hidden="true">/</span><a href={`/${locale}/privacy`}>{d.title}</a></span></nav><article className="term-article legal-content"><span className="eyebrow">{d.eyebrow}</span><h1>{d.title}</h1><p className="legal-note">{d.updated}</p><p className="term-definition">{d.intro}</p>{d.sections.map((section,i)=><section key={section.heading} id={i===5?'account-deletion':undefined}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}><MailText text={paragraph}/></p>)}</section>)}</article></div><CTA locale={locale}/></>}
export async function LocalizedSite({locale,parts,q}:{locale:NewLocale;parts?:string[];q?:string}){const p=packs[locale],r=route(parts);let content:React.ReactNode;if(!r)content=<Home locale={locale}/>;else if(r==='plants')content=<PlantsIndex locale={locale}/>;else if(parts?.[0]==='plants'&&parts[1]&&parts.length===2){const plant=plantBySlug(parts[1]);if(!plant)notFound();content=<PlantDetail plant={plant} locale={locale}/>;}else if(r==='learn')content=<><Hero locale={locale} library image="/images/learn-grow-hero.webp"/><Library locale={locale} q={q}/><CTA locale={locale}/></>;else if(r==='app')content=<AppPage locale={locale}/>;else if(r==='glossary')content=<Glossary locale={locale}/>;else if(r==='privacy')content=<PrivacyPage locale={locale}/>;else if(parts?.[0]==='learn'&&parts[1])content=<ArticlePage locale={locale} slug={parts[1]}/>;else if(parts?.[0]==='glossary'&&parts[1])content=<Glossary locale={locale} slug={parts[1]}/>;else if(parts?.length===1&&p.categories[parts[0]])content=<><Hero locale={locale} library image={parts[0]==='soil-fertilizer'?'/images/soil-care-hero.webp':undefined} title={p.categories[parts[0]]} text={categoryText(locale,parts[0])}/><Library locale={locale} category={parts[0]} q={q}/><CTA locale={locale}/></>;else notFound();return <main id="main" className="localized-site" lang={p.lang} dir={p.dir}>{content}</main>}
