import { ArrowUpRight, ArrowLeft, Leaf, Smartphone, Sprout, Droplets, Stethoscope, Shovel, Lightbulb } from 'lucide-react';
import { PLAY_URL, APP_STORE_URL, categories } from '@/lib/config';
export const icons = {Sprout,Droplets,Stethoscope,Shovel,Lightbulb};
export function DownloadButton({light=false}: {light?:boolean}) { return <div className="store-buttons"><a className={`button ${light?'button-light':''}`} href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" aria-label="הורדת PlantPal מ־App Store"><Smartphone size={18}/> App Store <ArrowUpRight size={15}/></a><a className={`button ${light?'button-light':''}`} href={PLAY_URL} target="_blank" rel="noopener noreferrer" aria-label="הורדת PlantPal מ־Google Play"><Smartphone size={18}/> Google Play <ArrowUpRight size={15}/></a></div> }
export function Header() {return <header className="site-header"><div className="shell nav-row"><a className="wordmark" href="/" aria-label="PlantPal — דף הבית"><img src="/images/app-icon.webp" width="38" height="38" alt=""/>Plant<span>Pal</span></a><nav className="desktop-nav" aria-label="ניווט ראשי"><a href="/plant-guides">מדריכי צמחים</a><a href="/learn">לומדים ומגדלים</a><a href="/soil-fertilizer">אדמה ודישון</a><a href="/glossary">מילון מושגים</a><a href="/app">האפליקציה</a></nav><a className="button" href="/app">הורדת PlantPal <ArrowUpRight size={17}/></a><details className="mobile-menu"><summary aria-label="פתיחת התפריט">☰</summary><nav aria-label="ניווט בנייד"><a href="/plant-guides">מדריכי צמחים</a><a href="/learn">לומדים ומגדלים</a><a href="/soil-fertilizer">אדמה ודישון</a><a href="/glossary">מילון מושגים</a><a href="/app">האפליקציה</a></nav></details></div></header>}
export function Footer() {return <footer className="footer"><div className="shell footer-grid"><div><a className="wordmark" href="/"><Leaf/>Plant<span>Pal</span></a><p>קצת ידע.<br/>קצת תשומת לב. הרבה יותר ירוק.</p><span className="muted">נוצר עבורכם ועבור הצמחים שלכם.</span></div><div><h3>מגלים</h3>{categories.slice(0,4).map(c=><a key={c.slug} href={`/${c.slug}`}>{c.name}</a>)}</div><div><h3>ממשיכים לגדול</h3><a href="/tips">טיפים שימושיים</a><a href="/glossary">מילון הצמחים</a><a href="/learn">כל המדריכים</a><a href="/editorial">איך אנחנו כותבים</a></div><div><h3>העוזר האישי של הצמחים שלכם</h3><p>פחות ניחושים. יותר צמיחה.</p><DownloadButton/></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} PlantPal: AI Plant Care</span><nav className="footer-legal" aria-label="מידע משפטי ותמיכה"><a href="/terms">תנאי שימוש</a><a href="/privacy">מדיניות פרטיות</a><a href="/account-deletion">מחיקת חשבון</a></nav></div></footer>}
export function AppCTA() {return <section className="app-cta shell"><div><span className="eyebrow">עזרה קטנה בכל יום</span><h2>הצמחים סומכים עליכם.<br/>אתם יכולים לסמוך על PlantPal.</h2><p>זהו את הצמחים, הבינו מה הם צריכים והפכו כוונות טובות לשגרת טיפול שקל לשמור.</p><DownloadButton light/></div><div className="cta-side"><img src="/images/app-icon.webp" width="125" height="125" alt="סמל אפליקציית PlantPal"/><span>PlantPal: AI Plant Care</span><small>זמינה ל־iOS ול־Android</small></div></section>}
export function CategoryCards(){return <div className="category-grid">{categories.map(c=>{const Icon=icons[c.icon];return <a key={c.slug} className="category-card" href={`/${c.slug}`}><Icon size={27} strokeWidth={1.5}/><h3>{c.name}</h3><p>{c.short}</p><ArrowUpRight size={18}/></a>})}</div>}
export function SectionTitle({eyebrow,title,link,href='/learn'}:{eyebrow:string,title:string,link?:string,href?:string}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{link&&<a className="text-link" href={href}>{link} <ArrowLeft size={18}/></a>}</div>}
