import { ArrowUpRight, ArrowRight, Leaf, Smartphone, Sprout, Droplets, Stethoscope, Shovel, Lightbulb } from 'lucide-react';
import { PLAY_URL, APP_STORE_URL, categories } from '@/lib/config';
export const icons = {Sprout,Droplets,Stethoscope,Shovel,Lightbulb};
export function DownloadButton({light=false}: {light?:boolean}) { return <div className="store-buttons"><a className={`button ${light?'button-light':''}`} href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" aria-label="Download PlantPal on the App Store"><Smartphone size={18}/> App Store <ArrowUpRight size={15}/></a><a className={`button ${light?'button-light':''}`} href={PLAY_URL} target="_blank" rel="noopener noreferrer" aria-label="Download PlantPal on Google Play"><Smartphone size={18}/> Google Play <ArrowUpRight size={15}/></a></div> }
export function Header() {return <header className="site-header"><div className="shell nav-row"><a className="wordmark" href="/" aria-label="PlantPal home"><img src="/images/app-icon.webp" width="38" height="38" alt=""/>Plant<span>Pal</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="/plant-guides">Plant guides</a><a href="/learn">Learn & grow</a><a href="/soil-fertilizer">Soil & fertilizer</a><a href="/glossary">Glossary</a><a href="/app">The app</a></nav><a className="button" href="/app">Get PlantPal <ArrowUpRight size={17}/></a><details className="mobile-menu"><summary aria-label="Open navigation">☰</summary><nav aria-label="Mobile navigation"><a href="/plant-guides">Plant guides</a><a href="/learn">Learn & grow</a><a href="/soil-fertilizer">Soil & fertilizer</a><a href="/glossary">Glossary</a><a href="/app">The app</a></nav></details></div></header>}
export function Footer() {return <footer className="footer"><div className="shell footer-grid"><div><a className="wordmark" href="/"><Leaf/>Plant<span>Pal</span></a><p>A little knowledge.<br/>A little care. A lot more green.</p><span className="muted">Made for you and your plants.</span></div><div><h3>Explore</h3>{categories.slice(0,4).map(c=><a key={c.slug} href={`/${c.slug}`}>{c.name}</a>)}</div><div><h3>Keep growing</h3><a href="/tips">Tips & tricks</a><a href="/glossary">Plant glossary</a><a href="/learn">All articles</a><a href="/editorial">Our editorial approach</a></div><div><h3>Your plant care companion</h3><p>Less guessing. More growing.</p><DownloadButton/></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} PlantPal: AI Plant Care</span><span>Healthier plants. Happier days. <Leaf size={15}/></span></div></footer>}
export function AppCTA() {return <section className="app-cta shell"><div><span className="eyebrow">A LITTLE HELP, EVERY DAY</span><h2>Your plants have you.<br/>You have PlantPal.</h2><p>Meet your plants, understand their needs, and turn good intentions into a care routine that sticks.</p><DownloadButton light/></div><div className="cta-side"><img src="/images/app-icon.webp" width="125" height="125" alt="PlantPal app icon"/><span>PlantPal: AI Plant Care</span><small>Available on iOS & Android</small></div></section>}
export function CategoryCards(){return <div className="category-grid">{categories.map(c=>{const Icon=icons[c.icon];return <a key={c.slug} className="category-card" href={`/${c.slug}`}><Icon size={27} strokeWidth={1.5}/><h3>{c.name}</h3><p>{c.short}</p><ArrowUpRight size={18}/></a>})}</div>}
export function SectionTitle({eyebrow,title,link,href='/learn'}:{eyebrow:string,title:string,link?:string,href?:string}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{link&&<a className="text-link" href={href}>{link} <ArrowRight size={18}/></a>}</div>}

