'use client';
import { ArrowUpRight, ArrowLeft, Leaf, Smartphone, Sprout, Droplets, Stethoscope, Shovel, Lightbulb, Languages } from 'lucide-react';
import {usePathname} from 'next/navigation';
import {useEffect} from 'react';
import { PLAY_URL, APP_STORE_URL, categories } from '@/lib/config';
export const icons = {Sprout,Droplets,Stethoscope,Shovel,Lightbulb};
export function DownloadButton({light=false}: {light?:boolean}) { return <div className="store-buttons"><a className={`button ${light?'button-light':''}`} href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" aria-label="הורדת PlantPal מ־App Store"><Smartphone size={18}/> App Store <ArrowUpRight size={15}/></a><a className={`button ${light?'button-light':''}`} href={PLAY_URL} target="_blank" rel="noopener noreferrer" aria-label="הורדת PlantPal מ־Google Play"><Smartphone size={18}/> Google Play <ArrowUpRight size={15}/></a></div> }
function alternatePath(pathname:string, english:boolean){if(english)return pathname.replace(/^\/en(?=\/|$)/,'')||'/';return '/en'+(pathname==='/'?'':pathname)}
export function SkipLink(){const pathname=usePathname()||'/';const en=pathname==='/en'||pathname.startsWith('/en/');return <a className="skip-link" href="#main">{en?'Skip to content':'דילוג לתוכן'}</a>}
export function Header() {const pathname=usePathname()||'/';const en=pathname==='/en'||pathname.startsWith('/en/');const p=en?'/en':'';useEffect(()=>{document.documentElement.lang=en?'en':'he-IL';document.documentElement.dir=en?'ltr':'rtl'},[en]);return <header className="site-header" dir={en?'ltr':'rtl'}><div className="shell nav-row"><a className="wordmark" href={p||'/'} aria-label={en?'PlantPal home':'PlantPal — דף הבית'}><img src="/images/app-icon.webp" width="38" height="38" alt=""/>Plant<span>Pal</span></a><nav className="desktop-nav" aria-label={en?'Main navigation':'ניווט ראשי'}><a href={`${p}/plant-guides`}>{en?'Plant guides':'מדריכי צמחים'}</a><a href={`${p}/learn`}>{en?'Learn & grow':'לומדים ומגדלים'}</a><a href={`${p}/soil-fertilizer`}>{en?'Soil & fertilizer':'אדמה ודישון'}</a><a href={`${p}/glossary`}>{en?'Glossary':'מילון מושגים'}</a><a href={`${p}/app`}>{en?'The app':'האפליקציה'}</a></nav><a className="language-switch" href={alternatePath(pathname,en)} hrefLang={en?'he':'en'}><Languages size={16}/>{en?'עברית':'English'}</a><a className="button" href={`${p}/app`}>{en?'Get PlantPal':'הורדת PlantPal'} <ArrowUpRight size={17}/></a><details className="mobile-menu"><summary aria-label={en?'Open navigation':'פתיחת התפריט'}>☰</summary><nav aria-label={en?'Mobile navigation':'ניווט בנייד'}><a href={`${p}/plant-guides`}>{en?'Plant guides':'מדריכי צמחים'}</a><a href={`${p}/learn`}>{en?'Learn & grow':'לומדים ומגדלים'}</a><a href={`${p}/soil-fertilizer`}>{en?'Soil & fertilizer':'אדמה ודישון'}</a><a href={`${p}/glossary`}>{en?'Glossary':'מילון מושגים'}</a><a href={`${p}/app`}>{en?'The app':'האפליקציה'}</a><a href={alternatePath(pathname,en)}>{en?'עברית':'English'}</a></nav></details></div></header>}
export function Footer() {const pathname=usePathname()||'/';const en=pathname==='/en'||pathname.startsWith('/en/');const p=en?'/en':'';return <footer className="footer" dir={en?'ltr':'rtl'}><div className="shell footer-grid"><div><a className="wordmark" href={p||'/'}><Leaf/>Plant<span>Pal</span></a><p>{en?<>A little knowledge.<br/>A little care. A lot more green.</>:<>קצת ידע.<br/>קצת תשומת לב. הרבה יותר ירוק.</>}</p><span className="muted">{en?'Made for you and your plants.':'נוצר עבורכם ועבור הצמחים שלכם.'}</span></div><div><h3>{en?'Explore':'מגלים'}</h3>{(en?[['plant-guides','Plant guides'],['plant-care','Plant care'],['troubleshooting','Plant problems'],['soil-fertilizer','Soil & fertilizer']]:categories.slice(0,4).map(c=>[c.slug,c.name])).map(([slug,name])=><a key={slug} href={`${p}/${slug}`}>{name}</a>)}</div><div><h3>{en?'Keep growing':'ממשיכים לגדול'}</h3><a href={`${p}/tips`}>{en?'Tips & tricks':'טיפים שימושיים'}</a><a href={`${p}/glossary`}>{en?'Plant glossary':'מילון הצמחים'}</a><a href={`${p}/learn`}>{en?'All articles':'כל המדריכים'}</a><a href={`${p}/editorial`}>{en?'Our editorial approach':'איך אנחנו כותבים'}</a></div><div><h3>{en?'Your plant care companion':'העוזר האישי של הצמחים שלכם'}</h3><p>{en?'Less guessing. More growing.':'פחות ניחושים. יותר צמיחה.'}</p><DownloadButton/></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} PlantPal: AI Plant Care</span><nav className="footer-legal" aria-label={en?'Legal and account support':'מידע משפטי ותמיכה'}><a href={`${p}/terms`}>{en?'Terms & Conditions':'תנאי שימוש'}</a><a href={`${p}/privacy`}>{en?'Privacy Policy':'מדיניות פרטיות'}</a><a href={`${p}/account-deletion`}>{en?'Account deletion':'מחיקת חשבון'}</a></nav></div></footer>}
export function AppCTA() {return <section className="app-cta shell"><div><span className="eyebrow">עזרה קטנה בכל יום</span><h2>הצמחים סומכים עליכם.<br/>אתם יכולים לסמוך על PlantPal.</h2><p>זהו את הצמחים, הבינו מה הם צריכים והפכו כוונות טובות לשגרת טיפול שקל לשמור.</p><DownloadButton light/></div><div className="cta-side"><img src="/images/app-icon.webp" width="125" height="125" alt="סמל אפליקציית PlantPal"/><span>PlantPal: AI Plant Care</span><small>זמינה ל־iOS ול־Android</small></div></section>}
export function CategoryCards(){return <div className="category-grid">{categories.map(c=>{const Icon=icons[c.icon];return <a key={c.slug} className="category-card" href={`/${c.slug}`}><Icon size={27} strokeWidth={1.5}/><h3>{c.name}</h3><p>{c.short}</p><ArrowUpRight size={18}/></a>})}</div>}
export function SectionTitle({eyebrow,title,link,href='/learn'}:{eyebrow:string,title:string,link?:string,href?:string}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{link&&<a className="text-link" href={href}>{link} <ArrowLeft size={18}/></a>}</div>}
