import type {Category} from './config';
export type Section={heading:string;paragraphs:string[];bullets?:string[]};
export type Article={slug:string;title:string;category:Category;description:string;takeaway:string;sections:Section[];related:string[];sources:{title:string;url:string}[];publishedAt:string;updatedAt:string;author:string;status:'draft'|'published';contentHash?:string};
export const section=(heading:string,text:string,bullets?:string[]):Section=>({heading,paragraphs:text.split('\n\n'),...(bullets?{bullets}:{})});
const article=(slug:string,title:string,category:Category,description:string,takeaway:string,sections:Section[],related:string[],sources:Article['sources']=[]):Article=>({slug,title,category,description,takeaway,sections,related,sources,publishedAt:'2026-09-22T20:00:00.000Z',updatedAt:'2026-09-22T20:00:00.000Z',author:'PlantPal',status:'published'});
const s=section;
export const articles:Article[]=[
article('houseplant-care-for-beginners','Houseplant care for beginners: your first healthy routine','plant-care','Start caring for houseplants with a simple routine for light, watering, drainage, feeding, and checking for problems.','Choose a plant for the light you actually have. Then build a habit of checking its needs before acting.',[
s('Start with your home, then choose the plant','Before buying a plant, spend a day noticing the light where you want it to live. Does direct sun reach the leaves, and for how long? A bright room can still have a dark corner. Distance from a window, neighboring buildings, curtains, and the season all change what a plant receives.\n\nChoose a plant whose needs overlap with that location. A sun-loving succulent is unlikely to thrive on a shelf far from the window. A tolerant foliage plant may cope better there, but even a low-light plant needs usable light. Beginning with one or two plants gives you time to understand your space.'),
s('Set up a pot that makes watering easier','Keep the nursery pot inside a decorative outer pot if the outer one has no drainage hole. This lets you lift the plant out, water thoroughly, and empty the excess. Check that water has not collected out of sight. Use a potting mix designed for container plants rather than soil dug from the garden.\n\nAvoid repotting a healthy new plant just because you have brought it home. First inspect its roots, mix, and drainage. Repot promptly when the current setup is causing a problem; otherwise give yourself time to learn how quickly the pot dries.'),
s('Use a check-in routine, not a fixed watering rule','Set aside a few minutes to inspect your plants. Touch the mix below the surface, lift the pot, and look at the leaves. A light pot with dry mix tells a different story from a heavy pot with drooping leaves. Water only when the plant’s preferred drying point has arrived.\n\nFor many leafy tropical plants that means allowing some of the upper mix to dry; for many succulents it means a much more complete dry-down. Once you water, wet the root ball evenly and let it drain. Record what you noticed so the next check becomes easier.', ['Check moisture before watering.','Look underneath leaves for insects or unusual marks.','Empty saucers and decorative pots.','Notice new growth and changes in light.']),
s('Add feeding after the basics are working','Fertilizer supplies mineral nutrients; it cannot replace light or revive roots sitting in stagnant water. Read the potting-mix bag to see whether it already contains fertilizer. When an established plant is growing, choose a feed labeled for that plant and follow its directions.\n\nPlantPal can help you identify a new arrival, keep care information together, and set reminders to check watering and feeding. Treat those reminders as a nudge to observe the plant. Your room, season, and pot still decide what it needs today.')
],['how-to-water-houseplants','bright-indirect-light','potting-mix-vs-garden-soil']),
article('how-to-water-houseplants','How to water houseplants: check the roots, not the calendar','plant-care','Learn when and how to water indoor plants, read potting-mix moisture, and avoid the most common watering mistakes.','The right time to water depends on the plant and how far its root ball has dried—not the day of the week.',[
s('Why “once a week” is only a starting point','Two plants in matching pots can dry at very different rates. A sunny window, active growth, warm air, and a porous clay pot can speed up drying. A large pot, dense mix, and dim winter light can slow it down. A schedule that worked in July may keep roots wet for too long in December.\n\nBuild a checking schedule instead. Start by checking more often than you expect to water. Over time, you will recognize the weight of a dry pot and the feel of the mix. Record the conditions as well as the date; the interval is a useful observation, not a rule.'),
s('Check more than the surface','Feel the mix below the top layer without repeatedly disturbing roots. For deeper pots, a clean wooden skewer can give another clue: damp particles clinging to it suggest moisture remains. Lift the pot when possible. A crusty surface can hide wet mix underneath, especially in a large container.\n\nInterpret the result for the species. A fern should not be treated like a snake plant. A cheap moisture probe can help compare readings, but salts, the mix, and poor contact affect its accuracy. Confirm readings with touch and pot weight rather than trusting one number.'),
s('Water the whole root ball, then let it drain','When the plant needs water, pour slowly across the surface rather than repeatedly wetting one spot. Pause if water runs down a gap beside the pot. Continue until the mix is evenly moistened and excess can leave through the drainage holes. Allow the pot to drain and empty the saucer.\n\nIf very dry mix repels water, a short, monitored soak from below can help it absorb moisture again. Remove the pot once the root ball has rehydrated and let it drain fully. Do not leave it standing in water indefinitely, and do not assume runoff proves the center became wet.'),
s('Make the next watering a better decision','Notice how the plant and pot change over the following days. If the mix stays wet far longer than usual, review light, pot size, drainage, and root condition before adding more water. If it dries extremely fast, inspect for a tightly packed root ball.\n\nUse PlantPal’s watering reminders as check-in prompts. A reminder is most useful when you pair it with the question “does this plant need water now?” That small habit protects plants from both accidental neglect and enthusiastic overwatering.')
],['overwatering-vs-underwatering','bottom-watering-houseplants','root-rot-houseplants']),
article('bright-indirect-light','What is bright indirect light? A room-by-room guide','plant-care','Understand bright indirect light, window direction, seasonal changes, and how to choose a better location for indoor plants.','Bright indirect light is strong daylight reaching the plant without a sustained beam of direct sun on its leaves.',[
s('Look at the leaves, not the room','A room may look bright to your eyes because a window is in your line of sight. The plant on a shelf across that room may receive much less light. Stand where the foliage is, look toward the window, and notice what blocks the sky. A plant squeezed behind another plant receives a different light environment from the one in front.\n\nDirect sunlight usually makes distinct shadows and a bright patch that moves across leaves. Indirect light arrives after scattering or passing through a suitable sheer curtain. These are practical descriptions, not precise guarantees of intensity.'),
s('Use window direction as a clue','In the Northern Hemisphere, a south-facing window often receives stronger and longer direct sun than a north-facing one; the broad pattern reverses in the Southern Hemisphere. East windows can provide gentler morning sun, while west windows may deliver hotter afternoon exposure. Buildings, trees, roof overhangs, and latitude can overturn these expectations.\n\nObserve the actual location at several times of day. A plant can spend the morning in indirect light and the afternoon in a strong sunbeam. Moving it a little sideways may change exposure more usefully than moving it far into the room.'),
s('Measure consistently and compare','A light reading is useful when you take it at leaf height, facing the light source, without shading the sensor. Measure in the morning, around midday, and later in the day. Lux is a measure weighted for human vision, so it helps compare locations but is not a complete measure of plant-usable light.\n\nPlantPal’s light meter can help you explore which places are brighter or dimmer. Phone sensors and camera-based estimates vary, so treat readings as guidance. Do not translate one instant reading into a promise that a plant has received enough light for the whole day.'),
s('Move plants gradually','Plants grown in shade may scorch when moved suddenly into intense sun. Introduce the brighter exposure in steps and watch new growth and leaf condition. Bleached or crispy patches facing the glass suggest a different issue from slow, stretched growth in a dark corner.\n\nRecheck locations as the season changes. The sun’s path, day length, and the leaves on outdoor trees change the light reaching your home. Save the plant’s zone and light needs in PlantPal so your care notes reflect where it actually lives.')
],['low-light-houseplants','using-a-plant-light-meter','houseplant-care-for-beginners']),
article('potting-mix-vs-garden-soil','Potting mix vs. garden soil: what belongs in a plant pot?','soil-fertilizer','Compare potting mix, potting soil, garden soil, and compost so you can choose the right root environment for container plants.','Choose a growing medium labeled for containers. Garden soil and compost are not automatic substitutes for potting mix.',[
s('A pot asks different things of soil','In the ground, roots can explore a large and varied environment. In a pot, they depend on a small volume that must hold moisture while keeping enough air around the roots. The container’s height, drainage holes, and material all influence how that volume behaves.\n\nSoil dug from a garden may pack tightly after repeated watering. Its fine particles can leave fewer useful air spaces in a container, and it may bring weeds or pests indoors. Adding a few stones at the bottom does not change the structure of the mix surrounding the roots.'),
s('Read the label behind the name','“Potting soil” and “potting mix” are sometimes used interchangeably on retail bags. Many mixes contain no field soil at all. They may combine coir, bark, peat alternatives, perlite, composted materials, and a starter fertilizer. The ingredient list and intended use matter more than the marketing name.\n\nLook for container or indoor-plant use, then consider the plant. A moisture-loving fern and a drought-tolerant succulent need different balances. Also check whether feed is already included, so you do not begin adding fertilizer on top of an existing nutrient supply.'),
s('Understand what amendments contribute','Coir and similar fibrous materials help hold water. Coarse bark can create structure in blends for many aroids. Perlite and pumice are mineral ingredients often used to adjust air space and weight. Compost contributes organic matter and nutrients, but its properties vary and it is not a universal stand-alone medium.\n\nMore ingredients do not automatically create a better blend. Start with a suitable commercial mix and make changes to solve an observed problem. If a plant dries too slowly in a dim room, reconsider the pot and light before endlessly adding amendments.'),
s('Test the mix in your conditions','Moisten a small amount before repotting and observe how it takes up water. After potting, water evenly and check that drainage is open. Then monitor the actual drying pattern. A loose-looking mix in a large pot can still stay wet for a long time.\n\nKeep the bag or record its ingredients and any fertilizer claim in your plant notes. When a mix works well for one plant, that record helps you repeat the result. When it does not, change one variable at a time rather than replacing every part of the setup.')
],['perlite-vs-pumice','repotting-houseplants','coco-coir-vs-peat']),
article('overwatering-vs-underwatering','Overwatering or underwatering? How to tell the difference','troubleshooting','Drooping and yellow leaves can have opposite causes. Use soil moisture, pot weight, and root condition to decide what to do.','Drooping describes a symptom. Check the root environment before deciding whether more water will help.',[
s('Begin with the pot, not the leaf','A thirsty plant and a plant with damaged, waterlogged roots can both wilt. The first lacks available water; the second may be unable to take it up. If you water every drooping plant immediately, you can make the second problem worse.\n\nCheck moisture at more than one depth, lift the pot, and inspect the saucer or outer container. Look at when you last watered and whether the room recently became colder or darker. Those clues help explain the symptom more reliably than leaf color alone.'),
s('Clues that the plant has become too dry','A very light pot, dry root ball, and mix shrinking away from the container suggest significant drying. Some plants develop thin, floppy leaves; others curl or lose firmness. Crispy edges can appear, but similar damage also has other causes.\n\nWater a dry plant slowly and evenly, checking that the center of the root ball actually absorbs moisture. Let it drain. A short bottom soak can help water-repellent mix, but repeated severe drying deserves a review of your checking routine, pot size, and light exposure.'),
s('Clues that the root zone stays too wet','A heavy pot and persistently wet mix alongside soft, collapsing growth suggest a different problem. Water trapped in an outer pot, blocked drainage, an oversized container, or reduced light can all prolong wetness. Overwatering often means watering again before roots have had enough air—not merely pouring a large amount once.\n\nStop adding water while you investigate. If decline is continuing or the mix smells unpleasant, carefully examine the roots. Soft, disintegrating roots need more attention than a plant that is simply a little wetter than ideal. See the root-rot guide before taking action.'),
s('Check whether something else changed','Heat, cold drafts, pests, transplant stress, and intense sun can also cause drooping. Write down the sequence: what changed first, when the symptoms appeared, and whether they affect old or new leaves. Avoid simultaneously repotting, spraying, fertilizing, and relocating unless the evidence calls for it.\n\nAfter correcting the likely cause, watch healthy tissue and new growth. Damaged leaves may never look perfect again. Progress means the problem stops spreading and the plant resumes stable growth—not that every brown tip turns green.')
],['how-to-water-houseplants','root-rot-houseplants','yellow-leaves-houseplants']),
article('repotting-houseplants','How to repot a houseplant without overdoing it','plant-care','Find out when a houseplant needs repotting, how to choose a container, and what to do before and after moving its roots.','Repot for a reason: crowded roots, failing mix, or a container problem. A bigger pot is not always a better home.',[
s('Check whether repotting solves the problem','Roots circling densely around the root ball, unusually fast drying, or a plant repeatedly becoming unstable can justify a closer look. A single root emerging from a drainage hole is only one clue. Some roots explore openings long before the whole pot is crowded.\n\nSlide the plant out carefully when the mix is manageable and support the root ball. Look at the amount of root compared with mix. If roots have room and the medium still performs well, the plant may need better light or a changed watering routine rather than a new container.'),
s('Choose the next pot thoughtfully','For a healthy plant moving up in size, choose a modest increase instead of surrounding a small root ball with a large volume of damp mix. Use drainage holes and a stable shape. Porous terracotta often dries faster than plastic, which can be helpful or inconvenient depending on the plant and your room.\n\nPrepare an appropriate potting mix before starting. Check whether it contains fertilizer. Moisten dusty ingredients gently and avoid breathing the dust. Keep the growing point at its previous level unless a species-specific method says otherwise.'),
s('Move the plant with minimal root damage','Remove loose old mix and gently ease apart tightly circling roots when needed. Do not tear healthy roots apart simply to make the root ball look tidy. If roots are unhealthy, address that issue separately and clean tools between plants.\n\nAdd enough mix beneath the plant to place it at the correct height. Fill around the sides, settle the mix gently, and leave space at the rim for watering. Do not compress the medium into a hard block. Water according to the species and the condition of its roots, then allow excess to drain.'),
s('Give the roots time to adjust','Keep the plant in suitable, stable light and protect it from abrupt changes. Check moisture rather than reusing the old watering interval: the fresh mix and new pot may dry differently. Avoid treating temporary stress with extra fertilizer.\n\nRecord the repotting date, pot size, and mix. Inspect the plant over the following weeks for stable leaves and fresh growth. In PlantPal, update your care notes and reminders so the routine matches its new home rather than its old container.')
],['potting-mix-vs-garden-soil','root-rot-houseplants','terracotta-vs-plastic-pots']),
article('fertilizing-houseplants','How to fertilize houseplants: a practical feeding guide','soil-fertilizer','Understand when indoor plants need fertilizer, how to read feeding directions, and when to pause feeding instead of adding more.','Feed a healthy, actively growing plant according to the product label. Fertilizer is not a substitute for adequate light or healthy roots.',[
s('Decide whether the plant needs feeding','Consider growth, light, season, and the medium before reaching for a bottle. A plant producing leaves in good light has different demands from one resting in a dim winter room. Recently purchased plants or newly repotted specimens may already have fertilizer in their mix.\n\nYellow leaves alone do not prove a nutrient deficiency. Persistent wetness, root damage, pests, and ordinary leaf aging can also change color. Start by checking the growing conditions. Adding nutrients to a struggling root system can create another problem without solving the first.'),
s('Read the directions for the exact product','Liquid concentrates, ready-to-use liquids, soluble powders, and coated granules use different application methods. A capful of one product is not equivalent to a capful of another. Confirm the intended plants, dilution, application amount, and repeat interval on the container in your hands.\n\nMeasure with a dedicated tool and label any prepared solution clearly. Do not mix products together unless their instructions explicitly allow it. More concentrated feed does not make up for a missed application, and a stronger dose can damage roots.'),
s('Choose a format you can use consistently','Liquid feed makes it straightforward to decide whether to fertilize at an individual watering. Soluble powders can be economical for a larger collection but need careful measuring. Controlled-release granules spread nutrient release over time, which reduces frequent mixing but makes immediate adjustment less precise.\n\nWhichever format you choose, track what is already in the pot. Combining pre-fertilized mix, granules, and frequent liquid feed without calculating the overlap can oversupply nutrients. Start with a simple approach and observe growth rather than stacking products.'),
s('Pause when conditions call for it','If a plant is severely dry, has damaged roots, or has stopped growing because the room is too dark or cold, correct that situation before continuing a feeding routine. If white deposits and worsening tip damage appear, review the water source and fertilizer use together.\n\nPlantPal’s fertilizing reminders can help you remember a check, but review the plant and product label before every application. Record the product name and last feeding date. That makes it easier to pause a routine seasonally and restart thoughtfully when growth resumes.')
],['npk-fertilizer-numbers','liquid-vs-slow-release-fertilizer','fertilizer-burn-houseplants']),
article('npk-fertilizer-numbers','NPK numbers explained: reading a fertilizer label','soil-fertilizer','Decode nitrogen, phosphate, and potash on fertilizer labels and learn why concentration, dilution, and micronutrients matter.','The three numbers describe nutrient concentrations by weight. They do not rank how good a fertilizer is for your plant.',[
s('What the three numbers mean','On a conventional fertilizer label, the first number is the percentage of nitrogen, the second is available phosphate expressed as P₂O₅, and the third is soluble potash expressed as K₂O. These reporting conventions mean the last two numbers are not simply percentages of elemental phosphorus and potassium.\n\nA 10-10-10 product has a higher concentration of each listed nutrient than a 1-1-1 product. That does not mean you should apply the same amount of both. The manufacturer’s dilution and application instructions determine how much nutrient ultimately reaches a plant.'),
s('Think about the whole nutrient supply','Nitrogen is involved in proteins and chlorophyll. Phosphorus participates in energy transfer and other processes. Potassium contributes to functions including water regulation. Plants also need other elements, so the three front-label numbers do not tell the whole nutritional story.\n\nCheck the guaranteed analysis for secondary nutrients and micronutrients, and consider what the potting mix and irrigation water already supply. A large phosphorus number is not a universal shortcut to flowers. Light, maturity, temperature, and overall health influence flowering too.'),
s('Compare products at the working dilution','Imagine comparing a concentrated liquid with a mild ready-to-use product. The concentrated bottle may show larger numbers but require much greater dilution. Comparing only the label percentages can lead you to choose on the wrong basis.\n\nFor a practical purchase decision, compare the intended plant types, application method, number of usable applications, and whether you can measure it accurately. Avoid inventing a conversion between pump counts or cap sizes from different brands. Formulas and dispensers can change.'),
s('Keep a useful feeding record','Save the exact product name, analysis, and current label instructions with your care notes. Include whether the mix was pre-fertilized and when you last applied feed. This is more informative than a note that only says “fertilized.”\n\nIf growth is weak, investigate the environment before changing to a stronger formulation. A plant cannot use unlimited nutrients to compensate for darkness or oxygen-starved roots. Start with an appropriate houseplant product and a repeatable routine, then adjust based on evidence.')
],['fertilizing-houseplants','liquid-vs-slow-release-fertilizer','fertilizer-burn-houseplants']),
article('perlite-vs-pumice','Perlite vs. pumice: which potting-mix amendment fits?','soil-fertilizer','Compare perlite and pumice for indoor plants, including weight, water behavior, particle size, and how to choose an amendment.','Both can change a mix’s physical structure. Choose by particle size, weight, and how the complete mix behaves in your pot.',[
s('What these pale particles actually do','Perlite is a heat-expanded volcanic material. Pumice is naturally porous volcanic rock. Both are used in potting blends to alter the balance of solids, water, and air. Neither ingredient replaces a balanced growing medium or acts as a complete fertilizer.\n\nThe result depends on the grade and amount you add. Fine particles behave differently from coarse ones, and a small handful cannot transform a large volume of dense material. Judge an amendment as part of the whole mix rather than treating it as a guarantee of drainage.'),
s('When lighter perlite is useful','Perlite’s low weight can be convenient in large pots, hanging planters, and containers that need to be moved. It is widely available in horticultural grades. Its lightness also means pieces can migrate upward during watering, leaving a scattered white surface.\n\nMoisten it gently before mixing and avoid breathing dust. Look for a grade intended for horticulture. If your main problem is a top-heavy plant falling over, perlite’s low weight may be less useful than a heavier mineral amendment or a more stable outer container.'),
s('When heavier pumice is useful','Pumice generally adds more weight than perlite, which can suit top-heavy specimens and mixes where you want particles to remain distributed. Its pores hold some moisture while the spaces between particles can help preserve air in the blend.\n\nAvailability, cost, and particle sizes vary by location. Avoid assuming a bag of very fine pumice behaves like a coarse grade shown in a recipe. Check dust content and grain size, and handle it with the same care you would use for other dusty mineral ingredients.'),
s('Choose through a small, observable trial','Make a small test batch with a suitable base mix and one amendment. Pot similar plants only when they actually need repotting, then compare drying behavior in their real locations. Keep notes about proportions, pot material, and watering.\n\nIf a mix stays wet, check for blocked drainage or an oversized pot before increasing mineral content repeatedly. If it dries too quickly, a very coarse blend may demand more attention than you can give. The best choice is the one that balances the plant’s needs with your conditions and routine.')
],['potting-mix-vs-garden-soil','aroid-potting-mix','coco-coir-vs-peat']),
article('coco-coir-vs-peat','Coco coir vs. peat: understanding moisture-retaining ingredients','soil-fertilizer','Learn how coconut coir and peat behave in potting mixes, what to check on labels, and how to avoid overly wet root zones.','Coir and peat help manage moisture, but neither should be mistaken for a complete, ready-to-use plant-care system.',[
s('Why these ingredients appear in mixes','Fibrous ingredients help a growing medium hold water between waterings. Coir is processed from coconut husks; horticultural peat comes from accumulated plant material in peatlands. They often appear alongside ingredients that add structure, adjust pH, or supply nutrients.\n\nA bag of coir or peat alone is different from a formulated potting mix. A complete blend may include amendments and fertilizer that are absent from the raw ingredient. Read the label rather than assuming that two similarly colored bags can be used in the same way.'),
s('What to check when buying coir','Coir may be sold as fine pith, fibers, chips, or compressed blocks. These forms behave differently. A compressed block needs preparation before use, and the manufacturer should explain hydration and any washing or buffering already performed.\n\nProcessing quality matters because residual salts and nutrient interactions can affect plant growth. Choose a reputable horticultural product with clear preparation guidance. Do not assume that soaking every brand in the same homemade solution is necessary or helpful.'),
s('What to understand about peat','Peat-based components can hold substantial water and are often adjusted with other ingredients in commercial mixes. When allowed to become very dry, some blends can be difficult to rewet. Peat extraction also raises environmental concerns because peatlands store carbon and support specialized habitats.\n\nPeat-free products use a range of alternatives, so “peat-free” does not describe one standardized watering behavior. A wood-fiber blend may dry differently from a coir-rich blend. Switching materials is a reason to observe moisture again, not simply carry over an old calendar.'),
s('Make the whole mix your unit of comparison','Compare ingredient lists, intended plants, preparation requirements, and included nutrients. For an indoor collection, consistency and clear labeling are valuable. Keep a note of which mix went into each pot so you can understand why two similar plants dry at different rates.\n\nIf you want to reduce peat use, try a suitable peat-free container mix and adjust your checking routine. Evaluate plant growth and root health over time. There is no single raw ingredient that removes the need for drainage, appropriate light, and attentive watering.')
],['potting-mix-vs-garden-soil','perlite-vs-pumice','how-to-water-houseplants']),
article('liquid-vs-slow-release-fertilizer','Liquid vs. controlled-release fertilizer for houseplants','soil-fertilizer','Compare liquid feeds, soluble powders, and controlled-release granules for indoor plant care and choose a manageable routine.','Liquid feed offers frequent control; coated granules offer longer intervals. Both still require accurate dosing and suitable growing conditions.',[
s('Liquid feed gives you a decision at each application','A liquid concentrate or dissolved powder lets you choose whether to add nutrients at a particular watering. That flexibility is useful when growth changes through the year or when individual plants need different treatment. It also makes it easy to pause feeding while you investigate a problem.\n\nThe tradeoff is repeated measuring and record-keeping. A missed feed should not be followed by a double-strength one. Follow the label for your product and use a measuring tool that makes the required small amount practical.'),
s('Coated granules release nutrients over time','Controlled-release products commonly use a coating to regulate how nutrients leave each granule. Release depends on the formulation and environmental conditions, including temperature and moisture. The duration printed on the package is tied to specified conditions, not an exact expiry date for every room.\n\nThis format can suit a larger collection when you want fewer mixing tasks. The tradeoff is less immediate control once granules are distributed through the medium. Record the application date and amount so you do not add another product simply because you forgot what was already there.'),
s('Do not confuse all granular products','A dry granular fertilizer is not automatically controlled-release. Some soluble granules are designed to dissolve in water first, while other products are applied to the mix. Organic materials may release nutrients as they break down, with behavior that differs from coated mineral products.\n\nRead the intended method closely. A product meant for dissolving should not be scattered into a small houseplant pot as if it were a coated feed. Similar packaging or the word “granular” does not make application methods interchangeable.'),
s('Choose the routine you can follow accurately','For a few plants, liquid feed may be the simplest way to stay responsive. For an established collection, a suitable controlled-release product can reduce repetitive work. In either case, account for fertilizer already included in potting mix.\n\nA useful comparison includes the actual dose, frequency, intended plants, and your ability to pause or adjust. Record these in PlantPal and schedule reminders to review the routine. The goal is steady, appropriate nutrition—not the largest possible number of feeding events.')
],['fertilizing-houseplants','npk-fertilizer-numbers','common-houseplant-fertilizers']),
article('yellow-leaves-houseplants','Why are my houseplant leaves turning yellow?','troubleshooting','Work through yellow leaves using leaf age, moisture, light, pests, and recent changes before choosing a treatment.','One older yellow leaf and many rapidly yellowing leaves are different situations. Look for a pattern before changing care.',[
s('Notice which leaves are changing','Start with the oldest and newest growth. A single old leaf gradually fading while the plant produces healthy growth can be ordinary turnover. Several leaves changing quickly, yellow patches, or yellowing new growth deserve a closer inspection.\n\nPhotograph the whole plant and a close-up so you can compare later. Note whether damage is concentrated on the sunny side, lower leaves, or one stem. A record helps you tell ongoing decline from damage that happened before you corrected the conditions.'),
s('Check moisture and roots first','Both prolonged wetness and severe drying can lead to yellow foliage. Feel the mix below the surface, lift the container, and check for trapped water. A plant with persistently wet mix should not receive extra water or fertilizer just because its leaves look pale.\n\nIf yellowing continues alongside wet mix, soft stems, or a sour smell, inspect roots carefully. Healthy roots vary in color by species, so judge firmness and integrity as well as appearance. Roots that collapse or shed their outer tissue suggest damage.'),
s('Look at light, temperature, and pests','Has the plant moved? Have curtains closed off its daylight? Did heating or air conditioning begin recently? A change in environment can explain symptoms better than an assumed deficiency. Inspect underneath leaves and around leaf joints for insects, webbing, or sticky residue.\n\nDo not diagnose a specific nutrient deficiency from a photograph alone. Similar patterns can result from root problems, pH, or environmental stress. If a valuable plant keeps declining despite basic corrections, seek help from a local horticultural service with detailed history and clear photos.'),
s('Change care with a clear reason','Choose the most likely cause supported by your observations and correct it. Remove fully dead leaves with clean tools if desired, but retain functional tissue where practical. Avoid adding several treatments at once, which makes the next result difficult to interpret.\n\nWatch for the yellowing to stop spreading and for new leaves to develop normally. Existing yellow leaves often do not recover their original color. PlantPal can help you keep the care history together so you can recognize the direction of change.')
],['overwatering-vs-underwatering','root-rot-houseplants','fertilizing-houseplants'],[{title:'RHS: How to help a poorly houseplant',url:'https://www.rhs.org.uk/plants/types/houseplants/how-to-help-a-poorly-houseplant'}]),
article('root-rot-houseplants','Root rot in houseplants: signs, first steps, and prevention','troubleshooting','Learn how to inspect unhealthy roots, reduce prolonged wetness, and give a struggling houseplant a better chance of recovery.','Declining leaves plus persistently wet mix call for a root check. Recovery depends on how much healthy root and stem tissue remains.',[
s('Recognize when to inspect the roots','Wilting, yellowing, or leaf drop despite damp mix can indicate damaged roots, though none proves a diagnosis by itself. Check for blocked drainage and water trapped inside decorative pots. If symptoms continue, gently remove the plant from its container and inspect the root ball.\n\nLook for roots that are soft, collapse when touched, or lose their outer tissue. A musty or sour smell can add context. Root color alone is unreliable: healthy roots are not always white, and some mixes stain them.'),
s('Remove the conditions that keep roots failing','Use clean tools to remove clearly dead, mushy roots while preserving firm tissue. Discard compromised old medium rather than transferring it to another plant. Clean a reused container appropriately before adding fresh, suitable potting mix.\n\nChoose a pot that fits the remaining root system. A plant that has lost many roots may need a smaller container, not a larger one. Give excess water a clear exit. Do not create a gravel layer as a substitute for drainage holes and a suitable medium.'),
s('Be cautious with recovery promises','A plant with extensive stem or crown damage may not recover. For species that propagate readily, a healthy cutting can sometimes preserve the plant while the original root system is failing. Take only sound tissue and follow a species-appropriate method.\n\nAvoid pouring household chemicals into the pot or mixing treatments based on generic online recipes. Root problems have different causes, and a product intended for one pathogen or crop may not be appropriate indoors. Persistent or valuable-plant cases may need local expert diagnosis.'),
s('Rebuild a slower, more observant routine','Place the plant in suitable light without sudden harsh exposure. Check moisture carefully while the reduced root system recovers; it may use water more slowly. Pause fertilizer until healthy growth and root function are re-established.\n\nPrevent recurrence by reviewing the whole setup: light, pot size, medium, drainage, and the interval between waterings. In PlantPal, set a reminder to check rather than automatically water. A healthy cycle of moisture and air around the roots matters more than a rigid schedule.')
],['overwatering-vs-underwatering','repotting-houseplants','potting-mix-vs-garden-soil']),
article('brown-leaf-tips','Brown leaf tips: what to check before reaching for the scissors','troubleshooting','Explore brown tips on indoor plants, from inconsistent moisture and mineral buildup to dry air and damaged roots.','Brown tissue will not turn green again. The useful goal is healthy new growth and stopping the damage from spreading.',[
s('Look for a pattern in the damage','Dry tips on older leaves can accumulate over time, while rapid browning across the plant suggests a more recent stress. Note whether edges are crisp, patches are soft, or damage faces the window. Each pattern provides a clue, but several causes can overlap.\n\nTake a photo before trimming. That gives you a reference for whether the damage continues. Do not assume every brown edge means low humidity: roots that are too wet or too dry can both leave foliage unable to maintain normal water balance.'),
s('Review watering and dissolved minerals','Check the mix below the surface and inspect the pot for trapped water. Repeated severe drying can damage tips, but so can unhealthy roots in persistently wet medium. Review how you water, not only how often.\n\nWhite crust on the pot or mix may indicate mineral deposits from water, fertilizer, or both. Check whether you have been combining feeds or using more than the label directs. If buildup is suspected, seek guidance appropriate to the plant and medium; flushing a waterlogged, root-damaged plant can worsen its condition.'),
s('Measure the environment instead of guessing','Dry heated air, a nearby vent, hot glass, and cold drafts can stress foliage. A hygrometer gives a more useful humidity picture than assuming a room is humid because it contains plants. Misting briefly wets leaves but does not reliably maintain the humidity of an entire room.\n\nChoose plants that fit the environment you can sustain. If using a humidifier, keep it clean and avoid persistent condensation or wet foliage. Air movement and room hygiene still matter.'),
s('Trim only for appearance, then monitor','You may trim completely brown tips with clean scissors, following the leaf shape and avoiding healthy tissue. This tidies the plant but does not treat the underlying cause. It is also fine to leave cosmetic damage while you investigate.\n\nKeep care stable after making a reasoned correction. Check new leaves and whether the brown margin advances. Track the change in PlantPal so you can distinguish an old scar from a continuing problem.')
],['how-to-water-houseplants','fertilizer-burn-houseplants','houseplant-humidity']),
article('fungus-gnats-houseplants','Fungus gnats in houseplants: break the damp-soil cycle','troubleshooting','Understand fungus gnat adults and larvae, inspect potting mix, and combine moisture management with suitable controls.','Flying adults are only part of the problem. Focus on the moist growing medium where the immature stages develop.',[
s('Make sure the insects match the problem','Small dark flies hovering near potting mix may be fungus gnats, but insects around drains or fruit can be something else. Observe where they appear and whether activity increases when you disturb a pot. Yellow sticky cards near the medium can help monitor flying adults.\n\nSticky cards alone do not treat larvae in the root zone. Use them as a way to compare activity over time and identify which pots need attention. Keep adhesive traps out of reach of children, pets, and unintended wildlife.'),
s('Reduce unnecessary moisture','Check whether the mix stays continuously damp because of frequent watering, low light, or a large pot. Where the species tolerates it, allow the upper medium to dry appropriately between waterings. Empty saucers and remove decaying fallen leaves from the pot.\n\nDo not force a moisture-loving plant into severe drought just to chase insects. Correct the growing setup and use a suitable targeted control if needed. Bottom watering is not a guaranteed cure because moisture can still remain available in the medium.'),
s('Choose controls labeled for the setting','Biological options can include products based on Bacillus thuringiensis israelensis or appropriate beneficial nematodes where available and labeled for the intended use. Their preparation, storage, and repeat timing are product-specific. Read the actual instructions rather than improvising a dose.\n\nAvoid routine household mixtures or sprays aimed only at the flying adults. If you are unsure of the insect, get an identification before treating. In a larger collection, monitor neighboring pots so you are not repeatedly treating one while another remains a source.'),
s('Follow the trend over several checks','Adults may continue appearing while existing immature stages develop. A useful record includes trap counts or photos, watering changes, and treatment dates. A reduction over time tells you more than whether you saw one fly today.\n\nInspect new plants and stored potting supplies before bringing them into the collection. Store mixes as directed and avoid leaving open, wet material around growing areas. A consistent moisture-checking habit helps plants as well as pest management.')
],['how-to-water-houseplants','quarantine-new-houseplants','potting-mix-vs-garden-soil']),
article('spider-mites-houseplants','Spider mites on houseplants: spotting early signs','troubleshooting','Learn to inspect stippled leaves and fine webbing, isolate affected plants, and build a repeatable spider mite response.','Inspect leaf undersides and new growth. Early isolation and follow-up checks matter as much as the first treatment.',[
s('Look beyond obvious webbing','Fine pale speckling on leaves can appear before a heavy infestation produces noticeable webbing. Examine undersides, leaf joints, and tender growth with magnification if possible. Dust, old damage, and other pests can look similar from a distance.\n\nCheck nearby plants, especially those with touching foliage. Take clear close-up photos and record which plants show symptoms. If you cannot identify the pest, seek help before applying a broad treatment that may miss the actual cause.'),
s('Separate and clean carefully','Move an affected plant away from the collection when practical. Support delicate leaves and rinse suitable foliage with water, paying attention to undersides. Protect the pot from becoming unnecessarily soaked, and avoid an abrupt move into harsh sun afterward.\n\nRemove heavily damaged dead material when appropriate and clean the growing area. Washing can reduce the population but may not reach every life stage. Do not assume one rinse ends the problem.'),
s('Use an appropriate labeled treatment','If treatment is needed, choose a product labeled for mites, the plant type, and indoor use in your region. Insecticidal soaps or horticultural oils are options for some situations, but plant sensitivity, coverage, temperature, and repeat intervals matter. Patch-test when the label advises it.\n\nHousehold dish detergent is not interchangeable with a formulated insecticidal soap. Avoid improvised mixtures and do not combine pesticides. Follow restrictions around people and pets and allow treated foliage to dry as directed.'),
s('Make follow-up part of the treatment','Repeat inspection on the label’s schedule and continue monitoring adjacent plants. New damage, live mites, and expanding webbing are more useful signs than old stippling, which remains after control.\n\nReview plant stress and the growing environment without assuming humidity alone will eliminate mites. Keep notes on dates and products so you can judge whether the response is working and avoid applying too frequently.')
],['quarantine-new-houseplants','brown-leaf-tips','houseplant-humidity']),
article('fertilizer-burn-houseplants','Fertilizer burn in houseplants: prevention and recovery checks','troubleshooting','Recognize possible overfeeding, review overlapping fertilizers, and take measured steps when excess salts may be damaging a plant.','Before adding any treatment, stop and count every nutrient source already in the pot.',[
s('Connect symptoms with recent care','Brown tips, damaged margins, wilting, or slowed growth after feeding can suggest excess salts, but these symptoms are not unique to fertilizer. Review the exact product, amount, dilution, and timing. Include granules and fertilizer already in the potting mix.\n\nA dose meant for a larger volume of water can become much stronger if mixed in a small can. A ready-to-use bottle and a concentrate can look similar. Keep the label and measuring tool together to reduce these mistakes.'),
s('Pause additional feeding','Do not add a different fertilizer to correct damage that may already be caused by excess nutrients. If visible surface granules were recently overapplied and can be removed without damaging roots, carefully remove them. Granules mixed throughout the root ball are a different situation.\n\nCheck roots and moisture. An already saturated plant with poor drainage should not be repeatedly flooded in an attempt to wash everything out. The recovery method needs to fit both the suspected salt problem and the current root condition.'),
s('Use drainage and repotting thoughtfully','For a plant with functioning drainage and otherwise healthy roots, leaching excess soluble salts with suitable water may help. Species, medium, and water quality affect the approach. If the root system is badly compromised or the mix is unsuitable, careful repotting may be more appropriate.\n\nAvoid adding household substances to “neutralize” fertilizer. They can change pH or introduce more salts. When the dose was extreme or the plant is valuable, ask a local horticultural service for advice with the product label available.'),
s('Restart only when growth supports it','Damaged edges will remain even if the plant recovers. Watch for stable foliage and healthy new growth before resuming a measured feeding routine. Start with a single appropriate product and account for any feed in new potting mix.\n\nRecord actual applications in PlantPal, not just planned ones. A reminder should prompt you to check the plant and label. It should not override evidence that the plant needs a pause.')
],['fertilizing-houseplants','npk-fertilizer-numbers','root-rot-houseplants']),
article('bottom-watering-houseplants','Bottom watering houseplants: when it helps and when it does not','plant-care','Learn how bottom watering works, how to check the root ball, and why it does not replace good drainage or occasional top watering.','Bottom watering is a technique for wetting the mix. It is not a cure for overwatering or a reason to leave roots standing in water.',[
s('Understand the path water takes','When a nursery pot sits in a shallow reservoir, water enters through drainage openings and moves into the medium. How evenly it rises depends on the ingredients, how dry they are, and whether they contact the water. A very coarse mix may behave differently from a fine, fibrous one.\n\nUse a separate clean container for soaking. Do not assume that water disappearing from the reservoir means every part of a large root ball is equally moist. Check the mix and pot weight before deciding the process is complete.'),
s('Use a monitored soak','Place a pot with open drainage holes in a shallow amount of water, keeping foliage and the plant’s crown above it. Check periodically and remove the pot when the root ball has absorbed enough moisture for that plant. Allow it to drain fully before returning it to its outer container.\n\nThere is no universal soak duration for all pots. Size, dryness, and medium matter. Do not leave a pot unattended for hours or turn a decorative cover pot into a permanent reservoir unless the plant is in a system designed for that purpose.'),
s('Know its useful limits','This method can help rehydrate a dry root ball or avoid wetting sensitive foliage. It may also reduce disturbance to a fragile soil surface. It will not fix a pot that is too large, a poorly aerated mix, or a plant receiving too little light.\n\nRegular bottom watering can leave dissolved salts behind as water evaporates or is used. Where appropriate for the species and root condition, occasional thorough top watering with drainage helps move accumulated salts out. Consider your water quality and fertilizer routine together.'),
s('Avoid sharing problems between pots','Use clean water and containers, particularly if any plants show root disease or pests. Moving several plants through the same water can transfer unwanted organisms. Check each plant separately instead of soaking the whole collection by habit.\n\nAfter changing technique, continue observing how long each pot takes to dry. PlantPal reminders can keep checks consistent, but the plant and medium still determine when the next watering is needed.')
],['how-to-water-houseplants','overwatering-vs-underwatering','fertilizer-burn-houseplants']),
article('using-a-plant-light-meter','How to use a plant light meter without overreading the numbers','plant-care','Take repeatable lux readings at leaf height and use them to compare plant locations while understanding phone sensor limitations.','Use light readings to compare places and times. A single lux measurement cannot describe a plant’s entire day.',[
s('Measure where the plant actually grows','Hold the meter or phone at the level of the leaves and follow the device’s instructions for sensor direction. Avoid shading the sensor with your hand or body. Measure in the same orientation when comparing two shelves or window positions.\n\nA reading beside the glass is not a reading at the back of a bookcase. Small changes in position can have large effects. Write down distance from the window and any curtains or nearby foliage so the comparison can be repeated.'),
s('Build a daily picture','Take measurements at several times on more than one day. A short sunny interval can produce a high number while the rest of the day stays dim. Cloud cover and seasonal day length also change the total light available.\n\nA practical first exercise is to compare three candidate locations at similar times. This tells you which is brighter without pretending to know an exact light prescription for every species. Combine those observations with the plant’s growth and established care needs.'),
s('Understand lux and sensor limitations','Lux weights light according to human visual sensitivity. Plant lighting is often discussed using photosynthetic photon measurements instead. Converting lux to a plant-specific photon value depends on the light spectrum, so one universal conversion factor is misleading.\n\nPhone hardware and measurement methods vary. A built-in sensor or camera-based estimate can provide useful relative guidance, but it is not automatically a calibrated horticultural instrument. PlantPal’s light meter is best paired with consistent technique and an understanding of those limits.'),
s('Use results to make gradual changes','If a location is consistently much darker than another, consider moving a light-hungry plant closer to the brighter area. Acclimate it gradually if direct sun exposure increases. Watch new leaves, spacing between leaves, and signs of bleaching or scorch.\n\nRevisit measurements when seasons change or a plant grows into the light of another. Save the plant’s zone and observations in PlantPal. The number is useful because it supports a better care decision, not because it replaces observation.')
],['bright-indirect-light','low-light-houseplants','houseplant-care-for-beginners']),
article('houseplant-humidity','Humidity for houseplants: useful changes beyond misting','plant-care','Understand indoor humidity, measure your growing area, and choose realistic ways to support humidity-sensitive houseplants.','Measure humidity near the foliage and choose plants that fit the conditions you can maintain consistently.',[
s('Start with a measurement','A room’s humidity changes with temperature, ventilation, heating, and the weather. Place a hygrometer near the plants without letting it touch wet foliage or sit directly in a humidifier plume. Read it at different times to understand the range rather than one isolated value.\n\nLeaf damage is not a humidity meter. Brown tips can also result from uneven moisture, root damage, or dissolved minerals. Check the root zone and care history before buying equipment to solve an assumed air problem.'),
s('Understand what misting can and cannot do','A spray bottle temporarily wets leaves and nearby air. In a normal ventilated room, that effect is short-lived and does not create sustained tropical conditions. Some plants also dislike repeatedly wet foliage, especially when air movement is poor.\n\nMisting can be a pleasant ritual, but it should not stand in for a suitable growing environment. Likewise, a small tray of wet pebbles may have limited influence beyond its immediate surface. Keep pots above standing water rather than immersing their drainage holes.'),
s('Make manageable environmental changes','Moving a sensitive plant away from a heating vent may help more than adding occasional mist. Grouping plants can influence the immediate microclimate, but keep enough space for inspection and air movement. A naturally brighter bathroom may suit some plants if its light and temperature are also appropriate.\n\nA humidifier can raise room humidity more consistently, but it needs regular cleaning and sensible placement. Follow the manufacturer’s instructions and avoid condensation on windows, walls, or leaves. Persistent dampness creates a different set of problems.'),
s('Match the collection to your home','If your living space stays dry, consider plants with thicker leaves or less demanding humidity needs rather than fighting the room all year. Reserve more sensitive specimens for a place where you can maintain their conditions.\n\nRecord both humidity and symptoms before making changes. Evaluate healthy new growth over time. PlantPal can help you organize plants by zone so you remember which room has which growing conditions.')
],['brown-leaf-tips','spider-mites-houseplants','organize-plants-by-zone']),
article('low-light-houseplants','Low-light houseplants: what tolerance really means','plant-guides','Choose houseplants for dimmer rooms while understanding the difference between surviving low light and growing well.','Low-light tolerant does not mean no-light tolerant. Slower growth usually means slower water use, too.',[
s('Define the location before choosing','A place receiving daylight for much of the day is different from a windowless corner. Human eyes adapt to dim rooms, so a comfortable reading environment does not necessarily provide ample plant light. Look from the plant’s position toward the window and note obstructions.\n\nA simple light comparison can help you choose between locations. Measure at leaf height and repeat at different times. If usable natural light is very limited, a properly selected grow light may be more realistic than expecting a plant to adapt indefinitely.'),
s('Consider tolerant foliage plants','ZZ plants, snake plants, and some green pothos are often chosen for their tolerance of less intense light. Tolerance is not the same as preference. In a brighter suitable location they may grow more strongly, while a dim position can mean little new growth.\n\nVariegated cultivars may respond differently from all-green forms. Choose based on the particular plant and its condition, not only a common name. Keep expectations realistic and avoid buying a specimen that is already stressed or pest-infested.'),
s('Adjust watering to reduced demand','Lower light commonly means the pot dries more slowly. A plant kept on the watering routine from a brighter location may remain wet for too long after a move. Check the medium and container weight rather than treating low-light tolerance as permission to ignore the roots.\n\nAvoid placing a small plant in a very large pot to “help it grow” in a dark room. That adds damp medium without adding useful light. Keep the root environment manageable and feed according to actual growth and the product label.'),
s('Watch for the difference between stable and declining','New growth that is stretched, sparse, or much smaller can indicate inadequate light, though other causes are possible. Losing many leaves is not an unavoidable feature of a low-light plant. Check the full environment and make a gradual move if needed.\n\nRotate plants only thoughtfully: frequent abrupt changes between a dark corner and strong sun can add stress. A stable suitable location is easier to manage. Use PlantPal zones and light readings to find the best compromise in your home.')
],['zz-plant-care','snake-plant-care','pothos-care','bright-indirect-light']),
article('vacation-plant-care','Vacation plant care: a simple plan for your plant sitter','tips','Prepare indoor plants for time away with moisture checks, clear sitter instructions, and a practical handover plan.','Give your sitter observable instructions for each plant, not a blanket request to water everything.',[
s('Prepare around the length of your trip','Start planning before the day you leave. A short absence may only require checking plants that are due for water. A longer trip may call for a sitter, a tested watering system, or a temporary grouping in a suitable location.\n\nDo not soak every plant heavily as a precaution. A drought-tolerant plant that is still wet can be harmed by another watering. Likewise, moving every plant into darkness may reduce water use but deprive them of needed light.'),
s('Write instructions a visitor can follow','Label each plant or group clearly and explain what a dry-enough pot feels like. Point out which plants should be left alone unless a specific condition is met. Demonstrate how to remove a nursery pot from a decorative container and empty runoff.\n\nKeep the instructions short and visible. A sitter should not have to infer whether “a little water” means a spoonful or a full watering. If an amount is part of your plan, test it in that exact pot and describe drainage as well.', ['Show where the watering supplies are.','Identify plants that are not due for water.','Explain how to check moisture and empty saucers.','Leave a way to ask about an uncertain plant.']),
s('Test any equipment in advance','Wicks, reservoirs, and self-watering devices behave differently depending on the potting mix, container, and height of the water source. A last-minute setup can deliver too much or too little. Trial it while you are home and check the entire root ball.\n\nKeep electrical devices away from water and follow their instructions. Do not introduce new fertilizer or major repotting just before leaving unless a plant has a problem that cannot wait.'),
s('Use Plant Sitter for a clearer handover','PlantPal’s Plant Sitter feature is designed to help someone else keep care on track while you are away. Use it alongside practical location notes and a quick demonstration. The person caring for the plants still needs to check their current condition.\n\nWhen you return, inspect the plants before resuming your usual routine. Your sitter may have watered recently, and room conditions may have changed. Update your care records so the next reminder starts from what actually happened.')
],['how-to-water-houseplants','organize-plants-by-zone','self-watering-pots']),
article('quarantine-new-houseplants','Bringing home a new houseplant: an inspection and settling-in guide','tips','Inspect new plants for pests, keep them apart from your collection, and help them adjust without unnecessary care changes.','A separate observation period helps you notice hidden problems before a new arrival joins the rest of your plants.',[
s('Inspect before the plant comes home','Look at both sides of leaves, stem joints, and the surface of the mix. Check for insects, webbing, sticky residue, unusual spots, or collapsed tissue. A plant can look attractive from the front while hiding a problem underneath.\n\nInspect the container as well. Water trapped around a nursery pot and a soggy root ball can be warning signs. If a plant already has a serious problem, decide whether you actually want a recovery project before bringing it into a healthy collection.'),
s('Create a separate observation space','Keep the new plant away from direct foliage contact with established plants, ideally in a separate suitable area. Separation is useful only if the location still provides adequate light and temperature. Use separate tools or clean them between plants.\n\nInspect repeatedly over the following weeks rather than relying on one glance. The exact observation period depends on the pest risk and circumstances; some issues take time to become visible. Record findings so subtle changes do not get overlooked.'),
s('Avoid changing everything at once','Moving from a nursery to a home already changes light, humidity, and temperature. Unless drainage or root health needs urgent attention, first learn how the existing pot dries. Unnecessary repotting, heavy pruning, and feeding can make it harder to understand a stressed plant’s response.\n\nIf you discover a problem, identify it before treating. Blanket pesticide use is not a substitute for inspection. Follow appropriate labels and keep any affected plant separate while monitoring the response.'),
s('Introduce it when it is stable','When repeated checks show healthy growth and no developing pest issue, choose its longer-term position based on light and space. Keep enough room between leaves to inspect and clean. Continue periodic checks because no observation period guarantees permanent freedom from pests.\n\nAdd the plant to PlantPal with its identification, location, and care notes. Recording the arrival date and initial condition gives you a useful baseline for the months ahead.')
],['spider-mites-houseplants','fungus-gnats-houseplants','houseplant-care-for-beginners']),
article('organize-plants-by-zone','Organize houseplants by zone for an easier care routine','tips','Group indoor plants by location and growing conditions to make watering checks, light decisions, and plant-sitter handovers easier.','A zone should describe a real growing environment, not imply that every plant in that room needs identical care.',[
s('Name the places you actually check','Start with familiar locations such as Living Room, Bedroom, Office, or Balcony. If one room has very different light conditions, divide it into meaningful subareas such as East Window and Back Shelf. Names that match the room are easier for you and a sitter to follow.\n\nKeep the system simple enough to maintain. A dozen vague categories can be harder to use than four clear zones. The purpose is to find plants and notice their conditions, not create administrative work.'),
s('Record what makes each zone different','Note the main window direction, direct-sun periods, temperature changes, and nearby vents. A balcony may be exposed to wind or rain; an office may have heating switched off over weekends. These details influence the care routine more than the room name itself.\n\nWithin a zone, compare pot sizes and plant types. A small fern and a large succulent sharing a shelf should not share an automatic watering rule. Use the zone as a route for inspection while retaining individual care needs.'),
s('Build a quick inspection circuit','Check one zone at a time and gather supplies before starting. Look for dry-enough pots, fallen leaves, pest signs, and water in saucers. Leave plants that do not need intervention alone. This is often faster and more reliable than reacting to whichever leaf catches your eye.\n\nIf a plant moves, update its location promptly. Otherwise care reminders and sitter instructions can describe the wrong environment. A move is also a reason to reassess how quickly the pot dries.'),
s('Use zones to make handovers clearer','PlantPal supports organizing plants into custom zones. Combine this with identifiable plant names and practical notes so another person can match a care task to the right pot. A room photo can be useful in your own handover materials when several plants look similar.\n\nReview the zones seasonally. As plants grow or furniture moves, light and access change. An organization system works best when it reflects the collection you have now, not the one you arranged a year ago.')
],['vacation-plant-care','using-a-plant-light-meter','houseplant-care-for-beginners']),
article('terracotta-vs-plastic-pots','Terracotta vs. plastic pots: choose for your watering habits','soil-fertilizer','Compare terracotta and plastic plant pots for moisture, weight, stability, and everyday indoor plant care.','Pot material changes the drying pattern. Choose it together with the plant, mix, light, and your checking routine.',[
s('Why the same plant dries differently in another pot','Unglazed terracotta is porous, so moisture can leave through the walls as well as the surface and drainage openings. Plastic retains moisture through its walls. Glazed ceramic behaves differently from unglazed clay, so appearance alone does not tell you how a container performs.\n\nBoth materials can work well. The question is whether the resulting drying pattern fits the plant and your room. Reusing the same watering interval after changing container material can lead to surprises.'),
s('When terracotta is a useful choice','A heavier clay pot can stabilize a top-heavy plant. Faster drying can suit plants that prefer a more complete dry-down, especially if your room and mix otherwise hold moisture for a long time. The weight also gives a different feel when you lift the container to judge moisture.\n\nThe tradeoffs include more weight to move, possible salt staining, and potentially faster drying than a moisture-loving plant can tolerate between checks. Clay does not rescue a pot without a drainage opening or a chronically oversized container.'),
s('When plastic makes care easier','Plastic nursery pots are light, affordable, and easy to lift from decorative covers. Their slower moisture loss can help when plants dry too quickly or when a large pot would otherwise be difficult to move. Many also make it easier to see or reach drainage holes.\n\nUse a stable cover pot if needed, but keep enough space to remove the nursery pot and inspect for trapped water. Avoid letting the outer container hide standing runoff. Lightweight pots may also need support for tall plants.'),
s('Change one variable at a time','When repotting, note the old and new materials, size, and mix. If all three change, you may need several checks to learn the new behavior. Water according to moisture and the plant’s needs rather than the label “terracotta” or “plastic.”\n\nKeep matching care notes in PlantPal. If one setup consistently causes problems, use that history to make the next container choice instead of buying only for appearance.')
],['repotting-houseplants','potting-mix-vs-garden-soil','how-to-water-houseplants']),
article('aroid-potting-mix','Aroid potting mix: building structure without a magic recipe','soil-fertilizer','Understand bark, mineral amendments, and moisture-holding ingredients in potting mixes for monstera, pothos, and other aroids.','A useful aroid mix holds enough moisture for roots while retaining air. The proportions depend on your plant and growing conditions.',[
s('Why aroids are often grown in chunky mixes','Many popular aroids are grown in blends that include coarse particles alongside moisture-holding material. The goal is a root environment that does not compact easily or remain saturated for too long. But the aroid family contains plants with different habits, so one recipe cannot fit every member.\n\nConsider the plant, container size, indoor temperature, and available light. A very coarse blend in a small pot beside a bright window may dry faster than you can manage. The same mix in a large, cool container may behave differently.'),
s('Give each ingredient a clear job','A suitable potting-mix base can hold moisture and supply a consistent starting structure. Horticultural bark adds coarse organic particles. Perlite or pumice can adjust weight and pore space. The properties depend on grade and particle size, not only the ingredient name.\n\nAvoid adding ingredients because a long recipe sounds expert. Charcoal, castings, and specialty products are not mandatory for every plant. Each addition should address a need you understand and should not accidentally duplicate a nutrient source.'),
s('Prepare and observe a small batch','Use clean horticultural materials and follow preparation instructions, especially for compressed coir or dusty amendments. Mix evenly so the pot does not contain separate wet and dry layers. Keep a written record of proportions by volume if you want to reproduce the result.\n\nAfter repotting a plant that actually needs it, water carefully and observe the full drying cycle. Check the center of the root ball as well as the surrounding fresh mix. A coarse outer blend can dry while a dense old core remains wet.'),
s('Adjust the setup before chasing ingredients','A pot much larger than the root ball or a dark location may be the main reason moisture lingers. Changing the mix repeatedly without correcting those conditions can stress roots without solving the problem.\n\nUse the simplest blend that works reliably in your home. Record the mix and repotting date in PlantPal, then judge the result through root health and new growth. There is no prize for using the most ingredients.')
],['monstera-deliciosa-care','perlite-vs-pumice','potting-mix-vs-garden-soil']),
article('self-watering-pots','Self-watering pots: how to use a reservoir thoughtfully','tips','Learn how self-watering planters work, which conditions affect their success, and how to test them before relying on a reservoir.','A reservoir changes how water reaches the roots. It does not make every plant or potting mix suitable for constant moisture.',[
s('Understand your planter’s design','Some planters use a wick; others draw moisture through a column of growing medium. The reservoir, air space, overflow, and indicator all influence performance. Read the instructions for the actual planter rather than treating every “self-watering” container as the same system.\n\nCheck that the overflow works and that roots or debris have not blocked important openings. A decorative pot filled with water is not automatically a self-watering system.'),
s('Choose a plant and mix that fit','Plants that prefer relatively steady moisture may adapt more readily than those needing a pronounced dry period. Even then, root oxygen and the medium’s wicking behavior matter. A blend that works in an ordinary nursery pot may not behave the same over a reservoir.\n\nFollow the planter’s guidance about medium and establishment. Newly repotted roots may not yet reach the zone supplied by the reservoir, so an indicator showing water is not proof that the root ball is moist.'),
s('Test while you are at home','Monitor moisture at different depths, plant condition, and how quickly the reservoir empties. Check for waterlogging as well as dryness. Light, temperature, and plant size affect demand, so do not assume the advertised refill interval applies to your room.\n\nIf using the planter for vacation care, run it through a full cycle before leaving. Ask a sitter to check the plant as well as the gauge. A stuck indicator or poor wick contact can give false reassurance.'),
s('Keep maintenance in the routine','Clean reservoirs and check for accumulated deposits according to the manufacturer’s instructions. Use fertilizer only in a way compatible with the system and product label. Do not add a concentrated dose to standing water on a guess.\n\nTrack refills and observations in your care notes. A well-matched reservoir can reduce repetitive tasks, but periodic root, foliage, and moisture checks remain part of good plant care.')
],['vacation-plant-care','how-to-water-houseplants','potting-mix-vs-garden-soil']),
];
export function readingMinutes(a:Pick<Article,'sections'>){return Math.max(2,Math.ceil(a.sections.flatMap(s=>[s.heading,...s.paragraphs,...(s.bullets||[])]).join(' ').split(/\s+/).length/200))}
