import {section as s,type Article} from './content';
const make=(slug:string,title:string,category:Article['category'],description:string,takeaway:string,sections:Article['sections'],related:string[],sources:Article['sources']=[]):Article=>({slug,title,category,description,takeaway,sections,related,sources,author:'PlantPal',status:'published',publishedAt:'2026-09-22T20:00:00.000Z',updatedAt:'2026-09-22T20:00:00.000Z'});
const mg='https://scottsmiraclegro.com/en-us/brands/miracle-gro/products/plant-food-and-care/3000552.html';
const ep='https://www.espoma.com/product/indoor/';
const mix='https://scottsmiraclegro.com/en-us/brands/miracle-gro/products/potting-mix/miracle-gro-indoor-potting-mix/72776431.html';
export const extraArticles:Article[]=[
make('common-houseplant-fertilizers','Common houseplant fertilizers: compare the format before the brand','soil-fertilizer','Compare familiar indoor plant foods, concentrated liquids, coated granules, and organic options without treating one product as universally best.','Compare intended use, working dilution, and release method. Brand names alone do not tell you how to feed a plant.',[
s('Begin with the job you need the product to do','For an indoor collection, a useful fertilizer is one that matches the plant and is easy to measure correctly. Consider whether you want to mix feed at selected waterings or apply a product intended to release nutrients over a longer period. Also check whether the potting mix already contains feed.\n\nThis is a format comparison, not a hands-on product test or a ranking. Product names and formulations vary by country and change over time. The label on the product you buy is the authority for its application.'),
s('Two familiar liquid options','The US Miracle-Gro Indoor Plant Food page describes a pump-dispensed liquid with a 1-1-1 analysis and offers direct-to-soil or diluted application. Espoma Indoor! is a concentrated liquid that the manufacturer describes as an organic option and instructs users to dilute before drenching the mix.\n\nThe key practical distinction is how each product is measured and applied. Do not transfer a pump count, cap measure, or interval from one to the other. Read our individual product notes and then confirm the current local label.'),
s('What coated granules change','Osmocote is a familiar example of a brand associated with controlled-release plant foods. Products in this category use formulations and coatings designed to release nutrients over time. Choose an exact product labeled for your plants and setting, since the brand includes different formulations.\n\nA longer application interval can simplify routine care, but it does not remove the need to record when and how much was applied. Avoid adding liquid feed on top of an existing controlled-release program without accounting for the combined nutrient supply.'),
s('Compare the real cost and effort','A small concentrated bottle may produce many applications; a larger ready-to-use container may be simpler to measure. Compare the prepared quantity and labeled dose, not only bottle size. Consider storage, spills, and whether you can accurately measure the smallest amount needed.\n\nNo fertilizer compensates for weak light or damaged roots. Choose one appropriate approach, keep the label, and record applications in PlantPal. Change products for a clear reason rather than collecting multiple feeds that overlap.')
],['miracle-gro-indoor-plant-food','espoma-indoor-plant-food','liquid-vs-slow-release-fertilizer'],[{title:'Miracle-Gro: Indoor Plant Food',url:mg},{title:'Espoma: Indoor!',url:ep}]),
make('miracle-gro-indoor-plant-food','Miracle-Gro Indoor Plant Food: understanding the pump bottle','soil-fertilizer','A label-based look at the US Miracle-Gro Indoor Plant Food pump bottle, how it differs from other feeds, and what to check before use.','Confirm the exact bottle and local label. Miracle-Gro sells multiple plant foods with different strengths and directions.',[
s('Identify the exact product','The US manufacturer page reviewed for this guide lists Miracle-Gro Indoor Plant Food as a liquid with a 1-1-1 analysis. It describes both direct-to-soil application and a watering-can dilution. These details apply to that listed product, not every bottle carrying the Miracle-Gro name.\n\nCheck the product name, formulation, and instructions on your own container. Do not substitute the directions from a water-soluble powder, a general-purpose concentrate, or a regional version with different labeling.'),
s('Understand the convenience and the tradeoff','A pump dispenser can make small applications convenient because it reduces the need to pour a tiny quantity into a separate measuring cup. The amount delivered still depends on using the correct product and following its intended method.\n\nConvenience should not turn into automatic feeding. First check whether the plant is growing, whether its mix already supplies nutrients, and whether watering is due. A plant with a saturated root ball should not receive an extra drink simply because you planned a feeding day.'),
s('Keep the routine unambiguous','Choose the label-approved application method that fits your collection, then record it. Avoid alternating between direct application and dilution without keeping track of the total feed. Do not add a second fertilizer to compensate for a missed application.\n\nUse dedicated plant-care equipment and keep the bottle securely stored according to its instructions. If someone else cares for your plants, write down whether feeding should be skipped during your absence; a sitter usually benefits from fewer optional decisions.'),
s('Evaluate the plant, not a marketing promise','Observe new growth and the condition of roots and leaves over time. If the plant remains weak, investigate light, moisture, temperature, and pests instead of increasing the dose beyond the label.\n\nThis guide is based on manufacturer information and general care principles, not a product trial. Follow the current package directions for amounts, timing, and precautions. Save the product name with your PlantPal feeding reminders so you can check the right label each time.')
],['common-houseplant-fertilizers','npk-fertilizer-numbers','fertilizer-burn-houseplants'],[{title:'Manufacturer details and current label link',url:mg}]),
make('espoma-indoor-plant-food','Espoma Indoor! plant food: using a liquid concentrate thoughtfully','soil-fertilizer','Understand Espoma Indoor! as a liquid concentrate, how to plan applications, and why organic fertilizer still needs careful measuring.','Organic does not mean unlimited. Measure the concentrate, check the plant, and follow the current bottle instructions.',[
s('Know what kind of product you have','Espoma describes Indoor! as a liquid plant food for houseplants and an organic option. Its manufacturer directions call for shaking and diluting the concentrate in water before thoroughly wetting the mix. Confirm the instructions on the bottle sold in your region.\n\nA concentrate is not a ready-to-use solution. Do not pour an unmeasured amount onto the roots or borrow a cap measure from another fertilizer. Bottle sizes and dispensers can make casual measurements especially unreliable.'),
s('Fit feeding into the plant’s real needs','Before mixing, check whether watering is due and whether the plant is actively growing. The label provides product-specific guidance, but a wet, stressed, or poorly lit plant may need its growing conditions corrected before feeding.\n\nCheck the potting-mix bag for included fertilizer. Combining several nutrient sources without a plan can be excessive, even when one is marketed as natural or organic. Keep the routine simple enough that you know what went into each pot.'),
s('Prepare only what you can manage properly','Follow the label’s mixing and use instructions and use clean, dedicated equipment. Store the original bottle as directed rather than leaving it in heat or where it can be mistaken for a household product. Do not assume a homemade stored mixture behaves like the sealed concentrate.\n\nIf smell, storage, or measuring small quantities is inconvenient in your home, include those practical considerations when comparing formats. A product that you can use accurately and consistently is more useful than one selected only by a front-label claim.'),
s('Keep a record before judging the result','Record application dates and the exact product, then watch stable new growth. A change in light or watering can influence growth at the same time, so avoid attributing every new leaf to one feeding.\n\nThis is a label-based product overview, not a hands-on test or an endorsement that it suits every plant. Read the current manufacturer instructions and store feeding information with your PlantPal care notes so reminders lead to an informed decision.')
],['common-houseplant-fertilizers','fertilizing-houseplants','liquid-vs-slow-release-fertilizer'],[{title:'Espoma Indoor! manufacturer directions',url:ep}]),
make('miracle-gro-indoor-potting-mix','Miracle-Gro Indoor Potting Mix: what to check before repotting','soil-fertilizer','Read the ingredients and built-in feeding claims of Miracle-Gro Indoor Potting Mix and decide whether it fits your plant and home.','A pre-fertilized indoor mix changes both watering and feeding decisions. Check the bag before adding extra plant food.',[
s('Identify the mix, not just the brand','The US product page reviewed for Miracle-Gro Indoor Potting Mix describes a blend for indoor container plants that includes coconut coir and fertilizer. The brand also sells other mixes for different uses, so verify the exact bag and local formulation.\n\nThe reviewed page says the product contains no compost or bark and is designed to be less prone to gnats. That is a manufacturer claim about the formulation, not a guarantee that pests cannot appear in your home.'),
s('Treat the included fertilizer as part of the plan','The manufacturer describes feeding for up to six months for the reviewed product. Such a claim should be read alongside the actual label and your plant’s growing conditions, rather than treated as an exact calendar for every pot.\n\nRecord the repotting date and the presence of included feed. Do not automatically combine the fresh mix with granules and frequent liquid fertilizer. If growth or leaf color changes, investigate light, moisture, and roots before assuming more nutrients are needed.'),
s('Match the moisture behavior to the plant','A mix marketed for indoor plants is a starting point, not proof that every species needs the same root environment. A succulent, a fern, and a climbing aroid may require different drying patterns. Pot size and room conditions influence the result as much as the bag name.\n\nAfter repotting, check below the surface and learn how the new medium dries. Compare the center of the old root ball with the surrounding fresh mix. Avoid packing the medium tightly or burying the plant deeper than its appropriate level.'),
s('Use observation to decide whether it fits','Choose a pot with drainage, water according to the plant’s needs, and empty runoff. Monitor growth and moisture over several cycles rather than deciding from the feel of the dry bag.\n\nThis overview is based on the manufacturer’s description and general container-care principles; it is not a hands-on comparison. Check the current package instructions and record the mix in PlantPal so future watering and feeding decisions account for what is in the pot.')
],['potting-mix-vs-garden-soil','coco-coir-vs-peat','fungus-gnats-houseplants'],[{title:'Miracle-Gro Indoor Potting Mix manufacturer information',url:mix}]),
make('propagating-pothos','How to propagate pothos from a stem cutting','tips','Find the node, prepare a healthy pothos cutting, and move from rooting to a small pot with practical checks along the way.','A viable pothos cutting needs a healthy node. A leaf with only its stalk is not the same as a stem cutting.',[
s('Choose a healthy section of vine','Start with a parent plant that is not actively declining or carrying pests. Identify the nodes where leaves attach to the stem; these are the important growth points. Choose a manageable section with sound tissue rather than a long, stressed vine with many leaves to support.\n\nUse clean scissors or a blade. Cut so the cutting includes a node and some healthy stem. Remove a lower leaf if it would be submerged or buried, taking care not to damage the node itself.'),
s('Choose water or a suitable rooting medium','For water propagation, place the node in clean water while keeping leaves above the surface. Use a clean container and refresh the water when needed rather than allowing it to become stagnant. Give the cutting good indirect light without overheating it in direct sun.\n\nFor propagation in medium, use a small container and a suitable moist, airy mix. Keep it appropriately moist without constant saturation. Neither method benefits from strong fertilizer while the cutting has little or no working root system.'),
s('Look for progress rather than a fixed deadline','Rooting time varies with temperature, light, the cutting, and the parent plant. Check for firm tissue and developing roots. If part of the stem becomes mushy, remove compromised material with clean tools and reassess whether a healthy node remains.\n\nDo not repeatedly pull a medium-rooted cutting out to inspect it. Gentle signs of new growth and eventual resistance can provide clues, though neither should prompt rough testing.'),
s('Move into a modest pot and keep watching','When a water-rooted cutting has a useful developing root system, move it into an appropriately small pot with drainage and suitable mix. Set the node and roots carefully and keep moisture reasonably consistent during the transition without turning the pot soggy.\n\nA tiny cutting in a large container is harder to water well. Record the propagation and potting dates, then watch new growth. PlantPal can help keep the new plant’s care needs separate from those of the established parent.')
],['pothos-care','repotting-houseplants','how-to-water-houseplants']),
make('cleaning-houseplant-leaves','How to clean houseplant leaves gently','tips','Remove dust from indoor foliage, inspect for pests, and avoid household polishes that can cause more problems than they solve.','Support the leaf, use a gentle method suited to its surface, and turn cleaning into an inspection habit.',[
s('Choose the method for the leaf surface','Broad, smooth leaves can often be wiped gently with a soft damp cloth. Support the underside with your hand so the leaf does not bend sharply. Use clean water and rinse the cloth as it collects dust.\n\nHairy, delicate, or powdery-coated foliage needs a different approach. Wiping can damage surface hairs or remove a protective bloom. Use a soft brush where appropriate, or consult the care requirements for the particular plant before washing.'),
s('Avoid turning shine into the goal','A healthy leaf does not need to look polished. Household oils, mayonnaise, and improvised mixtures can leave residues and create problems. Use products on living foliage only when they are intended for that purpose and appropriate for the plant.\n\nPlain water is often enough for ordinary dust on smooth leaves. If you find sticky deposits, investigate their cause rather than simply hiding them. Some pests produce residues, and repeated stickiness deserves an inspection.'),
s('Protect the pot and tender growth','If rinsing a suitable plant in a shower or sink, use gentle water pressure and a comfortable temperature. Avoid saturating a pot that already needs to dry. Let foliage and the container drain before returning the plant to its place.\n\nDo not force open a new unfurling leaf or scrub damaged tissue. Keep the plant out of abrupt harsh sun after a major wash or move. Clean tools and cloths between plants when pests or disease are suspected.'),
s('Use the moment to notice changes','Look at undersides, joints, and the base of new growth while the plant is accessible. Check for webbing, scale-like bumps, or unusual speckling. A careful look can reveal a developing problem earlier than a quick glance across the room.\n\nThere is no universal cleaning interval: dust level, leaf type, and room conditions differ. Add an occasional inspection reminder to your routine and keep notes on anything that changes. The purpose is healthy foliage and better observation, not a showroom finish.')
],['rubber-plant-care','spider-mites-houseplants','quarantine-new-houseplants']),
];
