import {section as s,type Article} from './content';
const make=(slug:string,title:string,category:Article['category'],description:string,takeaway:string,sections:Article['sections'],related:string[],sources:Article['sources']=[]):Article=>({slug,title,category,description,takeaway,sections,related,sources,author:'PlantPal',status:'published',publishedAt:'2026-09-22T20:00:00.000Z',updatedAt:'2026-09-22T20:00:00.000Z'});
const mg='https://scottsmiraclegro.com/en-us/brands/miracle-gro/products/plant-food-and-care/3000552.html';
const ep='https://www.espoma.com/product/indoor/';
const mix='https://scottsmiraclegro.com/en-us/brands/miracle-gro/products/potting-mix/miracle-gro-indoor-potting-mix/72776431.html';
export const extraArticles:Article[]=[
make('common-houseplant-fertilizers','Common houseplant fertilizers compared: liquids, granules and organic feeds','soil-fertilizer','How liquid concentrates, ready-to-use pumps, controlled-release granules and organic feeds differ in nutrient delivery, salt risk and effort indoors.','Pick one feeding format and run it consistently: a balanced liquid at label rate every 2–4 weeks during active growth, or a controlled-release product — never both at full rate.',[
s('Read the analysis before the brand','Every fertilizer label carries three numbers: the percentage by weight of nitrogen (N), available phosphate (P₂O₅) and soluble potash (K₂O). To get elemental values, multiply phosphate by 0.436 and potash by 0.83, so a 2-2-2 product actually supplies about 2% N, 0.9% P and 1.7% K.\n\nThe ratio tells you more than the size of the numbers. Foliage plants build leaves from nitrogen, so ratios such as 3-1-2 suit monstera, pothos and philodendron well; balanced 1-1-1 or 2-2-2 feeds work for mixed collections. A high-analysis powder and a low-analysis liquid can deliver the same nutrients once each is diluted as directed — what reaches the roots is the working solution, not what is printed in large type on the front.'),
s('Liquid feeds: fast, flexible and easy to stop','Liquids deliver nutrients already dissolved, so roots can take them up within hours. That makes them the most controllable format indoors: you decide each dose, and you can simply stop when growth slows in autumn. Two familiar US examples illustrate the range. Per the manufacturer, Miracle-Gro Indoor Plant Food is a 1-1-1 liquid in a pump dispenser, while Espoma Organic Indoor! is a 2-2-2 liquid concentrate that must be diluted before use.\n\nMeasurement habits differ between those formats, so never transfer a pump count or cap measure from one product to another. A properly mixed feed for most foliage houseplants lands around 0.8–1.5 mS/cm electrical conductivity (EC); many growers feed at half strength every watering or two rather than full strength once a month, which keeps root-zone salts steadier.'),
s('Controlled-release granules: temperature sets the pace','Coated prills such as Osmocote release nutrients as water diffuses through a resin shell, and the rate is driven mainly by temperature. Label durations of 3–4, 6 or 8–9 months are calculated at about 21 °C (70 °F); on a warm windowsill release runs faster, and in a cool winter room it slows.\n\nThe convenience is real, but you cannot switch granules off. If a plant stalls or its roots are damaged, the prills keep releasing. Record the date and rate you applied, and do not layer a full-strength liquid program on top — that is the most common route to fertilizer burn in otherwise healthy collections.'),
s('Organic feeds: microbes do the unlocking','Much of the nitrogen in organic fertilizers is bound in proteins and other compounds that soil microbes must convert to ammonium and nitrate before roots can absorb it. Soilless peat or coir mixes in a cool room support far less of that activity than garden soil, so organic feeds usually act more gently and more slowly indoors.\n\nOrganic is not the same as salt-free. Dissolved organic feeds still raise EC, and overdosing still injures root tips. Some also carry an odor and leave films on the pot surface; a moist, organic-rich top layer favours fungus gnats, so let the top 2–5 cm dry between waterings where the species allows.'),
s('Matching the format to your plants and season','Feed only when a plant is actively growing — roughly spring to late summer in temperate homes — and reduce or stop in winter unless it sits under grow lights. No fertilizer compensates for weak light or rotting roots; fix those first. PlantPal reminders are useful here mainly for spacing feeds consistently rather than for feeding more often.',['Mixed collection, hands-on grower: balanced liquid at half strength every 1–2 weeks in growth','Busy household or plant sitter: one controlled-release application in spring, no extra liquid','Salt-sensitive species (spider plant, peace lily, Dracaena): low-strength liquid plus a leach every 2–3 months','Freshly repotted into pre-fertilized mix: no additional feed for at least 6–8 weeks','Succulents and cacti: dilute feed 2–3 times in summer only'])
],['miracle-gro-indoor-plant-food','espoma-indoor-plant-food','liquid-vs-slow-release-fertilizer'],[{title:'Miracle-Gro: Indoor Plant Food',url:mg},{title:'Espoma: Indoor!',url:ep}]),
make('miracle-gro-indoor-plant-food','Miracle-Gro Indoor Plant Food: a label-based guide to the 1-1-1 pump','soil-fertilizer','What the 1-1-1 analysis of Miracle-Gro Indoor Plant Food means in practice, how to fit the pump bottle into a feeding program, and when to leave it on the shelf.','Treat the 1-1-1 pump as a mild, balanced feed: apply it to already moist mix during active growth, follow your local label, and skip it in winter low light.',[
s('What the manufacturer says the product is','According to the US manufacturer page, Miracle-Gro Indoor Plant Food is a liquid with a 1-1-1 analysis, sold in a pump dispenser and intended for houseplants. The page describes both applying pumps directly to the soil and diluting them in a watering can. This overview is based on that published information and general horticultural principles; it is not a hands-on product test.\n\nMiracle-Gro sells many other plant foods, including water-soluble powders with far higher analyses and entirely different directions. Formulations and labels also vary by country. Check that the name and numbers on your bottle match, and follow your local label for dose and frequency.'),
s('What 1-1-1 means once it is in the pot','A 1-1-1 analysis means 1% nitrogen, 1% phosphate (about 0.44% elemental phosphorus) and 1% potash (about 0.83% potassium) by weight. That is a low-concentration, balanced product. Low analysis is a practical advantage for home growers: a small measuring error changes the dose far less than with a concentrated powder.\n\nThe balanced ratio supplies proportionally more phosphorus than most foliage plants use; leafy aroids and ferns generally respond best to nitrogen-leaning feeds around 3-1-2. For a mixed windowsill of foliage and flowering plants, balanced is a reasonable compromise. Excess phosphorus is not immediately harmful, but it adds to the salts accumulating in the mix.'),
s('Fitting the pump into a feeding program','The pump is designed for convenience, and convenience is exactly where routines drift. Anchor it to a defined schedule rather than to whenever the bottle catches your eye.',['Feed during active growth only, roughly spring to late summer, at the interval your label states','Water first if the mix is dry — nutrients applied to bone-dry peat or coir concentrate in the few roots that are wet','Use one application method consistently; do not alternate direct pumps and watering-can dilution without tracking the total','After repotting into a pre-fertilized mix, wait at least 6–8 weeks before starting','Under grow lights in winter, continue at the lower end of the label rate'])
,
s('Salts, EC and water quality','Every feed adds soluble salts, and indoor pots rarely receive enough rain-like flushing to remove them. Hard tap water adds calcium carbonate on top, showing up as a white crust on the rim and surface. Salt build-up raises the osmotic pressure around roots, making water uptake harder and producing brown leaf tips and margins.\n\nEvery 2–3 months, or whenever a crust appears, leach the pot: run 2–3 times its volume of clean water through it, provided drainage and roots are sound. Never use water from a salt-based softener, which adds sodium. Salt- and fluoride-sensitive species such as spider plant (Chlorophytum comosum), peace lily and Dracaena benefit from the lower end of the label range.'),
s('When not to use it','Fertilizer cannot fix a problem caused by light, water or roots, and feeding a stressed plant usually adds injury. Leave the bottle closed when a plant is wilting in wet mix, when roots are soft or brown, when cuttings have no working roots yet, or when succulents and snake plants are resting in winter. If new growth is pale and small in a dim room, move the plant toward brighter light before reaching for plant food; more fertilizer in low light mostly means more salt in the pot.')
],['common-houseplant-fertilizers','npk-fertilizer-numbers','fertilizer-burn-houseplants'],[{title:'Manufacturer details and current label link',url:mg}]),
make('espoma-indoor-plant-food','Espoma Organic Indoor! plant food: using a 2-2-2 concentrate well','soil-fertilizer','A label-based look at Espoma Organic Indoor! 2-2-2 liquid concentrate: how organic nitrogen behaves in potting mix, measuring dilutions, and when to hold off.','Always dilute the concentrate exactly as your local label directs, feed only actively growing plants, and remember that organic feeds still add salts.',[
s('What Espoma states about the product','Per the manufacturer, Espoma Organic Indoor! Houseplant Food is a liquid concentrate with a 2-2-2 analysis, marketed as an organic option, and must be diluted in water before it is applied to the potting mix. This article summarises that published information and adds general horticultural context; it is not a hands-on product trial or an endorsement for every plant.\n\nLabels are revised and can differ between markets. Before the first use, read the dilution rate, application interval and storage directions on your own bottle, and follow your local label wherever it differs from anything written here.'),
s('How organic nitrogen behaves in a pot','Much of the nitrogen in organic fertilizers arrives in forms that microbes must break down into ammonium and nitrate before roots can absorb them. Garden soil teems with those organisms; a soilless peat or coir mix at 18–22 °C supports far fewer. The practical result is a gentler, slower response than with a fully soluble mineral feed.\n\nThat gentleness is useful for beginners, but it tempts people to add more when nothing visible happens in a week. Judge results over 4–6 weeks of new growth, not days. Leaf colour and internode length in new shoots are better indicators than the older leaves, which rarely change.'),
s('Dilution is where accuracy is won or lost','A 2-2-2 concentrate carries twice the nutrient percentage of a 1-1-1 product per unit weight, but concentration on the label says nothing about the working strength; only your dilution sets that. Measure with a kitchen measuring spoon or an oral syringe kept for plant use, never by eye or by glugging from the bottle.\n\nShake the bottle first, since organic concentrates can settle. Mix only what you will use that day and discard leftovers onto outdoor beds rather than storing diluted feed, which can ferment and smell. Water the mix lightly first if it is dry, then apply the diluted feed until 10–20% runs out of the drainage holes, and empty the saucer within 15–30 minutes.'),
s('Building a season around it','A simple program for a mixed collection of tropical foliage plants looks like this, adjusted to your label.',['Early spring, when new leaves appear: start at half the label rate for the first feed','Late spring to late summer: label rate at the stated interval, typically every 2–4 weeks','Early autumn: stretch the interval as growth slows','Winter in low light: stop; resume only for plants under grow lights','Every 2–3 months: leach with 2–3 pot volumes of clean water to clear accumulated salts'])
,
s('When to hold off','Skip feeding when roots are waterlogged or rotting, when a plant has just been repotted into a mix that already contains fertilizer, and for unrooted cuttings. Organic liquids leave dissolved organic matter on the surface of the mix, and a consistently moist organic surface is exactly where fungus gnat larvae thrive, so let the top 2–5 cm dry between waterings for species that tolerate it.\n\nOrganic does not mean safe to ingest. Store the concentrate in its original container, away from heat, children and pets, and keep plant-care measuring tools separate from kitchen ones.')
],['common-houseplant-fertilizers','fertilizing-houseplants','liquid-vs-slow-release-fertilizer'],[{title:'Espoma Indoor! manufacturer directions',url:ep}]),
make('miracle-gro-indoor-potting-mix','Miracle-Gro Indoor Potting Mix: what its label means for watering and feeding','soil-fertilizer','A label-based overview of Miracle-Gro Indoor Potting Mix: a coir-based, compost- and bark-free blend with starter feed, and how it changes your care routine.','Treat the built-in fertilizer as your first feeding program: add no extra plant food for at least 2–3 months after potting, then watch new growth before resuming.',[
s('What the manufacturer describes','On its US product page, Miracle-Gro describes Indoor Potting Mix as a blend for indoor container plants that contains coconut coir, contains no compost or bark, feeds for up to 6 months, and is less prone to gnats. Those are manufacturer claims; this overview explains what they mean in practice and is not based on hands-on testing.\n\nThe brand sells several other mixes, and bagged formulations differ by country and change over time. Check the ingredients and feeding statement on your own bag and follow your local label.'),
s('How a coir-based mix behaves','Coir is the processed pith and fibre of coconut husks. It typically sits around pH 5.5–6.8, holds a lot of water while keeping some air space, and good-quality coir is washed and buffered with calcium so it does not tie up calcium and magnesium. Like peat, it becomes hard to rewet if it dries out completely; if the mix pulls away from the pot wall, bottom soak for 10–30 minutes until the surface darkens, then drain fully.\n\nA fine, uniform bagged mix is moisture-retentive. In a shallow pot it holds a saturated perched water table at the base, which gravel does not remove. For most foliage plants, water when the top 2–5 cm is dry. For climbing aroids such as Monstera deliciosa, many growers open it up at roughly 1 part mix, 1 part fine bark and 1 part perlite or pumice.'),
s('The built-in fertilizer and your feeding calendar','The manufacturer says the mix feeds for up to 6 months. Treat that as an upper limit: nutrient release depends on temperature, how often you water and how vigorously the plant grows, so a warm, bright, fast-growing pothos exhausts it sooner than a slow ZZ in a cool room.\n\nDo not add controlled-release granules and full-strength liquid feed to fresh pre-fertilized mix; that doubles the salt load around new, still-establishing roots. A sound approach is no extra feed for the first 2–3 months, then start a liquid at half strength if new leaves come in smaller or paler, and move to your normal program by month 4–6.'),
s('Gnats: why the formulation helps, and what still matters','Fungus gnat larvae (Bradysia spp.) live in the top 5 cm of moist organic media and feed on fungi and decaying material. Removing compost and bark takes away some of their favourite food, which supports the manufacturer claim. Coir is still organic, though, and any mix kept constantly wet can host gnats.\n\nPrevention is mainly about moisture at the surface. Let the top 2–5 cm dry where the species allows, use yellow sticky cards to monitor adults, and quarantine new plants, which are the usual source of an infestation.'),
s('When to choose a different mix','A general indoor mix is a good default for common foliage plants but not a universal answer.',['Succulents, cacti, aloe and snake plant: blend with 40–60% pumice, perlite or grit','Epiphytic orchids: use a bark- or moss-based orchid medium instead','Large aroids in big pots: add bark and perlite to keep the root zone open','Unrooted cuttings: use a low-nutrient medium such as moist perlite or a seed mix','Plants you already feed on a strict liquid program: an unfertilized mix gives you full control'])
],['potting-mix-vs-garden-soil','coco-coir-vs-peat','fungus-gnats-houseplants'],[{title:'Miracle-Gro Indoor Potting Mix manufacturer information',url:mix}]),
make('propagating-pothos','How to propagate pothos from node cuttings in water or substrate','tips','Step-by-step pothos propagation: choosing nodes, cut length, water versus substrate, 20–25 °C for rooting in 2–4 weeks, and potting up at 2–5 cm of root.','Every pothos cutting needs at least one healthy node; keep it at 20–25 °C in bright indirect light and pot it up once roots reach 2–5 cm.',[
s('Find the node and make the cut','Pothos (Epipremnum aureum) roots from its nodes: the slightly swollen points where each leaf joins the vine, usually marked by a small brown bump that is a dormant aerial root. A leaf with only its petiole will sometimes root but almost never produces a new vine, because it has no bud.\n\nUse a clean, sharp blade and take cuttings 10–15 cm (4–6 in) long with 2–4 nodes, or cut the vine into single-node sections if you want many plants. Cut about 1 cm below a node and remove any leaf that would sit underwater or below the surface. Choose firm, green vine from a pest-free plant, not the thin, pale tips of a vine that has been hanging in dim light. The sap contains calcium oxalate crystals and pothos is listed by the ASPCA as toxic to cats and dogs, so clear up trimmings and wash your hands afterwards.'),
s('Water or substrate: choose one and commit','Both methods work. What harms cuttings is switching back and forth, because roots formed in water are structurally different from roots formed in a solid medium and must adapt once more when moved.',['Water: glass jar, nodes submerged, leaves above; change the water weekly to keep it oxygenated','Water: roots are easy to monitor, but expect a short pause in growth after potting','Substrate: moist perlite, sphagnum moss or a 50:50 perlite and potting mix, nodes buried 1–2 cm','Substrate: cover loosely with a clear bag or tray lid to keep humidity high, venting daily','Substrate: roots emerge already adapted, so the move into a pot is smoother'])
,
s('Conditions that speed rooting','Warmth drives root initiation. At 20–25 °C (68–77 °F) the first roots usually appear within 2–4 weeks; below about 18 °C the process slows markedly, so a spot near a heating vent is worse than a warm shelf away from drafts. A heat mat set to around 24 °C helps in winter.\n\nGive bright indirect light, roughly 5,000–15,000 lux, with no direct midday sun, which overheats a jar of water. Do not fertilize: the cutting has no roots to take up nutrients, and salts only stress the cut surface. Rooting hormone is optional for pothos, which roots readily without it. Heavily variegated cultivars such as Marble Queen have less chlorophyll and root more slowly than green Jade.'),
s('Potting up when roots are 2–5 cm','Pot water-rooted cuttings when the roots are 2–5 cm (1–2 in) long; waiting until they form a long tangle makes the transition harder. Use an 8–10 cm (3–4 in) pot with drainage and a light, well-aerated mix, and plant three to five cuttings together if you want a full-looking plant quickly.\n\nSet the nodes 1–2 cm below the surface and firm gently. For the first 1–2 weeks keep the mix evenly moist so water-formed roots do not desiccate, then switch to the normal pothos routine of watering when the top 2–5 cm is dry. Wait about 6 weeks before the first half-strength feed.'),
s('Troubleshooting a stalled cutting','A soft, dark or smelly stem means rot: cut back to firm, green tissue above the damage, rinse the jar and start again. One yellowing leaf while rooting is normal, since the cutting recycles nutrients from it. If nothing has rooted after 6 weeks, the usual causes are cold, low light or a node that was damaged or missing. Cloudy water signals bacteria; change it more often and use a smaller jar.')
],['pothos-care','repotting-houseplants','how-to-water-houseplants']),
make('cleaning-houseplant-leaves','How to clean houseplant leaves without damaging them','tips','Why dust starves leaves of light, how to clean smooth, hairy and waxy foliage safely, and why leaf shine, mayonnaise and milk do more harm than good.','Dust every 4–6 weeks with plain lukewarm water and a soft cloth or brush suited to the leaf, and use each cleaning as a close pest inspection.',[
s('Why dust costs your plant light','Indoor plants already live on a small fraction of outdoor light: a typical room away from windows sits at 50–500 lux, against about 100,000 lux in full summer sun. A film of dust on the upper leaf surface absorbs and scatters part of that light before it reaches the chloroplasts inside the leaf, so a dusty plant in a medium-light spot behaves as if it had been moved further from the window.\n\nDust also settles into the crevices where spider mites and thrips shelter, and a greasy kitchen film holds more of it. Removing it is one of the few improvements to light you can make without moving the plant.'),
s('Smooth, broad leaves: damp cloth and a supporting hand','Rubber plant (Ficus elastica), Monstera deliciosa, peace lily, ZZ and fiddle-leaf fig (Ficus lyrata) have smooth, tough cuticles that tolerate wiping. Use a soft microfibre cloth dampened with lukewarm water, cup the leaf from below with your other hand, and wipe from the stalk toward the tip in one direction. Clean the underside too, where most stomata are and where pests hide.\n\nRinse the cloth often so you are not smearing dust around. For a sticky or greasy film, add one or two drops of mild liquid soap to a litre of water, then wipe again with plain water. Wear gloves for Ficus if you are sensitive to its latex sap, and avoid wiping young, still-expanding leaves, which bruise easily.'),
s('Hairy, textured and waxy leaves need a different approach','Fuzzy leaves on African violets (Saintpaulia) and velvet-leaf philodendrons trap water and bruise under a cloth. Use a soft, dry paintbrush or a clean make-up brush instead. Keep cold water off African violets altogether, since it causes pale ring spots.\n\nMany succulents, such as Echeveria, carry a powdery, waxy bloom (epicuticular wax) that reflects excess sun and does not grow back once rubbed off. Clear dust with a hand bulb blower or a very light brush. Small-leaved plants such as ferns, Ficus benjamina and string-of-pearls are easiest to rinse under a gentle lukewarm shower with the pot wrapped in a plastic bag, then left to drip dry out of direct sun.'),
s('Why leaf shine, mayonnaise and milk do more harm than good','A leaf’s natural gloss comes from its waxy cuticle. Oils, mayonnaise, milk and commercial leaf-shine products coat that surface with a film that can clog stomata, trap more dust, and in the case of food products go rancid or grow mould. Some shine sprays also scorch tender foliage under strong light. None of them feed the plant.\n\nIf you want a plant to look its best, give it enough light and clean it with water. A healthy, dust-free leaf already has all the shine its species is meant to have.'),
s('Turn every cleaning into an inspection','Cleaning puts you closer to each leaf than you ever are when watering. A 10× hand lens makes the first signs of trouble visible weeks before they show from across the room.',['Fine yellow or white stippling on upper surfaces, or fine webbing: spider mites','White cottony tufts in leaf axils and along veins: mealybugs','Brown or tan immovable bumps on stems and midribs: scale insects','Silvery streaks with black specks: thrips','Sticky residue (honeydew) on leaves or furniture below: sap-sucking insects above','If you find pests, use a fresh cloth for each plant and isolate the affected one'])
],['rubber-plant-care','spider-mites-houseplants','quarantine-new-houseplants']),
];
