import type {Article} from './content';

export const newLocaleCodes=['fr','it','hi','zh','ar','pt','ru','es'] as const;
export type NewLocale=typeof newLocaleCodes[number];

type Pack={lang:string;dir:'ltr'|'rtl';label:string;home:string;guides:string;learn:string;soil:string;glossary:string;app:string;download:string;heroEyebrow:string;heroTitle:string;heroAccent:string;heroText:string;explore:string;libraryTitle:string;libraryText:string;search:string;all:string;read:string;minutes:string;ctaTitle:string;ctaText:string;categories:Record<string,string>;};

export const packs:Record<NewLocale,Pack>={
fr:{lang:'fr-FR',dir:'ltr',label:'Français',home:'Accueil',guides:'Guides des plantes',learn:'Conseils et guides',soil:'Terreaux et engrais',glossary:'Glossaire',app:'L’application',download:'Télécharger PlantPal',heroEyebrow:'VOTRE COIN DE VERDURE',heroTitle:'Un peu d’attention.',heroAccent:'Beaucoup plus de vie.',heroText:'Apprenez à connaître vos plantes, comprenez leurs besoins et aidez-les à s’épanouir avec PlantPal.',explore:'Découvrir les conseils',libraryTitle:'Des repères clairs pour des plantes en pleine forme.',libraryText:'Des réponses pratiques, pensées pour les plantes que l’on cultive vraiment à la maison.',search:'Rechercher un guide',all:'Tous les guides',read:'Lire le guide',minutes:'min de lecture',ctaTitle:'Vos plantes comptent sur vous. Vous pouvez compter sur PlantPal.',ctaText:'Identification, rappels et conseils personnalisés réunis dans une seule application.',categories:{'plant-guides':'Guides des plantes','plant-care':'Entretien','troubleshooting':'Problèmes courants','soil-fertilizer':'Terreaux et engrais',tips:'Astuces'}},
it:{lang:'it-IT',dir:'ltr',label:'Italiano',home:'Home',guides:'Guide alle piante',learn:'Consigli e guide',soil:'Terricci e concimi',glossary:'Glossario',app:'L’app',download:'Scarica PlantPal',heroEyebrow:'IL TUO ANGOLO VERDE',heroTitle:'Un po’ di cura.',heroAccent:'Molta più vita.',heroText:'Conosci le tue piante, capisci ciò di cui hanno bisogno e aiutale a crescere con PlantPal.',explore:'Scopri i consigli',libraryTitle:'Più conoscenza, piante più felici.',libraryText:'Risposte concrete per chi coltiva piante vere in case vere.',search:'Cerca una guida',all:'Tutte le guide',read:'Leggi la guida',minutes:'min di lettura',ctaTitle:'Le tue piante hanno te. Tu hai PlantPal.',ctaText:'Identificazione, promemoria e consigli personalizzati in un’unica app.',categories:{'plant-guides':'Guide alle piante','plant-care':'Cura delle piante','troubleshooting':'Problemi delle piante','soil-fertilizer':'Terricci e concimi',tips:'Consigli pratici'}},
hi:{lang:'hi-IN',dir:'ltr',label:'हिन्दी',home:'होम',guides:'पौधों की गाइड',learn:'देखभाल सीखें',soil:'मिट्टी और खाद',glossary:'शब्दकोश',app:'ऐप',download:'PlantPal डाउनलोड करें',heroEyebrow:'आपका अपना हरा-भरा कोना',heroTitle:'थोड़ी-सी देखभाल।',heroAccent:'ढेर सारी हरियाली।',heroText:'अपने पौधों को पहचानें, उनकी ज़रूरतें समझें और PlantPal के साथ उन्हें स्वस्थ रखें।',explore:'पौधों की देखभाल जानें',libraryTitle:'सही जानकारी से खुशहाल पौधे।',libraryText:'घर में पौधे उगाने वालों के लिए आसान और काम की सलाह।',search:'गाइड खोजें',all:'सभी गाइड',read:'गाइड पढ़ें',minutes:'मिनट',ctaTitle:'आप पौधों का ध्यान रखते हैं। PlantPal आपका साथ देता है।',ctaText:'पहचान, रिमाइंडर और व्यक्तिगत देखभाल सलाह—सब एक ही ऐप में।',categories:{'plant-guides':'पौधों की गाइड','plant-care':'पौधों की देखभाल','troubleshooting':'पौधों की समस्याएँ','soil-fertilizer':'मिट्टी और खाद',tips:'काम के सुझाव'}},
zh:{lang:'zh-CN',dir:'ltr',label:'简体中文',home:'首页',guides:'植物指南',learn:'养护知识',soil:'土壤与肥料',glossary:'植物词典',app:'应用介绍',download:'下载 PlantPal',heroEyebrow:'属于你的绿色角落',heroTitle:'多一点用心，',heroAccent:'多很多生机。',heroText:'认识你的植物，读懂它们的需要，用 PlantPal 陪伴每一次成长。',explore:'探索植物养护',libraryTitle:'懂得更多，植物长得更好。',libraryText:'为真实居家环境编写的实用植物养护建议。',search:'搜索指南',all:'全部指南',read:'阅读指南',minutes:'分钟阅读',ctaTitle:'你照顾植物，PlantPal 帮助你。',ctaText:'植物识别、养护提醒和个性化建议，都在一个应用中。',categories:{'plant-guides':'植物指南','plant-care':'日常养护','troubleshooting':'常见问题','soil-fertilizer':'土壤与肥料',tips:'实用技巧'}},
ar:{lang:'ar',dir:'rtl',label:'العربية',home:'الرئيسية',guides:'أدلة النباتات',learn:'تعلّم العناية',soil:'التربة والأسمدة',glossary:'قاموس النباتات',app:'التطبيق',download:'حمّل PlantPal',heroEyebrow:'ركنك الأخضر الخاص',heroTitle:'قليل من العناية،',heroAccent:'وكثير من الحياة.',heroText:'تعرّف إلى نباتاتك، وافهم احتياجاتها، وساعدها على الازدهار مع PlantPal.',explore:'اكتشف العناية بالنباتات',libraryTitle:'معرفة أوضح لنباتات أكثر صحة.',libraryText:'إجابات عملية تناسب النباتات التي نزرعها في بيوتنا بالفعل.',search:'ابحث عن دليل',all:'كل الأدلة',read:'اقرأ الدليل',minutes:'دقائق قراءة',ctaTitle:'نباتاتك تعتمد عليك، وأنت يمكنك الاعتماد على PlantPal.',ctaText:'التعرّف إلى النباتات والتذكيرات والإرشادات المخصصة في تطبيق واحد.',categories:{'plant-guides':'أدلة النباتات','plant-care':'العناية بالنباتات','troubleshooting':'مشكلات النباتات','soil-fertilizer':'التربة والأسمدة',tips:'نصائح عملية'}},
pt:{lang:'pt-BR',dir:'ltr',label:'Português',home:'Início',guides:'Guias de plantas',learn:'Aprenda a cuidar',soil:'Substratos e adubos',glossary:'Glossário',app:'O aplicativo',download:'Baixe o PlantPal',heroEyebrow:'SEU CANTINHO VERDE',heroTitle:'Um pouco de cuidado.',heroAccent:'Muito mais vida.',heroText:'Conheça suas plantas, entenda o que elas precisam e ajude cada uma a crescer com o PlantPal.',explore:'Explore os cuidados',libraryTitle:'Mais conhecimento, plantas mais felizes.',libraryText:'Respostas práticas para quem cultiva plantas de verdade dentro de casa.',search:'Buscar um guia',all:'Todos os guias',read:'Ler o guia',minutes:'min de leitura',ctaTitle:'Suas plantas têm você. Você tem o PlantPal.',ctaText:'Identificação, lembretes e orientações personalizadas em um só aplicativo.',categories:{'plant-guides':'Guias de plantas','plant-care':'Cuidados com plantas','troubleshooting':'Problemas comuns','soil-fertilizer':'Substratos e adubos',tips:'Dicas práticas'}},
ru:{lang:'ru-RU',dir:'ltr',label:'Русский',home:'Главная',guides:'Справочник растений',learn:'Уход за растениями',soil:'Грунты и удобрения',glossary:'Словарь',app:'Приложение',download:'Скачать PlantPal',heroEyebrow:'ВАШ ЗЕЛЁНЫЙ УГОЛОК',heroTitle:'Немного заботы.',heroAccent:'Гораздо больше жизни.',heroText:'Узнавайте свои растения, понимайте их потребности и помогайте им расти вместе с PlantPal.',explore:'Узнать об уходе',libraryTitle:'Больше знаний — здоровее растения.',libraryText:'Практичные ответы для тех, кто выращивает растения дома.',search:'Найти руководство',all:'Все руководства',read:'Читать',minutes:'мин чтения',ctaTitle:'У растений есть вы. У вас есть PlantPal.',ctaText:'Распознавание, напоминания и персональные рекомендации в одном приложении.',categories:{'plant-guides':'Справочник растений','plant-care':'Уход за растениями','troubleshooting':'Проблемы растений','soil-fertilizer':'Грунты и удобрения',tips:'Полезные советы'}},
es:{lang:'es-ES',dir:'ltr',label:'Español',home:'Inicio',guides:'Guías de plantas',learn:'Aprende a cuidarlas',soil:'Sustratos y abonos',glossary:'Glosario',app:'La aplicación',download:'Descargar PlantPal',heroEyebrow:'TU RINCÓN VERDE',heroTitle:'Un poco de cuidado.',heroAccent:'Mucha más vida.',heroText:'Conoce tus plantas, entiende lo que necesitan y ayúdalas a prosperar con PlantPal.',explore:'Descubrir cuidados',libraryTitle:'Más conocimiento, plantas más felices.',libraryText:'Respuestas prácticas para quienes cultivan plantas de verdad en casa.',search:'Buscar una guía',all:'Todas las guías',read:'Leer la guía',minutes:'min de lectura',ctaTitle:'Tus plantas te tienen a ti. Tú tienes PlantPal.',ctaText:'Identificación, recordatorios y orientación personalizada en una sola aplicación.',categories:{'plant-guides':'Guías de plantas','plant-care':'Cuidado de plantas','troubleshooting':'Problemas comunes','soil-fertilizer':'Sustratos y abonos',tips:'Consejos prácticos'}},
};

