import {packs, newLocaleCodes, type NewLocale} from './multilingual';
import {plants, type Plant} from './plants';
import {SITE_URL} from './config';

export type PlantLocale = 'en' | 'he' | NewLocale;
export type PlantGroup = 'easy' | 'statement' | 'trailing';
type PlantTranslation = [name: string, intro: string, tip: string];
type LightKind = 'bright' | 'medium' | 'low' | 'sun';
type WaterKind = 'top' | 'partial' | 'dry' | 'even';

export type PlantUi = {
  plantsLabel: string; home: string; heroEyebrow: string; heroLine: string; heroAccent: string; heroText: string; heroLink: string; heroFoot: string;
  collectionEyebrow: string; collectionTitle: string; collectionText: string; countLabel: string; searchLabel: string; searchPlaceholder: string; clearSearch: string;
  filters: Record<'all' | PlantGroup, string>; results: string; resultsOne: string; emptyTitle: string; emptyText: string; reset: string;
  bannerEyebrow: string; bannerTitle: string; bannerText: string; beginnerGuide: string;
  detailEyebrow: string; light: string; water: string; back: string; careEyebrow: string; careTitle: string; lightHeading: string; waterHeading: string; tipHeading: string;
  fullGuide: string; furtherReading: string; sourceLabel: string; asideEyebrow: string; asideText: string; relatedEyebrow: string; relatedTitle: string;
  imageAlt: string; cardAlt: string; detailAlt: string; cardLink: string;
  metaIndexTitle: string; metaIndexDescription: string; metaDetail: string;
};

export const plantUi: Record<PlantLocale, PlantUi> = {
  en: {
    plantsLabel:'Houseplants',home:'Home',heroEyebrow:'A HOME FOR EVERY PLANT',heroLine:'Meet your',heroAccent:'next houseplant.',heroText:'From the quietly easy to the wonderfully dramatic, find a plant that feels right for your light, your space, and your life.',heroLink:'Explore the collection',heroFoot:'Ten beloved houseplants. Just the beginning.',
    collectionEyebrow:'THE PLANTPAL COLLECTION',collectionTitle:'Find your next favorite.',collectionText:'Ten well-loved houseplants to get started. The collection will keep growing.',countLabel:'plants to explore',searchLabel:'Search plants',searchPlaceholder:'Search by common or botanical name...',clearSearch:'Clear search',
    filters:{all:'All plants',easy:'Easy-care',statement:'Statement plants',trailing:'Trailing & climbing'},results:'{count} plants found',resultsOne:'1 plant found',emptyTitle:'No plants found',emptyText:'Try another name or choose a different filter.',reset:'Show all plants',
    bannerEyebrow:'GROW WITH CONFIDENCE',bannerTitle:'New plant at home? Start well.',bannerText:'Your room matters more than any fixed watering calendar. Learn to read the light, the potting mix, and the leaves.',beginnerGuide:'Beginner’s care guide',
    detailEyebrow:'MEET THE PLANT',light:'Light',water:'Water',back:'Explore all plants',careEyebrow:'THE CARE NOTES',careTitle:'How to help it thrive.',lightHeading:'Light & placement',waterHeading:'Water & drainage',tipHeading:'One thing to remember',fullGuide:'Read the full care guide',furtherReading:'Further reading:',sourceLabel:'Horticultural source',asideEyebrow:'A LITTLE REMINDER',asideText:'A watering schedule is only a starting point. Always check the potting mix and the conditions in your home.',relatedEyebrow:'KEEP EXPLORING',relatedTitle:'You might love these, too.',
    imageAlt:'A collection of houseplants in warm window light',cardAlt:'{name} ({scientific}) in an indoor planter',detailAlt:'{name} ({scientific}) in an indoor planter',cardLink:'Explore {name}',metaIndexTitle:'Houseplants: Explore 10 Popular Indoor Plants',metaIndexDescription:'Explore ten well-loved houseplants with original images and practical tips for light, watering and care. Find the right plant for your home.',metaDetail:'{name} care: light, watering & growing tips',
  },
  he: {
    plantsLabel:'צמחי בית',home:'דף הבית',heroEyebrow:'הבית של הצמחים',heroLine:'הכירו את',heroAccent:'צמחי הבית שלכם.',heroText:'מקטנים וצנועים ועד גדולים ומרשימים — מוצאים את הצמח שמתאים לאור, לחלל ולקצב החיים שלכם.',heroLink:'לגלות את הצמחים',heroFoot:'עשרה צמחי בית אהובים. ואנחנו רק מתחילים.',
    collectionEyebrow:'אוסף PLANTPAL',collectionTitle:'מוצאים את הצמח הבא.',collectionText:'עשרה צמחי בית אהובים להתחלה. האוסף ימשיך לצמוח.',countLabel:'צמחים באוסף',searchLabel:'חיפוש צמחים',searchPlaceholder:'חפשו לפי שם הצמח...',clearSearch:'ניקוי חיפוש',
    filters:{all:'כל הצמחים',easy:'קלים לטיפול',statement:'צמחים בולטים',trailing:'מטפסים ומשתלשלים'},results:'נמצאו {count} צמחים',resultsOne:'נמצא צמח אחד',emptyTitle:'לא מצאנו צמח מתאים',emptyText:'נסו שם אחר או בחרו סינון שונה.',reset:'הציגו את כל הצמחים',
    bannerEyebrow:'גדלים ביחד',bannerTitle:'צמח חדש בבית? מתחילים נכון.',bannerText:'תנאי הבית שלכם חשובים יותר מכל לוח השקיה קבוע. למדו איך לקרוא אור, מצע ועלים לפני שמטפלים.',beginnerGuide:'המדריך למתחילים',
    detailEyebrow:'להכיר את הצמח',light:'אור',water:'השקיה',back:'לכל הצמחים',careEyebrow:'טיפול פשוט ומדויק',careTitle:'איך עוזרים לו לשגשג?',lightHeading:'אור ומיקום',waterHeading:'מים וניקוז',tipHeading:'טיפ קטן שעוזר',fullGuide:'למדריך הטיפול המלא',furtherReading:'לקריאה נוספת:',sourceLabel:'מקור גנני חיצוני',asideEyebrow:'תזכורת קטנה',asideText:'לוח השקיה הוא רק נקודת פתיחה. בדקו תמיד את האדמה ואת התנאים בבית שלכם.',relatedEyebrow:'עוד צמחים לגלות',relatedTitle:'אולי גם הם יתאימו לכם.',
    imageAlt:'צמחי בית מגוונים באור שמש חמים ליד חלון',cardAlt:'{name} ({scientific}) בעציץ בבית',detailAlt:'{name} ({scientific}) בעציץ בבית',cardLink:'פרטים על {name}',metaIndexTitle:'צמחי בית: מדריך ל־10 צמחים אהובים',metaIndexDescription:'גלו עשרה צמחי בית אהובים, תמונות מקוריות וטיפים מעשיים לאור, השקיה וטיפול. בחרו את הצמח המתאים לבית שלכם.',metaDetail:'{name}: אור, השקיה וטיפול | צמחי בית',
  },
  fr: {
    plantsLabel:'Plantes d’intérieur',home:'Accueil',heroEyebrow:'UNE PLACE POUR CHAQUE PLANTE',heroLine:'Rencontrez votre',heroAccent:'prochaine plante.',heroText:'Des plantes faciles aux plus spectaculaires, trouvez celle qui convient à la lumière, à l’espace et à votre quotidien.',heroLink:'Explorer la collection',heroFoot:'Dix plantes d’intérieur appréciées. Ce n’est qu’un début.',
    collectionEyebrow:'LA COLLECTION PLANTPAL',collectionTitle:'Trouvez votre prochaine plante.',collectionText:'Dix plantes d’intérieur pour commencer. La collection continuera de grandir.',countLabel:'plantes à découvrir',searchLabel:'Rechercher une plante',searchPlaceholder:'Nom courant ou botanique…',clearSearch:'Effacer la recherche',
    filters:{all:'Toutes les plantes',easy:'Faciles à entretenir',statement:'Plantes remarquables',trailing:'Retombantes et grimpantes'},results:'{count} plantes trouvées',resultsOne:'1 plante trouvée',emptyTitle:'Aucune plante trouvée',emptyText:'Essayez un autre nom ou filtre.',reset:'Afficher toutes les plantes',
    bannerEyebrow:'CULTIVEZ EN CONFIANCE',bannerTitle:'Une nouvelle plante chez vous ?',bannerText:'Les conditions de votre intérieur comptent plus qu’un calendrier fixe. Apprenez à observer la lumière, le terreau et les feuilles.',beginnerGuide:'Guide pour débuter',
    detailEyebrow:'DÉCOUVRIR LA PLANTE',light:'Lumière',water:'Arrosage',back:'Toutes les plantes',careEyebrow:'CONSEILS D’ENTRETIEN',careTitle:'Comment l’aider à s’épanouir ?',lightHeading:'Lumière et emplacement',waterHeading:'Arrosage et drainage',tipHeading:'À retenir',fullGuide:'Lire le guide complet',furtherReading:'Pour aller plus loin :',sourceLabel:'Source horticole',asideEyebrow:'PETIT RAPPEL',asideText:'Un calendrier d’arrosage n’est qu’un point de départ. Vérifiez toujours le terreau et les conditions de votre intérieur.',relatedEyebrow:'POURSUIVEZ LA DÉCOUVERTE',relatedTitle:'Ces plantes pourraient aussi vous plaire.',
    imageAlt:'Collection de plantes d’intérieur dans la lumière chaude d’une fenêtre',cardAlt:'{name} ({scientific}) dans un pot à l’intérieur',detailAlt:'{name} ({scientific}) dans un pot à l’intérieur',cardLink:'Découvrir {name}',metaIndexTitle:'Plantes d’intérieur : 10 espèces populaires à découvrir',metaIndexDescription:'Découvrez dix plantes d’intérieur avec des images originales et des conseils pratiques sur la lumière, l’arrosage et l’entretien.',metaDetail:'{name} : lumière, arrosage et conseils d’entretien',
  },
  it: {
    plantsLabel:'Piante da interno',home:'Home',heroEyebrow:'UNA CASA PER OGNI PIANTA',heroLine:'Scopri la tua',heroAccent:'prossima pianta.',heroText:'Dalle più semplici alle più scenografiche, trova la pianta adatta alla luce, allo spazio e alle tue abitudini.',heroLink:'Esplora la collezione',heroFoot:'Dieci piante da interno amate. È solo l’inizio.',
    collectionEyebrow:'LA COLLEZIONE PLANTPAL',collectionTitle:'Trova la tua prossima pianta.',collectionText:'Dieci piante da interno da cui iniziare. La collezione continuerà a crescere.',countLabel:'piante da scoprire',searchLabel:'Cerca una pianta',searchPlaceholder:'Nome comune o botanico…',clearSearch:'Cancella la ricerca',
    filters:{all:'Tutte le piante',easy:'Facili da curare',statement:'Piante d’effetto',trailing:'Ricadenti e rampicanti'},results:'{count} piante trovate',resultsOne:'1 pianta trovata',emptyTitle:'Nessuna pianta trovata',emptyText:'Prova un altro nome o filtro.',reset:'Mostra tutte le piante',
    bannerEyebrow:'COLTIVA CON FIDUCIA',bannerTitle:'Una nuova pianta in casa?',bannerText:'Le condizioni di casa contano più di un calendario fisso. Impara a osservare luce, terriccio e foglie.',beginnerGuide:'Guida per iniziare',
    detailEyebrow:'CONOSCI LA PIANTA',light:'Luce',water:'Acqua',back:'Tutte le piante',careEyebrow:'NOTE DI CURA',careTitle:'Come aiutarla a crescere.',lightHeading:'Luce e posizione',waterHeading:'Acqua e drenaggio',tipHeading:'Da ricordare',fullGuide:'Leggi la guida completa',furtherReading:'Per saperne di più:',sourceLabel:'Fonte botanica',asideEyebrow:'UN PICCOLO PROMEMORIA',asideText:'Un calendario di irrigazione è solo un punto di partenza. Controlla sempre il terriccio e le condizioni di casa.',relatedEyebrow:'CONTINUA A ESPLORARE',relatedTitle:'Potrebbero piacerti anche queste.',
    imageAlt:'Piante da interno nella calda luce di una finestra',cardAlt:'{name} ({scientific}) in un vaso da interno',detailAlt:'{name} ({scientific}) in un vaso da interno',cardLink:'Scopri {name}',metaIndexTitle:'Piante da interno: scopri 10 specie popolari',metaIndexDescription:'Scopri dieci piante da interno con immagini originali e consigli pratici su luce, irrigazione e cura.',metaDetail:'{name}: luce, irrigazione e consigli di cura',
  },
  hi: {
    plantsLabel:'घर के पौधे',home:'होम',heroEyebrow:'हर पौधे के लिए एक घर',heroLine:'अपना अगला',heroAccent:'पौधा खोजें।',heroText:'आसान देखभाल वाले पौधों से लेकर खास आकर्षण वाले पौधों तक, अपनी रोशनी, जगह और दिनचर्या के लिए सही पौधा चुनें।',heroLink:'संग्रह देखें',heroFoot:'घर के दस पसंदीदा पौधे। यह तो बस शुरुआत है।',
    collectionEyebrow:'PLANTPAL का संग्रह',collectionTitle:'अपना अगला पसंदीदा पौधा चुनें।',collectionText:'शुरुआत के लिए घर के दस लोकप्रिय पौधे। आगे और पौधे जुड़ेंगे।',countLabel:'पौधे देखें',searchLabel:'पौधा खोजें',searchPlaceholder:'सामान्य या वैज्ञानिक नाम लिखें…',clearSearch:'खोज साफ़ करें',
    filters:{all:'सभी पौधे',easy:'आसान देखभाल',statement:'खास आकर्षण',trailing:'लटकने और चढ़ने वाले'},results:'{count} पौधे मिले',resultsOne:'1 पौधा मिला',emptyTitle:'कोई पौधा नहीं मिला',emptyText:'दूसरा नाम या फ़िल्टर आज़माएँ।',reset:'सभी पौधे दिखाएँ',
    bannerEyebrow:'भरोसे से उगाएँ',bannerTitle:'घर में नया पौधा आया है?',bannerText:'तय सिंचाई तालिका से ज़्यादा ज़रूरी हैं आपके घर की परिस्थितियाँ। रोशनी, मिट्टी और पत्तियों को समझना सीखें।',beginnerGuide:'शुरुआती देखभाल गाइड',
    detailEyebrow:'पौधे को जानें',light:'रोशनी',water:'पानी',back:'सभी पौधे देखें',careEyebrow:'देखभाल के सुझाव',careTitle:'इसे स्वस्थ कैसे रखें?',lightHeading:'रोशनी और जगह',waterHeading:'पानी और निकास',tipHeading:'याद रखने की बात',fullGuide:'पूरी गाइड पढ़ें',furtherReading:'और पढ़ें:',sourceLabel:'बागवानी स्रोत',asideEyebrow:'एक छोटा सा ध्यान',asideText:'पानी देने की तय तारीख़ केवल शुरुआत है। मिट्टी और अपने घर की परिस्थितियाँ हमेशा जाँचें।',relatedEyebrow:'और पौधे जानें',relatedTitle:'ये पौधे भी पसंद आ सकते हैं।',
    imageAlt:'खिड़की की गर्म रोशनी में रखे घर के पौधे',cardAlt:'घर के गमले में {name} ({scientific})',detailAlt:'घर के गमले में {name} ({scientific})',cardLink:'{name} के बारे में जानें',metaIndexTitle:'घर के पौधे: 10 लोकप्रिय इनडोर पौधे',metaIndexDescription:'दस लोकप्रिय घरेलू पौधों की मूल तस्वीरें और रोशनी, पानी व देखभाल के काम के सुझाव देखें।',metaDetail:'{name} की देखभाल: रोशनी, पानी और सुझाव',
  },
  zh: {
    plantsLabel:'室内植物',home:'首页',heroEyebrow:'为每株植物找到家',heroLine:'遇见你的',heroAccent:'下一株室内植物。',heroText:'从省心好养到引人注目，找到适合你家光照、空间和生活节奏的植物。',heroLink:'探索植物图鉴',heroFoot:'十种深受喜爱的室内植物，这只是开始。',
    collectionEyebrow:'PLANTPAL 植物图鉴',collectionTitle:'找到下一株心仪植物。',collectionText:'先从十种常见室内植物开始，图鉴还会继续丰富。',countLabel:'种植物可探索',searchLabel:'搜索植物',searchPlaceholder:'输入常见名或学名…',clearSearch:'清除搜索',
    filters:{all:'全部植物',easy:'容易养护',statement:'观赏焦点',trailing:'垂吊与攀援'},results:'找到 {count} 种植物',resultsOne:'找到 1 种植物',emptyTitle:'没有找到植物',emptyText:'试试其他名称或筛选条件。',reset:'显示全部植物',
    bannerEyebrow:'安心开始养护',bannerTitle:'刚带新植物回家？',bannerText:'家中的实际环境比固定浇水日程更重要。学会观察光照、盆土和叶片。',beginnerGuide:'新手养护指南',
    detailEyebrow:'认识这种植物',light:'光照',water:'浇水',back:'查看全部植物',careEyebrow:'养护笔记',careTitle:'怎样让它茁壮生长？',lightHeading:'光照与摆放',waterHeading:'浇水与排水',tipHeading:'记住这一点',fullGuide:'阅读完整养护指南',furtherReading:'延伸阅读：',sourceLabel:'园艺资料',asideEyebrow:'温馨提醒',asideText:'浇水日程只是参考。请始终检查盆土，并结合家中的实际环境。',relatedEyebrow:'继续探索',relatedTitle:'你可能也会喜欢。',
    imageAlt:'暖暖窗光中的多种室内植物',cardAlt:'室内花盆中的{name}（{scientific}）',detailAlt:'室内花盆中的{name}（{scientific}）',cardLink:'了解{name}',metaIndexTitle:'室内植物图鉴：认识10种常见植物',metaIndexDescription:'探索十种常见室内植物，欣赏原创图片，了解光照、浇水和日常养护要点。',metaDetail:'{name}养护指南：光照、浇水与生长建议',
  },
  ar: {
    plantsLabel:'النباتات المنزلية',home:'الرئيسية',heroEyebrow:'بيت لكل نبتة',heroLine:'تعرّف إلى',heroAccent:'نبتتك القادمة.',heroText:'من النباتات سهلة العناية إلى الأنواع اللافتة، اعثر على ما يناسب إضاءة منزلك ومساحته وإيقاع حياتك.',heroLink:'استكشف المجموعة',heroFoot:'عشر نباتات منزلية محبوبة. وهذه مجرد البداية.',
    collectionEyebrow:'مجموعة PLANTPAL',collectionTitle:'اعثر على نبتتك المفضلة التالية.',collectionText:'عشر نباتات منزلية لتبدأ بها. وستستمر المجموعة في النمو.',countLabel:'نباتات لاكتشافها',searchLabel:'ابحث عن نبات',searchPlaceholder:'ابحث بالاسم الشائع أو العلمي…',clearSearch:'امسح البحث',
    filters:{all:'كل النباتات',easy:'سهلة العناية',statement:'نباتات لافتة',trailing:'متدلية ومتسلقة'},results:'عُثر على {count} نباتات',resultsOne:'عُثر على نبتة واحدة',emptyTitle:'لم نعثر على نبات',emptyText:'جرّب اسمًا أو تصنيفًا آخر.',reset:'اعرض كل النباتات',
    bannerEyebrow:'ازرع بثقة',bannerTitle:'نبتة جديدة في المنزل؟',bannerText:'ظروف منزلك أهم من أي جدول ري ثابت. تعلّم قراءة الضوء والتربة والأوراق.',beginnerGuide:'دليل العناية للمبتدئين',
    detailEyebrow:'تعرّف إلى النبات',light:'الضوء',water:'الري',back:'كل النباتات',careEyebrow:'ملاحظات العناية',careTitle:'كيف تساعدها على النمو؟',lightHeading:'الضوء والموقع',waterHeading:'الري والتصريف',tipHeading:'نصيحة مهمة',fullGuide:'اقرأ دليل العناية الكامل',furtherReading:'قراءة إضافية:',sourceLabel:'مصدر بستاني',asideEyebrow:'تذكير صغير',asideText:'جدول الري مجرد نقطة بداية. افحص التربة وظروف منزلك دائمًا.',relatedEyebrow:'واصل الاكتشاف',relatedTitle:'قد تعجبك هذه النباتات أيضًا.',
    imageAlt:'نباتات منزلية متنوعة في ضوء نافذة دافئ',cardAlt:'{name} ({scientific}) في أصيص داخل المنزل',detailAlt:'{name} ({scientific}) في أصيص داخل المنزل',cardLink:'اكتشف {name}',metaIndexTitle:'النباتات المنزلية: 10 أنواع شائعة',metaIndexDescription:'اكتشف عشر نباتات منزلية مع صور أصلية ونصائح عملية حول الضوء والري والعناية.',metaDetail:'العناية بنبات {name}: الضوء والري ونصائح النمو',
  },
  pt: {
    plantsLabel:'Plantas de interior',home:'Início',heroEyebrow:'UM LAR PARA CADA PLANTA',heroLine:'Conheça sua',heroAccent:'próxima planta.',heroText:'Das mais fáceis às mais marcantes, encontre uma planta que combine com a luz, o espaço e a rotina da sua casa.',heroLink:'Explore a coleção',heroFoot:'Dez plantas de interior queridas. É só o começo.',
    collectionEyebrow:'A COLEÇÃO PLANTPAL',collectionTitle:'Encontre sua próxima planta.',collectionText:'Dez plantas de interior para começar. A coleção continuará crescendo.',countLabel:'plantas para descobrir',searchLabel:'Buscar plantas',searchPlaceholder:'Nome comum ou científico…',clearSearch:'Limpar busca',
    filters:{all:'Todas as plantas',easy:'Fáceis de cuidar',statement:'Plantas de destaque',trailing:'Pendentes e trepadeiras'},results:'{count} plantas encontradas',resultsOne:'1 planta encontrada',emptyTitle:'Nenhuma planta encontrada',emptyText:'Tente outro nome ou filtro.',reset:'Mostrar todas as plantas',
    bannerEyebrow:'CULTIVE COM CONFIANÇA',bannerTitle:'Uma planta nova em casa?',bannerText:'As condições da sua casa importam mais que um calendário fixo. Aprenda a observar a luz, o substrato e as folhas.',beginnerGuide:'Guia para iniciantes',
    detailEyebrow:'CONHEÇA A PLANTA',light:'Luz',water:'Rega',back:'Todas as plantas',careEyebrow:'NOTAS DE CUIDADO',careTitle:'Como ajudá-la a crescer.',lightHeading:'Luz e localização',waterHeading:'Rega e drenagem',tipHeading:'Vale lembrar',fullGuide:'Leia o guia completo',furtherReading:'Saiba mais:',sourceLabel:'Fonte de horticultura',asideEyebrow:'UM LEMBRETE',asideText:'Um calendário de rega é apenas um ponto de partida. Verifique sempre o substrato e as condições da sua casa.',relatedEyebrow:'CONTINUE EXPLORANDO',relatedTitle:'Você também pode gostar destas.',
    imageAlt:'Plantas de interior sob a luz quente da janela',cardAlt:'{name} ({scientific}) em vaso dentro de casa',detailAlt:'{name} ({scientific}) em vaso dentro de casa',cardLink:'Conheça {name}',metaIndexTitle:'Plantas de interior: conheça 10 espécies populares',metaIndexDescription:'Conheça dez plantas de interior com imagens originais e dicas práticas de luz, rega e cuidados.',metaDetail:'Cuidados com {name}: luz, rega e dicas de cultivo',
  },
  ru: {
    plantsLabel:'Комнатные растения',home:'Главная',heroEyebrow:'ДОМ ДЛЯ КАЖДОГО РАСТЕНИЯ',heroLine:'Найдите своё',heroAccent:'новое растение.',heroText:'От простых в уходе до эффектных — выберите растение, которому подойдут освещение, пространство и ритм вашего дома.',heroLink:'Смотреть коллекцию',heroFoot:'Десять любимых комнатных растений. Это только начало.',
    collectionEyebrow:'КОЛЛЕКЦИЯ PLANTPAL',collectionTitle:'Выберите новое любимое растение.',collectionText:'Для начала — десять популярных комнатных растений. Коллекция будет расти.',countLabel:'растений в коллекции',searchLabel:'Поиск растений',searchPlaceholder:'Название или латинское имя…',clearSearch:'Очистить поиск',
    filters:{all:'Все растения',easy:'Простые в уходе',statement:'Акцентные растения',trailing:'Свисающие и вьющиеся'},results:'Найдено растений: {count}',resultsOne:'Найдено одно растение',emptyTitle:'Растения не найдены',emptyText:'Попробуйте другое название или фильтр.',reset:'Показать все растения',
    bannerEyebrow:'РАСТИТЕ С УВЕРЕННОСТЬЮ',bannerTitle:'Дома появилось новое растение?',bannerText:'Условия в вашем доме важнее строгого графика полива. Научитесь оценивать свет, грунт и состояние листьев.',beginnerGuide:'Руководство для начинающих',
    detailEyebrow:'ЗНАКОМСТВО С РАСТЕНИЕМ',light:'Свет',water:'Полив',back:'Все растения',careEyebrow:'СОВЕТЫ ПО УХОДУ',careTitle:'Как помочь ему расти.',lightHeading:'Свет и размещение',waterHeading:'Полив и дренаж',tipHeading:'Что важно помнить',fullGuide:'Читать полное руководство',furtherReading:'Дополнительно:',sourceLabel:'Источник по садоводству',asideEyebrow:'НЕБОЛЬШОЕ НАПОМИНАНИЕ',asideText:'График полива — лишь ориентир. Всегда проверяйте грунт и учитывайте условия в вашем доме.',relatedEyebrow:'ИССЛЕДУЙТЕ ДАЛЬШЕ',relatedTitle:'Вам также могут понравиться.',
    imageAlt:'Комнатные растения в тёплом свете окна',cardAlt:'{name} ({scientific}) в комнатном горшке',detailAlt:'{name} ({scientific}) в комнатном горшке',cardLink:'Подробнее: {name}',metaIndexTitle:'Комнатные растения: 10 популярных видов',metaIndexDescription:'Познакомьтесь с десятью комнатными растениями: оригинальные изображения и советы по освещению, поливу и уходу.',metaDetail:'Уход за {name}: свет, полив и советы по выращиванию',
  },
  es: {
    plantsLabel:'Plantas de interior',home:'Inicio',heroEyebrow:'UN HOGAR PARA CADA PLANTA',heroLine:'Conoce tu',heroAccent:'próxima planta.',heroText:'De las más fáciles a las más llamativas, encuentra una planta adecuada para la luz, el espacio y el ritmo de tu hogar.',heroLink:'Explorar la colección',heroFoot:'Diez plantas de interior queridas. Esto acaba de empezar.',
    collectionEyebrow:'LA COLECCIÓN PLANTPAL',collectionTitle:'Encuentra tu próxima planta.',collectionText:'Diez plantas de interior para empezar. La colección seguirá creciendo.',countLabel:'plantas por descubrir',searchLabel:'Buscar plantas',searchPlaceholder:'Nombre común o científico…',clearSearch:'Borrar búsqueda',
    filters:{all:'Todas las plantas',easy:'Fáciles de cuidar',statement:'Plantas protagonistas',trailing:'Colgantes y trepadoras'},results:'{count} plantas encontradas',resultsOne:'1 planta encontrada',emptyTitle:'No se encontraron plantas',emptyText:'Prueba otro nombre o filtro.',reset:'Mostrar todas las plantas',
    bannerEyebrow:'CULTIVA CON CONFIANZA',bannerTitle:'¿Una planta nueva en casa?',bannerText:'Las condiciones de tu hogar importan más que un calendario fijo. Aprende a observar la luz, el sustrato y las hojas.',beginnerGuide:'Guía para principiantes',
    detailEyebrow:'CONOCE LA PLANTA',light:'Luz',water:'Riego',back:'Todas las plantas',careEyebrow:'NOTAS DE CUIDADO',careTitle:'Cómo ayudarla a crecer.',lightHeading:'Luz y ubicación',waterHeading:'Riego y drenaje',tipHeading:'Algo que recordar',fullGuide:'Leer la guía completa',furtherReading:'Más información:',sourceLabel:'Fuente de horticultura',asideEyebrow:'UN PEQUEÑO RECORDATORIO',asideText:'Un calendario de riego es solo el punto de partida. Revisa siempre el sustrato y las condiciones de tu hogar.',relatedEyebrow:'SIGUE EXPLORANDO',relatedTitle:'También pueden gustarte estas.',
    imageAlt:'Plantas de interior con la luz cálida de una ventana',cardAlt:'{name} ({scientific}) en una maceta de interior',detailAlt:'{name} ({scientific}) en una maceta de interior',cardLink:'Descubre {name}',metaIndexTitle:'Plantas de interior: conoce 10 especies populares',metaIndexDescription:'Conoce diez plantas de interior con imágenes originales y consejos prácticos sobre luz, riego y cuidado.',metaDetail:'Cuidados de {name}: luz, riego y consejos de cultivo',
  },
};

const lightKind: Record<string, LightKind> = {
  'Bright, indirect':'bright', 'Medium to bright, indirect':'medium', 'Low to bright, indirect':'low', 'Bright light':'sun',
};
const waterKind: Record<string, WaterKind> = {
  'Let the top layer dry':'top', 'Allow partial drying':'partial', 'Dry well between waterings':'dry', 'Keep evenly, lightly moist':'even', 'Water after the top dries':'top',
};

type CareText = {lightLabels:Record<LightKind,string>;waterLabels:Record<WaterKind,string>;lightAdvice:Record<LightKind,string>;waterAdvice:Record<WaterKind,string>};
export const careTranslations: Record<NewLocale,CareText> = {
  fr:{lightLabels:{bright:'Lumière vive indirecte',medium:'Lumière moyenne à vive',low:'Lumière faible à vive',sun:'Lumière vive'},waterLabels:{top:'Laisser sécher la surface',partial:'Laisser sécher en partie',dry:'Bien laisser sécher',even:'Garder légèrement humide'},lightAdvice:{bright:'Placez la plante près d’une fenêtre lumineuse, à l’abri du soleil brûlant de midi. Habituez-la progressivement à une lumière plus forte.',medium:'Choisissez une lumière indirecte moyenne à vive. Une pièce très sombre ralentit souvent la croissance.',low:'Elle tolère moins de lumière, mais pousse mieux avec une bonne lumière indirecte. Évitez une pièce sans lumière utile.',sun:'Offrez un emplacement très lumineux. Habituez progressivement la plante au soleil direct après un séjour à l’ombre.'},waterAdvice:{top:'Vérifiez le haut du terreau avant d’arroser. Lorsque celui-ci est sec, arrosez puis laissez bien égoutter.',partial:'Laissez sécher une partie du terreau, puis arrosez suffisamment pour humidifier les racines et laissez égoutter.',dry:'Attendez que le terreau ait bien séché, même en profondeur. Arrosez ensuite et évacuez l’eau en excès.',even:'Maintenez le terreau légèrement et régulièrement humide, sans le détremper. Si la plante flétrit dans un terreau humide, vérifiez les racines.'}},
  it:{lightLabels:{bright:'Luce intensa indiretta',medium:'Luce media o intensa',low:'Da poca luce a luce intensa',sun:'Luce intensa'},waterLabels:{top:'Lascia asciugare la superficie',partial:'Lascia asciugare in parte',dry:'Lascia asciugare bene',even:'Mantieni appena umido'},lightAdvice:{bright:'Metti la pianta vicino a una finestra luminosa, al riparo dal sole forte di mezzogiorno. Abituala gradualmente a una luce più intensa.',medium:'Scegli una luce indiretta da media a intensa. Una stanza molto buia spesso rallenta la crescita.',low:'Tollera meno luce, ma cresce meglio con una buona luce indiretta. Evita stanze prive di luce utile.',sun:'Scegli un luogo molto luminoso. Abitua gradualmente la pianta al sole diretto dopo un periodo all’ombra.'},waterAdvice:{top:'Controlla la parte superiore del terriccio. Quando è asciutta, annaffia e lascia scolare bene.',partial:'Lascia asciugare parte del terriccio, poi annaffia a fondo e fai defluire l’acqua in eccesso.',dry:'Aspetta che il terriccio sia ben asciutto, anche in profondità. Poi annaffia e lascia drenare.',even:'Mantieni il terriccio leggermente e uniformemente umido, senza saturarlo. Se la pianta appassisce con il terriccio bagnato, controlla le radici.'}},
  hi:{lightLabels:{bright:'तेज़ परोक्ष रोशनी',medium:'मध्यम से तेज़ रोशनी',low:'कम से तेज़ परोक्ष रोशनी',sun:'तेज़ रोशनी'},waterLabels:{top:'ऊपरी मिट्टी सूखने पर',partial:'मिट्टी कुछ सूखने पर',dry:'मिट्टी अच्छी तरह सूखने पर',even:'हल्की नमी बनाए रखें'},lightAdvice:{bright:'पौधे को रोशन खिड़की के पास रखें, लेकिन दोपहर की तेज़ धूप से बचाएँ। अधिक रोशनी की आदत धीरे-धीरे डालें।',medium:'मध्यम से तेज़ परोक्ष रोशनी चुनें। बहुत अँधेरी जगह पर वृद्धि धीमी हो सकती है।',low:'कम रोशनी सह लेता है, लेकिन अच्छी परोक्ष रोशनी में बेहतर बढ़ता है। पूरी तरह अँधेरी जगह से बचें।',sun:'बहुत रोशन जगह चुनें। छाया से लाए पौधे को सीधी धूप की आदत धीरे-धीरे डालें।'},waterAdvice:{top:'पानी देने से पहले मिट्टी की ऊपरी परत जाँचें। सूखने पर पानी दें और अतिरिक्त पानी निकलने दें।',partial:'मिट्टी का कुछ हिस्सा सूखने दें, फिर अच्छी तरह पानी दें और अतिरिक्त पानी निकाल दें।',dry:'मिट्टी को गहराई तक अच्छी तरह सूखने दें। फिर पानी दें और गमले में पानी जमा न होने दें।',even:'मिट्टी को हल्का और समान रूप से नम रखें, भीगा हुआ नहीं। गीली मिट्टी में पौधा मुरझाए तो जड़ें जाँचें।'}},
  zh:{lightLabels:{bright:'明亮散射光',medium:'中等至明亮散射光',low:'弱光至明亮散射光',sun:'充足光照'},waterLabels:{top:'表层干后浇水',partial:'盆土部分干后浇水',dry:'充分干燥后浇水',even:'保持微湿'},lightAdvice:{bright:'放在明亮窗边，避开正午强烈的直射阳光。移到更亮处时要逐步适应。',medium:'选择中等到明亮的散射光。过于昏暗的环境通常会减慢生长。',low:'它可以忍受较弱的光线，但在明亮散射光下长得更好。不要放在几乎无光的房间。',sun:'选择光线非常充足的位置。从阴处移来后，应逐步适应直射阳光。'},waterAdvice:{top:'浇水前检查盆土表层。表层干后浇透，并让多余的水排出。',partial:'等盆土部分干燥后再浇透，确保水分到达根部，并排出余水。',dry:'等盆土连深处都充分干燥后再浇水，不要让积水留在套盆里。',even:'让盆土保持轻微而均匀的湿润，避免长期湿透。若盆土仍湿而叶片下垂，应检查根系。'}},
  ar:{lightLabels:{bright:'ضوء ساطع غير مباشر',medium:'ضوء متوسط إلى ساطع',low:'ضوء ضعيف إلى ساطع',sun:'ضوء ساطع'},waterLabels:{top:'عندما يجف السطح',partial:'بعد جفاف جزء من التربة',dry:'بعد جفاف التربة جيدًا',even:'رطوبة خفيفة منتظمة'},lightAdvice:{bright:'ضع النبات قرب نافذة مضيئة بعيدًا عن شمس الظهيرة القوية. عوّده تدريجيًا على الضوء الأقوى.',medium:'اختر ضوءًا غير مباشر متوسطًا إلى ساطع. قد تبطئ الغرفة شديدة الظلمة نموه.',low:'يتحمّل الإضاءة الأضعف، لكنه ينمو بصورة أفضل في ضوء غير مباشر جيد. لا تضعه في غرفة شبه مظلمة.',sun:'اختر مكانًا شديد الإضاءة، وعرّض النبات للشمس المباشرة تدريجيًا بعد بقائه في الظل.'},waterAdvice:{top:'افحص الطبقة العليا من التربة قبل الري. عندما تجف، اسقِ النبات واترك الماء الزائد يتصرف.',partial:'دع جزءًا من التربة يجف، ثم اسقِ جيدًا حتى تصل الرطوبة إلى الجذور واترك الفائض يخرج.',dry:'انتظر حتى تجف التربة جيدًا، بما في ذلك عمق الأصيص. اسقِ بعدها ولا تترك ماءً راكدًا.',even:'حافظ على رطوبة خفيفة ومتجانسة من دون إغراق التربة. إذا ذبل النبات والتربة رطبة، افحص الجذور.'}},
  pt:{lightLabels:{bright:'Luz indireta intensa',medium:'Luz média a intensa',low:'Luz fraca a intensa',sun:'Luz intensa'},waterLabels:{top:'Regue após secar a superfície',partial:'Deixe secar parcialmente',dry:'Deixe secar bem',even:'Mantenha levemente úmido'},lightAdvice:{bright:'Coloque perto de uma janela iluminada, protegida do sol forte do meio-dia. Acostume a planta gradualmente a mais luz.',medium:'Escolha luz indireta de média a intensa. Um ambiente muito escuro costuma retardar o crescimento.',low:'Tolera menos luz, mas cresce melhor com boa luz indireta. Evite cômodos quase sem claridade.',sun:'Escolha um local muito iluminado. Depois de um período à sombra, acostume a planta ao sol direto aos poucos.'},waterAdvice:{top:'Confira a camada superior do substrato antes de regar. Quando secar, regue e deixe a água escorrer.',partial:'Deixe parte do substrato secar. Depois, regue bem e descarte a água que sair do vaso.',dry:'Espere o substrato secar bem, inclusive em profundidade. Regue e deixe o excesso escorrer.',even:'Mantenha o substrato levemente e uniformemente úmido, sem encharcar. Se a planta murchar com o solo molhado, examine as raízes.'}},
  ru:{lightLabels:{bright:'Яркий рассеянный свет',medium:'Умеренный или яркий свет',low:'От слабого до яркого света',sun:'Яркий свет'},waterLabels:{top:'После подсыхания верхнего слоя',partial:'После частичного подсыхания',dry:'После хорошего просыхания',even:'Поддерживать лёгкую влажность'},lightAdvice:{bright:'Поставьте растение рядом со светлым окном, защищая от жгучего полуденного солнца. К более яркому свету приучайте постепенно.',medium:'Выберите умеренный или яркий рассеянный свет. В очень тёмной комнате рост обычно замедляется.',low:'Растение переносит более слабый свет, но лучше растёт при хорошем рассеянном освещении. Не оставляйте его почти в темноте.',sun:'Выберите очень светлое место. После пребывания в тени приучайте растение к прямому солнцу постепенно.'},waterAdvice:{top:'Перед поливом проверьте верхний слой грунта. Когда он высохнет, полейте и дайте лишней воде стечь.',partial:'Дайте части грунта подсохнуть, затем тщательно полейте и слейте лишнюю воду.',dry:'Дождитесь хорошего просыхания грунта, в том числе в глубине горшка. После полива удалите лишнюю воду.',even:'Поддерживайте грунт слегка и равномерно влажным, не заливая его. Если растение вянет при влажном грунте, проверьте корни.'}},
  es:{lightLabels:{bright:'Luz indirecta brillante',medium:'Luz media a brillante',low:'De poca luz a luz brillante',sun:'Luz brillante'},waterLabels:{top:'Riega al secarse la superficie',partial:'Deja secar parcialmente',dry:'Deja secar bien',even:'Mantén una humedad ligera'},lightAdvice:{bright:'Coloca la planta cerca de una ventana luminosa, protegida del sol intenso del mediodía. Acostúmbrala gradualmente a una luz más fuerte.',medium:'Elige luz indirecta de media a brillante. Una habitación muy oscura suele ralentizar el crecimiento.',low:'Tolera menos luz, pero crece mejor con buena luz indirecta. Evita las habitaciones casi a oscuras.',sun:'Elige un lugar muy luminoso. Si venía de la sombra, acostúmbrala al sol directo poco a poco.'},waterAdvice:{top:'Revisa la capa superior del sustrato antes de regar. Cuando esté seca, riega y deja escurrir el exceso.',partial:'Deja que parte del sustrato se seque. Luego riega bien y permite que salga el agua sobrante.',dry:'Espera a que el sustrato se seque bien, también en profundidad. Después riega y elimina el exceso de agua.',even:'Mantén el sustrato ligeramente y uniformemente húmedo, sin encharcarlo. Si la planta decae con la tierra mojada, revisa las raíces.'}},
};

export const speciesTranslations: Record<NewLocale,Record<string,PlantTranslation>> = {
  fr:{
    monstera:['Monstera','Ses grandes feuilles découpées font du monstera une plante grimpante spectaculaire. Les jeunes feuilles peuvent rester entières.','Une jeune feuille sans découpes n’indique pas forcément un problème : l’âge et la lumière comptent aussi.'],
    pothos:['Pothos doré','Cette liane facile à vivre habille étagères et suspensions de feuilles en forme de cœur. Une bonne lumière favorise un feuillage plus dense.','Taillez juste au-dessus d’un nœud pour garder une belle forme ; une bouture a besoin d’un nœud pour s’enraciner.'],
    'snake-plant':['Langue de belle-mère','Ses feuilles verticales et graphiques conviennent aux petits espaces. Elle tolère une lumière modérée, mais pas l’obscurité totale.','Des feuilles molles avec un terreau humide invitent à vérifier les racines, pas à arroser davantage.'],
    'zz-plant':['Plante ZZ','Ses feuilles lustrées et ses tiges arquées apportent une élégance discrète. Ses rhizomes stockent de l’eau : la patience lui réussit.','Un mois sans nouvelle pousse est normal ; davantage d’eau n’accélérera pas sa croissance.'],
    'peace-lily':['Fleur de lune','Son feuillage vert foncé et ses spathes blanches donnent une touche de fraîcheur. Elle préfère une humidité plus régulière que bien d’autres plantes ici.','La partie blanche est une spathe entourant les vraies petites fleurs ; elle change naturellement de couleur en vieillissant.'],
    'rubber-plant':['Caoutchouc','Ses grandes feuilles brillantes créent une silhouette sculpturale. Ce ficus apprécie un emplacement stable et des changements progressifs.','Dépoussiérez doucement les feuilles avec un chiffon humide : profitez-en pour rechercher d’éventuels parasites.'],
    'spider-plant':['Chlorophytum','Ses feuilles rayées et arquées forment une fontaine de verdure, parfois accompagnée de jeunes plantules retombantes.','Les plantules bien développées peuvent être enracinées pour créer un nouveau pot.'],
    'fiddle-leaf-fig':['Figuier lyre','Ses grandes feuilles en forme de violon font de ce petit arbre un point focal. Il préfère une lumière et un emplacement réguliers.','Une feuille tombée invite à examiner les changements récents, la lumière et l’humidité des racines.'],
    'heartleaf-philodendron':['Philodendron à feuilles de cœur','Ses feuilles souples en forme de cœur retombent d’une étagère ou grimpent sur un support. Une place chaude et lumineuse garde les tiges fournies.','Taillez une tige dégarnie après un nœud pour encourager une forme plus dense.'],
    'aloe-vera':['Aloe vera','Cette succulente sculpturale stocke de l’eau dans ses feuilles. Sa rosette compacte convient à un rebord de fenêtre lumineux.','Des feuilles fermes et des racines saines comptent plus qu’un arrosage à date fixe.'],
  },
  it:{
    monstera:['Monstera','Le grandi foglie incise rendono la monstera una rampicante scenografica. Le foglie giovani possono essere ancora intere.','Una nuova foglia senza incisioni non è sempre un problema: contano anche età e luce.'],
    pothos:['Pothos dorato','Una pianta flessibile che addolcisce mensole e vasi sospesi con foglie a cuore. Con luce adatta cresce in modo più folto.','Taglia sopra un nodo per mantenere una forma ordinata; una talea ha bisogno di un nodo per radicare.'],
    'snake-plant':['Sansevieria','Le foglie rigide e verticali danno struttura anche agli spazi piccoli. Tollera meno luce, ma ha comunque bisogno di luminosità.','Foglie molli e terriccio umido richiedono un controllo delle radici, non altra acqua.'],
    'zz-plant':['Zamioculcas','Foglie lucide e steli arcuati portano equilibrio nella stanza. I rizomi sotterranei accumulano acqua: meglio non avere fretta.','Un mese senza nuovi germogli è normale; più acqua non accelera la crescita.'],
    'peace-lily':['Spatifillo','Foglie verde scuro e spate bianche creano un aspetto fresco ed elegante. Preferisce un’umidità più costante di molte altre piante.','La parte bianca è una spata intorno ai piccoli fiori veri; invecchiando cambia colore naturalmente.'],
    'rubber-plant':['Ficus elastica','Le grandi foglie lucide ne fanno una presenza scultorea. Questo ficus preferisce una posizione stabile e cambiamenti graduali.','Pulisci delicatamente le foglie con un panno umido: è anche il momento giusto per cercare parassiti.'],
    'spider-plant':['Falangio','Le foglie arcuate e striate formano una cascata verde, spesso con piccole nuove piante che pendono dagli steli.','Quando sono ben sviluppate, le piantine possono essere fatte radicare in un nuovo vaso.'],
    'fiddle-leaf-fig':['Ficus lyrata','Le grandi foglie a forma di violino fanno di questo alberello un punto focale. Ama luce e posizione costanti.','Una foglia caduta è un invito a controllare cambiamenti recenti, luce e umidità delle radici.'],
    'heartleaf-philodendron':['Filodendro a cuore','Le foglie morbide a cuore ricadono dalle mensole o salgono su un supporto. Una posizione calda e luminosa mantiene folti gli steli.','Pota uno stelo spoglio subito dopo un nodo per favorire una forma più piena.'],
    'aloe-vera':['Aloe vera','Una succulenta scultorea che conserva acqua nelle foglie. La rosetta compatta sta bene su un davanzale luminoso.','Foglie sode e radici sane contano più di un calendario settimanale di annaffiatura.'],
  },
  hi:{
    monstera:['मॉन्स्टेरा','गहरी कटी हुई बड़ी पत्तियाँ मॉन्स्टेरा को कमरे का आकर्षक चढ़ने वाला पौधा बनाती हैं। नई पत्तियाँ शुरू में बिना कटाव की हो सकती हैं।','नई पत्ती में कटाव न होना हमेशा समस्या नहीं है; उम्र और रोशनी भी मायने रखती हैं।'],
    pothos:['गोल्डन पोथोस','दिल के आकार की पत्तियों वाली यह बेल शेल्फ़ और लटकते गमलों को हराभरा बनाती है। अच्छी रोशनी में पत्तियाँ अधिक घनी होती हैं।','बेल को गाँठ के ऊपर काटें; नई जड़ बनाने के लिए कटिंग में गाँठ होना ज़रूरी है।'],
    'snake-plant':['स्नेक प्लांट','सीधी, तलवार जैसी पत्तियाँ छोटी जगहों को भी सुंदर बनाती हैं। यह कम रोशनी सह सकता है, लेकिन पूरी तरह अँधेरा नहीं।','गीली मिट्टी के साथ नरम पड़ती पत्तियाँ दिखें तो पानी बढ़ाने के बजाय जड़ें जाँचें।'],
    'zz-plant':['ज़ेडज़ेड प्लांट','चमकदार पत्तियाँ और मुड़े हुए डंठल कमरे को सधा हुआ रूप देते हैं। इसके भूमिगत राइज़ोम पानी जमा करते हैं।','एक महीने तक नई शाखा न आना सामान्य है; ज़्यादा पानी वृद्धि नहीं बढ़ाएगा।'],
    'peace-lily':['पीस लिली','गहरी हरी पत्तियाँ और सफ़ेद आवरण इसे कोमल, हरा-भरा रूप देते हैं। इसे कई दूसरे पौधों से अधिक स्थिर नमी पसंद है।','सफ़ेद हिस्सा असली छोटे फूलों के चारों ओर का आवरण है; उम्र के साथ उसका रंग बदलना सामान्य है।'],
    'rubber-plant':['रबर प्लांट','चौड़ी, चमकदार पत्तियाँ इसे कमरे का आकर्षक पौधा बनाती हैं। इस फाइकस को स्थिर जगह और धीरे-धीरे बदलाव पसंद हैं।','पत्तियों को नम कपड़े से हल्के से साफ़ करें और उसी समय कीटों की भी जाँच करें।'],
    'spider-plant':['स्पाइडर प्लांट','धारीदार, झुकी पत्तियाँ फव्वारे जैसी दिखती हैं और अक्सर इनसे छोटे नए पौधे लटकते हैं।','विकसित हो चुके छोटे पौधों की जड़ें बनाकर नया गमला तैयार किया जा सकता है।'],
    'fiddle-leaf-fig':['फिडल-लीफ़ फ़िग','वायलिन जैसी बड़ी पत्तियाँ इस छोटे इनडोर पेड़ को केंद्र बिंदु बनाती हैं। इसे स्थिर रोशनी और जगह पसंद है।','पत्ती गिरने पर हाल में हुए बदलाव, रोशनी और जड़ों की नमी जाँचें।'],
    'heartleaf-philodendron':['हार्टलीफ़ फिलोडेंड्रॉन','मुलायम दिलनुमा पत्तियाँ शेल्फ़ से लटकती हैं या सहारे पर चढ़ती हैं। गर्म और रोशन जगह बेल को घना रखती है।','लंबे, विरल तने को पत्ती की गाँठ के ठीक बाद काटें ताकि पौधा घना हो।'],
    'aloe-vera':['एलोवेरा','मोटी पत्तियों में पानी जमा करने वाला यह सुडौल रसीला पौधा रोशन खिड़की पर अच्छा लगता है।','सख़्त पत्तियाँ और स्वस्थ जड़ें तय साप्ताहिक सिंचाई से अधिक महत्वपूर्ण हैं।'],
  },
  zh:{
    monstera:['龟背竹','大而开裂的叶片让龟背竹成为醒目的攀援植物。幼株叶片可能仍是完整的。','新叶没有开裂不一定是问题；植株年龄和光照都会影响叶形。'],
    pothos:['绿萝','心形叶片垂落在架子或吊盆边，为房间添上柔和绿意。适当的光照有助于长得更茂密。','在茎节上方修剪能让株形更整齐；扦插枝条需要带茎节才能生根。'],
    'snake-plant':['虎皮兰','挺直如剑的叶片适合小空间。它能忍受较弱光线，但仍需要一定的光照。','盆土潮湿时叶片却变软倒伏，应检查根系，而不是继续浇水。'],
    'zz-plant':['金钱树','光亮的小叶和弯曲的茎干让空间显得沉静有序。地下根茎能储水，养护时要有耐心。','一个月没有新芽也很正常；多浇水并不能催促它生长。'],
    'peace-lily':['白掌','深绿叶片与白色佛焰苞相映，显得清新雅致。相比这里许多植物，它更喜欢稳定的水分。','白色部分是包围小花的佛焰苞；它随着成熟改变颜色是自然现象。'],
    'rubber-plant':['橡皮树','宽大光亮的叶片很有雕塑感。这种榕属植物喜欢位置稳定、环境变化缓慢。','用湿软布轻轻擦拭宽叶，也可以顺便检查有没有害虫。'],
    'spider-plant':['吊兰','条纹叶片向四周弯垂，像绿色喷泉，常有小株从长茎上悬挂下来。','小株长好后可以让它们生根，培育成一盆新吊兰。'],
    'fiddle-leaf-fig':['琴叶榕','大而像小提琴的叶片让这株室内小树成为视觉焦点。它喜欢稳定的光照和位置。','落叶时先检查最近的环境变化、光照和根部湿度，不要一次改变所有养护方式。'],
    'heartleaf-philodendron':['心叶蔓绿绒','柔软的心形叶片可以从架子上垂下，也能沿支架攀援。温暖明亮的位置有助于枝条长得茂密。','在茎节后修剪稀疏的枝条，可帮助植株保持丰满。'],
    'aloe-vera':['芦荟','这是一种叶片储水、造型分明的多肉植物。紧凑的莲座适合明亮的窗台。','叶片饱满、根系健康，比严格遵守每周浇水日程更重要。'],
  },
  ar:{
    monstera:['مونستيرا','تجعل أوراقها الكبيرة المشقوقة من المونستيرا نبتة متسلقة لافتة. قد تكون أوراقها الفتية كاملة بلا شقوق.','الورقة الجديدة غير المشقوقة ليست بالضرورة علامة مشكلة؛ فعمر النبات والضوء مهمان أيضًا.'],
    pothos:['بوتس ذهبي','تزيّن هذه النبتة المتدلية الرفوف والأصص المعلقة بأوراق على شكل قلب. يساعد الضوء المناسب على نموها بكثافة.','اقصص الساق فوق عقدة لتحافظ على شكل ممتلئ؛ تحتاج العقلة إلى عقدة لتكوين جذور.'],
    'snake-plant':['نبات الثعبان','تضفي أوراقه الطويلة المنتصبة طابعًا معماريًا حتى في المساحات الصغيرة. يتحمّل الضوء الضعيف لكنه لا يعيش في الظلام.','إذا أصبحت الأوراق لينة والتربة رطبة، افحص الجذور بدلًا من إضافة مزيد من الماء.'],
    'zz-plant':['نبات ZZ','تضفي أوراقه اللامعة وسيقانه المقوسة هدوءًا على المكان. تخزن جذاميره تحت التربة الماء، لذا يناسبه الصبر.','مرور شهر من دون نمو جديد أمر طبيعي؛ زيادة الماء لا تسرّع نموه.'],
    'peace-lily':['زنبق السلام','تمنحه أوراقه الخضراء الداكنة والقنابات البيضاء مظهرًا أنيقًا. يفضل رطوبة أكثر انتظامًا من نباتات كثيرة هنا.','الجزء الأبيض قنابة تحيط بالأزهار الصغيرة الحقيقية؛ يتغير لونها طبيعيًا مع تقدّمها في العمر.'],
    'rubber-plant':['نبات المطاط','تمنح أوراقه الكبيرة اللامعة الغرفة حضورًا مميزًا. يفضل هذا الفيكس مكانًا ثابتًا وتغييرات تدريجية.','امسح الأوراق برفق بقطعة قماش رطبة، واستغل الفرصة للبحث عن الآفات.'],
    'spider-plant':['نبات العنكبوت','تشكّل أوراقه المخططة المقوسة نافورة خضراء، وقد تتدلى منه نباتات صغيرة جديدة.','يمكن تجذير النباتات الصغيرة بعد أن تنمو بما يكفي وزراعتها في أصيص جديد.'],
    'fiddle-leaf-fig':['تين الكمان','تجعل أوراقه الكبيرة الشبيهة بالكمان من هذه الشجرة المنزلية نقطة جذب. يناسبها ثبات الضوء والمكان.','إذا سقطت ورقة، راجع التغييرات الأخيرة والضوء ورطوبة الجذور قبل تغيير كل شيء.'],
    'heartleaf-philodendron':['فيلودندرون قلبي','تتدلى أوراقه القلبية الناعمة من الرفوف أو تتسلق دعامة. يساعد المكان الدافئ والمضيء على كثافة الأغصان.','اقصص ساقًا طويلة قليلة الأوراق بعد عقدة ورقية لتشجيع نمو أكثر امتلاءً.'],
    'aloe-vera':['ألوفيرا','نبات عصاري ذو شكل مميز يخزن الماء في أوراقه السميكة. تناسب وردته المتراصة نافذة مضيئة.','صلابة الأوراق وصحة الجذور أهم من الالتزام بموعد ري أسبوعي ثابت.'],
  },
  pt:{
    monstera:['Costela-de-adão','As folhas grandes e recortadas fazem dela uma trepadeira marcante. Folhas jovens podem nascer inteiras.','Uma folha nova sem recortes não indica necessariamente um problema; idade e luz também influenciam.'],
    pothos:['Jiboia','Esta trepadeira versátil suaviza prateleiras e vasos suspensos com folhas em forma de coração. Boa luz favorece uma folhagem mais cheia.','Pode logo acima de um nó para manter a planta cheia; a muda precisa de um nó para enraizar.'],
    'snake-plant':['Espada-de-são-jorge','As folhas rígidas e eretas criam um visual marcante até em espaços pequenos. Tolera menos luz, mas não a escuridão completa.','Folhas moles com substrato úmido pedem uma inspeção das raízes, não mais água.'],
    'zz-plant':['Zamioculca','Folhas brilhantes e hastes arqueadas dão estrutura ao ambiente. Os rizomas subterrâneos guardam água: tenha paciência ao cuidar.','Um mês sem brotos novos é normal; regar mais não acelera o crescimento.'],
    'peace-lily':['Lírio-da-paz','Folhas verde-escuras e espatas brancas dão um ar elegante e fresco. Gosta de umidade mais constante que muitas outras plantas daqui.','A parte branca é uma espata ao redor das pequenas flores verdadeiras; sua cor muda naturalmente com o tempo.'],
    'rubber-plant':['Ficus-elástica','As folhas grandes e brilhantes fazem desta planta um destaque escultural. Esse ficus prefere local estável e mudanças graduais.','Limpe as folhas delicadamente com um pano úmido e aproveite para procurar pragas.'],
    'spider-plant':['Clorofito','As folhas listradas e arqueadas formam uma cascata verde, muitas vezes com mudinhas pendentes.','Mudinhas já desenvolvidas podem criar raízes e formar um novo vaso.'],
    'fiddle-leaf-fig':['Figueira-lira','As folhas grandes em forma de violino fazem desta pequena árvore um ponto focal. Ela prefere luz e localização constantes.','Uma folha que caiu é um sinal para revisar mudanças recentes, luz e umidade das raízes.'],
    'heartleaf-philodendron':['Filodendro-coração','As folhas macias em forma de coração pendem das prateleiras ou sobem por suportes. Um lugar quente e claro ajuda a manter a planta cheia.','Pode uma haste alongada logo após um nó para estimular uma forma mais densa.'],
    'aloe-vera':['Babosa','Essa suculenta de forma marcante guarda água nas folhas. Sua roseta compacta fica bem em uma janela iluminada.','Folhas firmes e raízes saudáveis importam mais do que um dia fixo para regar.'],
  },
  ru:{
    monstera:['Монстера','Крупные резные листья делают монстеру выразительной лианой. Молодые листья могут быть цельными.','Новый лист без прорезей не всегда говорит о проблеме: важны возраст растения и освещение.'],
    pothos:['Золотистый эпипремнум','Эта неприхотливая лиана украшает полки и подвесные кашпо сердцевидными листьями. При хорошем свете она растёт гуще.','Обрезайте побег над узлом, чтобы сохранить пышность; для укоренения черенку нужен узел.'],
    'snake-plant':['Сансевиерия','Прямые мечевидные листья украсят даже небольшое пространство. Растение переносит слабый свет, но не полную темноту.','Мягкие листья при влажном грунте — повод проверить корни, а не поливать ещё раз.'],
    'zz-plant':['Замиокулькас','Глянцевые листья и изогнутые стебли придают комнате спокойный вид. Подземные корневища запасают воду, поэтому спешить с поливом не стоит.','Месяц без новых побегов — нормальное явление; лишняя вода не ускорит рост.'],
    'peace-lily':['Спатифиллум','Тёмно-зелёные листья и белые покрывала соцветий создают нарядный вид. Ему нужна более равномерная влажность, чем многим другим растениям.','Белая часть — покрывало вокруг маленьких настоящих цветков; со временем оно естественно меняет цвет.'],
    'rubber-plant':['Фикус каучуконосный','Крупные блестящие листья создают выразительный силуэт. Этот фикус любит постоянное место и постепенные изменения.','Аккуратно протирайте листья влажной тканью и одновременно проверяйте их на вредителей.'],
    'spider-plant':['Хлорофитум','Узкие полосатые листья образуют зелёный фонтан, а на длинных побегах часто появляются молодые розетки.','Подросшие дочерние розетки можно укоренить и посадить в отдельный горшок.'],
    'fiddle-leaf-fig':['Фикус лировидный','Большие листья, напоминающие скрипку, превращают это комнатное деревце в центр внимания. Ему подходят стабильные свет и место.','При опадении листа проверьте недавние перемены, освещение и влажность у корней.'],
    'heartleaf-philodendron':['Филодендрон сердцелистный','Мягкие сердцевидные листья свисают с полок или поднимаются по опоре. В тёплом светлом месте побеги выглядят гуще.','Обрежьте вытянувшийся побег после листового узла, чтобы стимулировать более пышный рост.'],
    'aloe-vera':['Алоэ вера','Это выразительное суккулентное растение хранит воду в толстых листьях. Компактная розетка подходит для светлого подоконника.','Плотные листья и здоровые корни важнее строгого еженедельного графика полива.'],
  },
  es:{
    monstera:['Monstera','Sus grandes hojas recortadas hacen de la monstera una trepadora llamativa. Las hojas jóvenes pueden salir enteras.','Una hoja nueva sin cortes no siempre indica un problema; la edad y la luz también influyen.'],
    pothos:['Poto dorado','Esta enredadera versátil llena de hojas en forma de corazón las estanterías y macetas colgantes. Con buena luz crece más frondosa.','Poda por encima de un nudo para mantenerla compacta; un esqueje necesita un nudo para echar raíces.'],
    'snake-plant':['Lengua de suegra','Sus hojas firmes y verticales aportan estructura incluso a espacios pequeños. Tolera menos luz, pero no la oscuridad total.','Las hojas blandas con el sustrato húmedo piden revisar las raíces, no añadir más agua.'],
    'zz-plant':['Planta ZZ','Las hojas brillantes y los tallos arqueados aportan calma a la habitación. Sus rizomas subterráneos guardan agua: conviene tener paciencia.','Un mes sin brotes nuevos es normal; más agua no hará que crezca antes.'],
    'peace-lily':['Espatifilo','Las hojas verde oscuro y las espatas blancas le dan un aspecto fresco y elegante. Prefiere una humedad más constante que muchas otras plantas.','La parte blanca es una espata alrededor de las pequeñas flores verdaderas; cambia de color de forma natural al envejecer.'],
    'rubber-plant':['Ficus elástica','Sus hojas grandes y brillantes crean una silueta escultórica. Este ficus prefiere una ubicación estable y cambios graduales.','Limpia las hojas con un paño húmedo y aprovecha para comprobar si hay plagas.'],
    'spider-plant':['Cinta','Sus hojas rayadas y arqueadas forman una fuente verde, a menudo con pequeñas plantas colgantes.','Las plantitas desarrolladas pueden enraizar y empezar una maceta nueva.'],
    'fiddle-leaf-fig':['Ficus lira','Sus grandes hojas con forma de violín convierten a este arbolito en un punto de atención. Prefiere luz y ubicación constantes.','Si cae una hoja, revisa los cambios recientes, la luz y la humedad de las raíces.'],
    'heartleaf-philodendron':['Filodendro de hoja corazón','Sus hojas suaves en forma de corazón caen desde las estanterías o trepan por un soporte. Un lugar cálido y claro mantiene las guías frondosas.','Poda un tallo largo y poco poblado después de un nudo para favorecer una forma más llena.'],
    'aloe-vera':['Aloe vera','Esta suculenta escultural almacena agua en sus hojas. Su roseta compacta encaja en un alféizar luminoso.','Las hojas firmes y las raíces sanas importan más que un día fijo de riego cada semana.'],
  },
};

export function plantPrefix(locale:PlantLocale){return locale==='en'?'':`/${locale}`}
export function plantLang(locale:PlantLocale){return locale==='en'?'en':locale==='he'?'he-IL':packs[locale].lang}
export function plantAlternates(path:string){const languages:Record<string,string>={'en':SITE_URL+path,'he-IL':SITE_URL+'/he'+path};for(const code of newLocaleCodes)languages[packs[code].lang]=SITE_URL+'/'+code+path;languages['x-default']=SITE_URL+path;return languages}
export function localizedPlant(plant:Plant,locale:PlantLocale){
  if(locale==='en')return {name:plant.name,intro:plant.intro,tip:plant.tip,light:plant.light,water:plant.water,lightCare:plant.lightCare,waterCare:plant.waterCare};
  if(locale==='he')return {name:plant.nameHe,intro:plant.introHe,tip:plant.tipHe,light:plant.lightHe,water:plant.waterHe,lightCare:plant.lightCareHe,waterCare:plant.waterCareHe};
  const translation=speciesTranslations[locale][plant.slug];
  if(!translation)throw new Error(`Missing ${locale} translation for ${plant.slug}`);
  const care=careTranslations[locale];
  const light=lightKind[plant.light],water=waterKind[plant.water];
  if(!light||!water)throw new Error(`Missing care type for ${plant.slug}`);
  return {name:translation[0],intro:translation[1],tip:translation[2],light:care.lightLabels[light],water:care.waterLabels[water],lightCare:care.lightAdvice[light],waterCare:care.waterAdvice[water]};
}

export function plantSearchText(plant:Plant,locale:PlantLocale){const local=localizedPlant(plant,locale);return `${local.name} ${plant.name} ${plant.nameHe} ${plant.scientific}`.toLocaleLowerCase(plantLang(locale))}
export function validatePlantTranslations(){for(const locale of newLocaleCodes){const missing=plants.filter(plant=>!speciesTranslations[locale][plant.slug]);if(missing.length)throw new Error(`Missing ${locale} plants: ${missing.map(plant=>plant.slug).join(', ')}`)}}
export function template(text:string,values:Record<string,string|number>){return text.replace(/\{(\w+)\}/g,(_,key:string)=>String(values[key]??''))}
