import {section as s,type Article} from './content';
const make=(slug:string,title:string,description:string,takeaway:string,sections:Article['sections'],related:string[]):Article=>({slug,title,description,takeaway,sections,related,category:'plant-guides',sources:[],author:'PlantPal',status:'published',publishedAt:'2026-09-22T20:00:00.000Z',updatedAt:'2026-09-22T20:00:00.000Z'});
export const plantArticles:Article[]=[
make('monstera-deliciosa-care','Monstera deliciosa care: bright light, an airy mix, and a pole to climb','Grow Monstera deliciosa well: 10,000–20,000 lux, water when the top 3–5 cm is dry, a chunky bark mix, a moss pole, and the conditions that trigger split leaves.','Light drives both growth and splits: give a monstera 10,000–20,000 lux of bright indirect light, and water only once the top 3–5 cm (1–2 in) of mix has dried.',[
s('A forest climber, and what that means indoors','Monstera deliciosa (Araceae) is native to the humid forests of southern Mexico and Central America. It is a hemiepiphyte: it starts on the forest floor, then climbs tree trunks toward brighter light, anchoring itself with thick aerial roots. Everything useful about its care follows from that habit: dappled rather than baking light, a root zone that breathes, and something to climb.\n\nThe famous splits and holes (fenestrations) are an adult trait. Young plants make entire, heart-shaped leaves, and fenestration usually starts once leaves pass roughly 30 cm (12 in) and the plant receives strong light. A monstera sprawling unsupported in a dim corner can stay in juvenile mode for years. If you want split leaves, give it more light and a pole, not more fertilizer.'),
s('Light, temperature, and humidity','Target 10,000–20,000 lux at leaf height: within about 1 m of an east or west window, or 1–2 m back from a bright south window (north in the Southern Hemisphere). Two to three hours of morning sun is welcome; hot afternoon sun through glass bleaches and scorches a plant that has not been acclimated, so step it up over 1–2 weeks. Below about 2,500 lux, growth stalls, stems stretch, and new leaves come in smaller and uncut.\n\nKeep it at 18–27 °C (65–80 °F) with a floor of about 12 °C (54 °F); leaves pressed against cold winter glass develop dark, water-soaked patches. It copes well at 40–60% relative humidity. In heated winter air, often 20–35% RH, a humidifier is the only method that reliably helps; misting lifts humidity for minutes and a pebble tray barely registers.'),
s('Watering, potting mix, and feeding','Water when the top 3–5 cm (1–2 in), roughly the top quarter to third of the pot, is dry. Then water thoroughly until 10–20% runs from the drainage holes and empty the cachepot within 30 minutes. In a bright room in summer that may be weekly; in winter, often every 2–3 weeks. Check with a finger or a wooden skewer, not the calendar.\n\nThe roots evolved to cling to bark in open air, so they suffocate and rot in dense, waterlogged media. A good starting blend is 1 part quality potting mix, 1 part 6–20 mm pine or orchid bark, and 1 part perlite or pumice by volume. Repot every 2–3 years in spring, going only 2–5 cm (1–2 in) wider, or 5–8 cm for a large specimen; an oversized pot holds a cold, wet core the roots cannot use.\n\nFrom spring to late summer, feed every 2–4 weeks with a balanced or nitrogen-leaning foliage fertilizer at half to full label strength. Stop in winter unless the plant is under grow lights and still producing leaves.'),
s('Poles, pruning, and propagation','A moss or coir pole is the single biggest upgrade for a maturing monstera. Set it at repotting time, tie the main stem (never the leaf stalks) loosely with soft ties, and guide aerial roots onto the pole. A damp pole encourages roots to grip, and a climbing stem produces larger, more fenestrated leaves than a sprawling one. Aerial roots that miss the pole are normal; tuck them into the pot or trim the odd one.\n\nTo propagate, cut a stem section with at least one node, ideally carrying an aerial root and a leaf. Root it in water or moist perlite at 20–25 °C (68–77 °F) in bright indirect light; roots typically show in 3–6 weeks. A leaf and stalk without a node may root but will never produce a new shoot.'),
s('At a glance, and what goes wrong','Yellowing lower leaves with mix that stays wet for more than a week point to root hypoxia and rot: unpot, cut away brown, mushy roots, and repot into fresh, chunky mix. Crisp brown edges with a light, dry pot mean it is drying out too far between waterings. Fine pale stippling, sometimes with webbing on the undersides, means spider mites, which thrive in warm, dry air: shower the foliage and apply insecticidal soap every 5–7 days for at least three rounds.\n\nAll parts contain calcium oxalate raphides, and chewing causes painful mouth and throat irritation. The ASPCA lists monstera as toxic to cats and dogs, so keep it out of reach of pets and small children.',[
'Light: 10,000–20,000 lux; morning sun is fine',
'Water: when the top 3–5 cm (top quarter to third) is dry',
'Temperature: 18–27 °C (65–80 °F), minimum about 12 °C',
'Humidity: 40–60% RH; humidifier in winter',
'Mix: 1 : 1 : 1 potting mix, bark, perlite or pumice',
'Repot: every 2–3 years in spring, 2–5 cm wider'
])
],['aroid-potting-mix','bright-indirect-light','yellow-leaves-houseplants']),
make('pothos-care','Pothos care: light, watering, and pruning for full, leafy vines','Grow a full pothos: 2,500–15,000 lux (more for variegated cultivars), water when the top quarter of the mix dries, prune above nodes, and root single-node cuttings.','Pothos survives low light but only fills out above about 5,000 lux; water when the top 3–5 cm is dry and cut vines back before they go bare at the top.',[
s('A giant climber living a trailing life','Pothos (Epipremnum aureum, Araceae) comes from Mo’orea in French Polynesia and has naturalized across the tropics. In the wild it climbs tree trunks and produces deeply split leaves more than 60 cm long. Indoors, hanging from a shelf, it never gets the climbing and light cues that trigger that adult form, so it stays in its small-leaved juvenile stage.\n\nThat has two practical consequences. First, light and support shape the plant far more than fertilizer does: a vine trained up a moss pole in good light makes noticeably bigger leaves than one dangling downward. Second, trailing stems keep extending at the tip while older sections shed leaves, so pruning is part of routine care, not a rescue job.'),
s('Light by cultivar','Pothos tolerates 1,000–2,500 lux, which is why it survives in offices, but at that level it grows slowly and stretches out with long bare gaps between leaves. For full growth, aim higher; the more white or cream in the leaf, the less chlorophyll it has, and the more light it needs to keep pace.\n\nHeavily variegated plants in dim spots push greener new leaves and grow very slowly. Hot afternoon sun through glass, on the other hand, scorches pale tissue first. A few hours of east-window morning sun suits every cultivar. If you are unsure what a spot actually delivers, a light meter such as the one in PlantPal gives you a reading to compare against these ranges.',[
'‘Jade’ and other all-green forms: 2,500–10,000 lux, tolerates less',
'‘Golden’ and ‘Neon’: 5,000–15,000 lux',
'‘Marble Queen’, ‘Manjula’, ‘Snow Queen’: 10,000–20,000 lux, bright indirect',
'All cultivars: avoid unfiltered afternoon sun through glass'
]),
s('Watering, mix, and temperature','Water when the top 3–5 cm (1–2 in), about the top quarter of the pot, has dried, then water until 10–20% drains out and empty the saucer. Hanging baskets near ceilings dry faster because warm air collects there; check them twice as often as floor-level pots. A thirsty pothos signals clearly: leaves turn soft and slightly limp, and they firm up within hours of watering. A plant that droops while the pot is still heavy has a root problem, not a thirst problem.\n\nAny quality indoor potting mix with 20–30% added perlite works; an aroid bark mix works too. Repot every 1–2 years in spring when roots circle the pot, moving only 2–5 cm wider. Feed every 2–4 weeks from spring to late summer with a nitrogen-leaning foliage fertilizer, such as a 3-1-2 ratio, at half strength.\n\nKeep it at 18–29 °C (65–85 °F) and above 12–15 °C (54–59 °F). Humidity of 40–60% is ideal, though pothos tolerates typical dry winter air better than most aroids.'),
s('Pruning and single-node propagation','Cut vines about 1 cm above a node, the bump where a leaf joins the stem. The node just behind the cut, and often the next one back, will break into new shoots, turning one long strand into two or three. Pruning a few vines each spring keeps the crown of the pot leafy instead of bald.\n\nEvery node carries a small brown aerial-root nub, and that is where new roots emerge. Cut the trimmings into single-node pieces, each with one leaf and 1–2 cm of stem, and root them in water or moist perlite at 20–25 °C (68–77 °F). Roots appear in 2–4 weeks. Once they reach 3–5 cm, plant three to five cuttings back into the parent pot to fill a thin top.'),
s('Troubleshooting and pet safety','One yellow leaf at the base of an old vine is normal aging. Several yellowing at once, with wet mix, means overwatering and early root rot: let the pot dry to half its depth and check that roots are white and firm, not brown and slimy. Yellow-brown crisp patches with a dry pot mean the reverse.\n\nWhite, cottony clusters in leaf axils and along stems are mealybugs. Wipe them off with a cotton swab dipped in 70% isopropyl alcohol, then follow up with insecticidal soap every 7 days until no new ones appear.\n\nPothos contains insoluble calcium oxalate crystals. The ASPCA lists it as toxic to cats and dogs; chewing causes drooling, mouth pain, and vomiting. Hang trailing vines well above the reach of pets.')
],['bright-indirect-light','propagating-pothos','how-to-water-houseplants']),
make('snake-plant-care','Snake plant care: CAM, deep drying, and how to prevent base rot','Snake plant care from a grower: why CAM makes it drought-proof, watering only when 75–100% of the mix is dry, gritty soil, a 10 °C floor, and how to stop base rot.','Water a snake plant only when the mix is dry through at least three quarters of the pot, usually every 2–3 weeks in summer and 3–6 weeks in winter; rot kills far more of them than drought.',[
s('Built for drought: CAM and rhizomes','The snake plant (Dracaena trifasciata, formerly Sansevieria trifasciata, Asparagaceae) is native to dry tropical West Africa, from Nigeria east to the Congo. It uses CAM photosynthesis: it opens its stomata at night, stores carbon dioxide as malic acid, and keeps its stomata closed through the heat of the day. That cuts water loss dramatically compared with ordinary foliage plants.\n\nWater is also stored in the thick leaves and the creeping underground rhizomes. The consequence indoors is simple: the plant uses very little water, especially in low light, and its roots are adapted to soil that dries completely. Constantly damp mix starves them of oxygen, and rot at the base is the number-one killer of snake plants.'),
s('Light and temperature','It tolerates 500–2,500 lux, which makes it one of the few plants that holds its looks in a dim hallway, but at that level it barely grows and uses almost no water. Growth, leaf thickness, and the yellow margins of ‘Laurentii’ are best at 5,000–20,000 lux. Once acclimated over 1–2 weeks, it accepts several hours of direct sun.\n\nKeep it at 18–29 °C (65–85 °F) with a floor of about 10 °C (50 °F). The dangerous combination is cold plus wet: leaves on a chilled plant in damp mix develop soft, water-soaked patches that turn to mush. Humidity is not a concern; ordinary indoor air at 30–50% RH suits it well.'),
s('Watering by depth, not by date','Water only when the mix is dry through 75–100% of the pot. Push a wooden skewer to the bottom and wait ten minutes; if it comes out clean and dry, water. Pot weight is an even faster check once you know the dry weight. Typical intervals are 2–3 weeks in a bright summer spot and 3–6 weeks in winter.\n\nWater the mix around the rosette, not into its center; water sitting in leaf bases starts rot. Water thoroughly until it drains, or bottom-soak for 10–20 minutes, then empty the saucer completely.\n\nUse a succulent mix with 40–60% mineral grit such as pumice or perlite. Terracotta helps the mix dry evenly and adds weight to balance tall leaves. Snake plants tolerate crowding, so repot only every 2–4 years, or when rhizomes deform the nursery pot, and only 2–5 cm wider. Feed two or three times between spring and late summer at half strength.'),
s('Division and leaf cuttings','Division in spring is the quickest route to a new plant. Knock the plant out, cut through the rhizome with a clean knife so each piece has two to three leaves and its own roots, let the cuts dry for a day, then pot into dry gritty mix and wait a week before watering.\n\nLeaf cuttings also work but are slow. Cut a leaf into 5–8 cm sections, keep track of which end was down, let them callus for 1–3 days, and insert the lower end 2 cm into barely damp mix. Roots form in 4–8 weeks, pups in several months. Leaf cuttings of ‘Laurentii’ lose the yellow margin, because the variegation is only in the outer tissue layers; divide it to keep the stripe.'),
s('Diagnosing the common problems','Most snake plant symptoms trace back to water, so check the mix before acting. Mealybugs, which hide in the leaf bases, are the main pest worth inspecting for. Remember that a snake plant grows slowly, so any fix takes weeks to show in new leaves.\n\nThe plant contains saponins rather than the oxalate crystals of aroids. The ASPCA lists it as toxic to cats and dogs; eating it causes nausea, vomiting, and diarrhea.',[
'Soft, translucent, yellowing base with a sour smell: rot; cut above healthy tissue and reroot the leaf',
'Wrinkled, curling leaves with bone-dry mix: thirst; water thoroughly',
'Wrinkled leaves with wet mix: roots already dead; unpot and inspect',
'Pale or brown scorched patches after a move into sun: sunburn',
'Floppy, leaning leaves: too little light, usually with overwatering'
])
],['low-light-houseplants','overwatering-vs-underwatering','terracotta-vs-plastic-pots']),
make('zz-plant-care','ZZ plant care: rhizomes, flexible light, and very little water','ZZ plant care: how its potato-like rhizomes store water, when to water (mix 75–100% dry), a 10 °C floor, light from 500 to 15,000 lux, and slow leaflet propagation.','Treat the rhizomes as the plant’s water tank: water a ZZ only when the mix is dry through most of the pot, which in winter can mean once every 4–6 weeks.',[
s('A drought specialist from East Africa','Zamioculcas zamiifolia (Araceae) grows wild in eastern Africa, from Kenya south to South Africa, in places with a long dry season. It survives drought on potato-like underground rhizomes and swollen stalk bases that store water and starch. In a severe dry spell it drops its leaflets and waits it out underground.\n\nWhat look like branching stems are single compound leaves rising straight from the rhizome, each carrying glossy leaflets. New ones arrive in flushes, often several at once, followed by months of apparent inactivity. Both traits point the same way: a ZZ needs far less water than its size suggests, and a quiet period is not a problem to be fixed.'),
s('Light and temperature','A ZZ survives at 500–1,000 lux in an office under ceiling lights, which is why it is so popular. It will not grow much there. At 5,000–15,000 lux, such as near an east window or a few metres from a south window, it pushes more and sturdier flushes. Unfiltered afternoon sun yellows and scorches the leaflets.\n\nIn weak or one-sided light the stems lean and can flop; give the pot a quarter turn each month. Keep it at 18–27 °C (65–80 °F). It tolerates down to about 10 °C (50 °F) if the mix is dry, and ordinary indoor humidity of 30–60% is fine.'),
s('Watering the rhizome, not the leaves','Water only when the mix is dry through 75–100% of the pot. In summer that is typically every 2–4 weeks; in winter, every 4–6 weeks. A skewer pushed to the bottom tells you more than the surface does. When you water, soak the whole root ball until it drains and never leave water standing in a cachepot.\n\nUse a succulent mix, or potting mix with 40–50% pumice or perlite. Rhizomes eventually swell enough to bulge or split plastic nursery pots, which is the usual signal to repot, every 2–3 years in spring. Go 2–5 cm wider and keep the rhizome tops just below the surface, at the same depth as before. Feed two or three times between spring and late summer with a balanced fertilizer at half strength.'),
s('Propagation: patience required','Division is fastest. At repotting, pull or cut the rhizome clump into sections, each with at least one stem and its own roots, and pot them into dry mix. Wait about a week before the first watering so any damaged tissue can seal.\n\nSingle leaflets root too. Push the base of a leaflet 1 cm into damp gritty mix or stand it in water; it forms roots and a small rhizome over 1–3 months, but the first new stem often takes 6–12 months. Whole stem cuttings root faster and are worth trying from any stem broken during repotting.'),
s('Warning signs and safety','The one serious risk to a ZZ is overwatering, and it shows in a predictable way. Yellowing on several stems at once, with mix that has stayed wet, means the rhizomes are rotting: unpot, cut back to firm, pale tissue, let the cuts dry, and replant in dry mix. A single older stem yellowing while the rest stays glossy is normal turnover. Heavy leaflet drop with a bone-dry pot is drought or cold; leaning, stretched stems mean too little light.\n\nZZ contains calcium oxalate crystals. The ASPCA lists it as toxic to cats and dogs, and the sap can irritate skin, so wear gloves when dividing. A PlantPal reminder works well here, since most checks end with deciding not to water today.',[
'Light: tolerates 500–1,000 lux; grows best at 5,000–15,000 lux',
'Water: when 75–100% of the mix is dry; every 4–6 weeks in winter',
'Temperature: 18–27 °C, minimum about 10 °C when dry',
'Mix: potting mix with 40–50% pumice or perlite',
'Repot: every 2–3 years, when rhizomes crowd the pot'
])
],['low-light-houseplants','snake-plant-care','root-rot-houseplants']),
make('peace-lily-care','Peace lily care: even moisture, clean water, and more flowers','Peace lily care: water when the top 1–2 cm dries, give 5,000–15,000 lux for flowers, keep it above 15 °C, and fix brown tips caused by salts, fluoride, or wilting.','Water a peace lily when the top 1–2 cm (about ½ in) of mix is dry, before it wilts; every dramatic collapse costs it leaf tips and older leaves.',[
s('A plant of wet forest floors','Peace lilies (Spathiphyllum wallisii and its hybrids, Araceae) grow in the shaded understory of tropical American rainforests, from Colombia to Venezuela, often in constantly moist soil along streams. Their roots are finer and less drought-tolerant than those of climbing aroids such as monstera, and the plant has no water-storing rhizome to fall back on.\n\nThat explains the care profile: steadier moisture than most houseplants, shade tolerance for the leaves, and a real need for more light if you want flowers. It also explains why a peace lily collapses so theatrically when it dries out. Its thin leaves lose turgor fast.'),
s('Light for leaves versus light for flowers','The foliage stays healthy at 2,500–5,000 lux, but flowering needs 5,000–15,000 lux, roughly 1–2 m from an east window or further back from a south one. Direct sun through glass bleaches the leaves to a yellow-white and scorches patches.\n\nThe white “flower” is a spathe, a modified bract wrapped around the spadix that carries the tiny true flowers. It turns green as it ages; cut the stalk at its base when it browns. Many nursery plants are brought into bloom on schedule with a growth regulator, so a full flush in the shop followed by months without flowers at home is normal. Good light, not extra fertilizer, brings them back.\n\nKeep it at 18–27 °C (65–80 °F) with a floor of about 15 °C (59 °F); cold drafts and temperatures near 10 °C cause dark, damaged patches. Humidity of 40–60% keeps tips cleaner.'),
s('Watering: catch it before the wilt','Water when the top 1–2 cm of mix is dry, which in a warm room can be every 4–7 days. Lift the pot to learn its weight when it needs water. A wilted peace lily usually recovers within hours of watering, but each collapse kills root tips and leaf margins, which shows up days later as yellow lower leaves and brown tips.\n\nIf the peat has dried and shrunk from the pot wall, water runs straight past it; bottom-soak for 10–30 minutes until the surface darkens, then drain. A plant that droops while the mix is still wet has damaged roots, and more water makes it worse.\n\nUse a peat- or coir-based potting mix with 20–30% perlite. Peace lilies grow fast and soon become root-bound, drying out within days; repot every 1–2 years in spring, 2–5 cm wider, and divide crowded clumps at the same time. Each division needs its own crown, roots, and at least three leaves.'),
s('Brown tips: salts, fluoride, and feeding','Peace lilies are sensitive to dissolved salts and fluoride, and both show up as brown leaf tips. Fertilizer is the most common cause. Feed every 4–6 weeks from spring to late summer at half label strength; more feed does not produce more flowers.\n\nWork through this checklist when tips brown, and remember that damaged tissue will not turn green again. Judge progress on new leaves.',[
'Wilting between waterings: water at the 1–2 cm mark, not at the collapse',
'Salt build-up: white crust on the pot or mix surface; leach with 2–3× the pot volume of water',
'Fluoridated or softened tap water: switch to rainwater, distilled, or RO water',
'Overfeeding: drop to half strength every 4–6 weeks',
'Dry winter air: keep RH above 40% with a humidifier'
]),
s('Pests and pet safety','Constantly moist mix makes peace lilies a favorite of fungus gnats. Yellow sticky cards show the problem, and a BTi drench every 5–7 days for 3–4 cycles clears the larvae without letting the plant dry out. In dry air, check the leaf undersides for spider mites; in leaf bases, look for mealybugs.\n\nThe peace lily is not a true lily and does not cause the kidney failure that Lilium species do in cats. It does contain calcium oxalate crystals, and the ASPCA lists it as toxic to cats and dogs; chewing causes mouth pain, drooling, and difficulty swallowing.')
],['how-to-water-houseplants','brown-leaf-tips','bright-indirect-light']),
make('rubber-plant-care','Rubber plant care: bright light, steady conditions, and branching','Ficus elastica care: 10,000–20,000 lux, water when the top 3–5 cm is dry, stay above 12 °C, and prune or notch to make it branch, plus how to diagnose leaf drop.','A rubber plant rewards consistency: at least 10,000 lux of bright light, water when the top quarter of the mix is dry, and no sudden moves, drafts, or nights below 12 °C.',[
s('A tropical fig tree in a living room','Ficus elastica (Moraceae) is native to the monsoon forests of northeastern India, through Myanmar, to Malaysia and Indonesia. In the wild it becomes a 30 m tree, often starting life on another tree and sending down aerial roots. Its thick, waxy leaves are built for bright canopy light, and the milky latex that gives it its name seals wounds.\n\nIndoors it tends to grow as a single straight stem, because the growing tip suppresses the buds below it. Like most figs, it reacts to sudden change by shedding leaves. Three rules follow: give it strong light, keep conditions steady, and prune if you want a bushier shape.'),
s('Light, temperature, and stability','Aim for 10,000–20,000 lux: close to an east or west window, or 1–2 m back from a south one. Once acclimated over 1–2 weeks, it handles a few hours of morning or winter sun. The variegated cultivars ‘Tineke’ and ‘Ruby’ need the top of that range to keep their cream and pink; in low light their new leaves come in greener. Below about 2,500 lux, any rubber plant stretches, makes smaller leaves, and drops its lowest ones.\n\nKeep it at 18–29 °C (65–85 °F) and above 12 °C (54 °F). Cold drafts from an opened door, air conditioning, or a winter window cause sudden leaf drop, and so does the heat blast from a radiator. Ordinary indoor humidity of 40–60% suits it. Choose its spot carefully and then leave it there; a plant that loses a few leaves after a move needs time, not a new watering plan.'),
s('Watering, mix, and feeding','Water when the top 3–5 cm (1–2 in), roughly the top quarter to third of the pot, is dry. In a large floor pot, push a skewer 10–15 cm deep, because the surface dries long before the core. Water until 10–20% drains and empty the saucer within 30 minutes. Clean the leaves with a damp cloth every month or two; dust cuts the light they receive, and leaf-shine products clog the surface.\n\nUse quality potting mix with 25–30% perlite or fine pine bark, in a heavy pot that will not tip as the plant grows. Repot every 2–3 years in spring, 2–5 cm wider, or 5–8 cm for a large specimen. Once it is in a pot over 30 cm, replace the top 3–5 cm of mix each spring instead. Feed every 2–4 weeks from spring to late summer with a nitrogen-leaning foliage fertilizer such as a 3-1-2 ratio.'),
s('Pruning, notching, and propagation','Cutting the top off about 1 cm above a node in spring removes the hormonal brake from the buds below, and one to three of them will break into branches. Notching, a shallow 2–3 mm cut into the stem just above a dormant bud, interrupts that signal locally and can wake a single bud without removing the top. Wear gloves: the latex irritates skin and eyes. A damp paper towel pressed on the cut stops the bleeding.\n\nTip cuttings 10–15 cm long with two or three leaves root in water or moist perlite at 22–27 °C (72–81 °F) in 3–6 weeks. For thick stems, air layering works better: wound the stem, wrap it in moist sphagnum and plastic, and roots form in 4–8 weeks.'),
s('Diagnosing leaf drop and other problems','Leaf drop is the symptom owners notice first, and the pattern tells you the cause. Look at which leaves fall, whether they are green or yellow, and how wet the mix is, then change one thing at a time. A plant that has lost leaves from the base up will not regrow them there; pruning is the way to get new growth lower down.\n\nThe ASPCA lists the rubber plant as toxic to cats and dogs. The latex irritates skin and eyes, and chewing causes vomiting and drooling, so keep the plant and its prunings away from pets and children.',[
'Healthy green leaves dropping suddenly: shock from cold, a draft, or a move',
'Lower leaves yellowing, then dropping, with wet mix: overwatering and root damage',
'Lower leaves curling and dropping with a dry pot: underwatering',
'Brown bumps on stems and midribs, sticky honeydew: scale; treat with horticultural oil',
'Small corky bumps on leaf undersides: edema from irregular watering in cool conditions'
])
],['cleaning-houseplant-leaves','repotting-houseplants','overwatering-vs-underwatering']),
];
