import {section as s,type Article} from './content';
const make=(slug:string,title:string,description:string,takeaway:string,sections:Article['sections'],related:string[]):Article=>({slug,title,description,takeaway,sections,related,category:'plant-guides',sources:[],author:'PlantPal',status:'published',publishedAt:'2026-09-22T20:00:00.000Z',updatedAt:'2026-09-22T20:00:00.000Z'});
export const plantArticles:Article[]=[
make('monstera-deliciosa-care','Monstera deliciosa care: light, watering, and room to climb','Help your monstera grow with suitable light, an airy potting mix, thoughtful watering, and support for its climbing habit.','Give a monstera good indirect light, check moisture below the surface, and provide space and support as it grows.',[
s('Choose light that supports strong growth','Monstera deliciosa is known for large leaves with splits and holes, but young plants often begin with smaller, uncut leaves. Maturity, growing conditions, and the individual plant influence leaf development. Do not assume one unsplit leaf means something is wrong.\n\nChoose a bright location protected from sudden, intense sun exposure. A plant raised in dim conditions needs gradual adjustment before receiving stronger light. Keep the leaves away from cold glass and leave enough room to inspect both sides of the foliage.'),
s('Let the root environment guide watering','Use a container with drainage and a mix that holds moisture without compacting into a dense, constantly wet mass. Check below the surface before watering and allow part of the upper mix to dry. The depth and timing depend on the pot and conditions.\n\nWhen water is needed, wet the root ball evenly and let excess escape. Empty any cover pot. A large monstera in a dim room may use water much more slowly than its dramatic foliage suggests, especially after a move or seasonal change.'),
s('Support the stem without damaging the plant','As a climbing plant grows, a stable support can help organize its weight and direction. Attach the main stem gently with ties that do not cut into it. Avoid fastening leaf stalks rigidly, since leaves need room to orient toward light.\n\nAerial roots are part of the plant’s growth habit. Guide them where practical rather than treating every one as a defect. Install or adjust support carefully to avoid unnecessary root disturbance. Repot only when the root ball or medium gives you a reason.'),
s('Read changes in context','Several yellowing leaves alongside wet mix deserve a root and watering check. Pale or scorched patches after a sudden move toward the window suggest exposure stress. Inspect undersides for pests before attributing all damage to humidity.\n\nFeed an established, growing plant with an appropriate product according to its label, accounting for fertilizer in the mix. Keep the plant out of reach of pets and children who may chew it; monstera tissue can irritate the mouth. In PlantPal, record its location, care needs, and watering checks as the plant grows.')
],['aroid-potting-mix','bright-indirect-light','yellow-leaves-houseplants']),
make('pothos-care','Pothos care: a practical guide to fuller, healthier vines','Care for pothos with the right light, moisture checks, pruning, and node-based propagation for a manageable indoor vine.','Pothos is forgiving, but it grows best with usable light and a root ball that does not stay constantly wet.',[
s('Find a location beyond mere survival','Pothos, commonly sold as Epipremnum aureum, tolerates a range of indoor conditions. Green forms may cope with less light than strongly variegated ones, but a dim corner can mean slow growth and long gaps between leaves. Bright indirect light is a useful starting point.\n\nObserve the plant rather than chasing a perfect label. If new leaves become smaller and stems stretch, review the light. Introduce stronger exposure gradually and protect a shade-grown plant from a sudden hot sunbeam.'),
s('Water the pot, not the length of the vines','Long vines do not tell you how wet the root ball is. Check the medium and pot weight before watering. Allow some drying in the upper mix, then water thoroughly enough to moisten the root zone and let excess drain.\n\nA hanging pot can hide runoff or make inspection awkward. Choose a setup you can lift or reach safely. If leaves wilt while the pot stays heavy and damp, investigate the roots instead of automatically adding more water.'),
s('Prune and propagate with the node in mind','To keep the plant manageable, trim an overlong vine with clean scissors just above a node on the parent stem. A node is where a leaf attaches and where growth can develop. For a cutting, include a healthy node rather than only a leaf and its stalk.\n\nRemove leaves that would sit below water or buried in the rooting medium. Use clean equipment and suitable light, then monitor for decay. Root development takes time and varies with conditions; a fixed number of days is not a guarantee.'),
s('Build a useful care history','Look at new growth, leaf firmness, and how quickly the pot dries. Feed according to the product label during active growth and avoid stacking fertilizer on top of a pre-fed mix without considering the overlap.\n\nPothos can cause irritation if chewed, so place trailing vines where pets and young children cannot reach them. Save the plant’s zone and care notes in PlantPal. For a growing vine, location notes help you notice when it begins shading itself or neighboring plants.')
],['bright-indirect-light','propagating-pothos','how-to-water-houseplants']),
make('snake-plant-care','Snake plant care: the case for checking before watering','Learn how light, pot size, and a drying period affect snake plant care, and why soft leaves deserve a root check.','Snake plants store water in their tissues. Let the mix dry substantially and check the root zone before watering again.',[
s('Give a tolerant plant a worthwhile location','Snake plants, often labeled Dracaena trifasciata or Sansevieria, are widely chosen for indoor resilience. They can tolerate less light than many sun-loving plants, but tolerance does not mean a dark room is ideal. Better suitable light supports stronger growth and more predictable water use.\n\nIf moving a plant into direct sun, acclimate it gradually. A nursery or shop may have grown it under shade, and an abrupt change can mark the leaves. Check window heat as well as light.'),
s('Wait for meaningful drying','The thick leaves and underground structures hold reserves, so frequent small drinks are rarely a good default. Check the medium deeper in the pot, not only a dry top layer. A large container can hide damp material beneath the surface for a long time.\n\nWhen the root ball has dried appropriately, water evenly and let it drain. Do not leave runoff in a saucer or outer pot. In cooler or dimmer conditions, the interval between needed waterings may lengthen substantially.'),
s('Choose a stable, draining setup','Use a pot with drainage and a container mix that suits a plant preferring a pronounced dry-down. Avoid moving a small root system into a very large pot. A heavier container may help stabilize tall leaves, but material alone does not solve excess moisture.\n\nIf the plant becomes crowded, inspect the root ball before deciding to divide or repot. Handle leaves carefully; a bent or cracked blade does not simply repair itself. Clean tools when dividing healthy growth.'),
s('Watch for soft tissue rather than a calendar date','Soft, yellowing, or collapsing leaves with damp mix call for a root and crown inspection. Wrinkling can have more than one cause, including damaged roots, so it is not automatic permission to soak the pot.\n\nFeed modestly according to an appropriate product label when the plant is actively growing. Keep it away from pets that chew plants. In PlantPal, set a reminder to check moisture, with notes emphasizing the plant’s preference for drying rather than frequent watering.')
],['low-light-houseplants','overwatering-vs-underwatering','terracotta-vs-plastic-pots']),
make('zz-plant-care','ZZ plant care: patient growth and careful watering','Care for Zamioculcas zamiifolia with realistic light expectations, a draining pot, and attention to its water-storing rhizomes.','ZZ plants are slow, resilient growers with water reserves. More water is not a shortcut to faster growth.',[
s('Expect a different growth rhythm','A ZZ plant may remain visually unchanged for a while, then send up a new shoot. Slow growth alone does not mean it needs extra fertilizer or a larger pot. Look at overall firmness, color, and the root environment before changing care.\n\nA bright location with indirect light is a useful choice, though ZZ plants can tolerate dimmer conditions. Very low light can slow growth further. Keep the plant away from harsh sudden sun and remember that all living indoor plants need some usable light.'),
s('Respect the water stored below the surface','ZZ plants have thick rhizomes that store resources. Let the potting mix dry substantially between waterings and check below the surface. The combination of a dim room and frequent watering can leave roots wet for too long.\n\nWhen watering is needed, moisten the root ball evenly and allow drainage. A decorative outer pot should be emptied rather than used as a hidden reservoir. Record the actual drying time in your room instead of adopting someone else’s monthly or weekly rule.'),
s('Repot only when the root system calls for it','A tightly filled or distorting nursery pot can justify inspection. Choose a modest size increase with drainage and an appropriate container mix. Take care around the fleshy underground structures and do not bury stems more deeply just to make the plant stand straighter.\n\nIf dividing, use clean equipment and keep sound growth attached to healthy roots and rhizomes. Division is optional; a healthy plant does not need to be taken apart simply because it has multiple stems.'),
s('Understand common warning signs','Several stems yellowing while the medium stays wet suggest a moisture or root problem. A single aging stem is different from rapid whole-plant decline. Inspect for pests and environmental changes before diagnosing a deficiency.\n\nKeep the plant out of reach of children and pets that may chew it, as its tissues can irritate. PlantPal can help track its zone and sparse care routine. For this plant, a useful reminder often ends with deciding that no watering is needed today.')
],['low-light-houseplants','snake-plant-care','root-rot-houseplants']),
make('peace-lily-care','Peace lily care: steady moisture without soggy roots','Learn how to care for peace lilies with suitable light, moisture checks, realistic flowering expectations, and attention to leaf changes.','Aim for consistent, appropriate moisture. Repeated dramatic wilting and constantly saturated roots are both worth avoiding.',[
s('Give foliage and flowers enough light','Peace lilies, sold under Spathiphyllum, are often described as shade tolerant. That does not mean a dark corner is the best place for them, especially if you hope for flowering. Choose good indirect light while avoiding abrupt exposure to strong sun.\n\nThe white flower-like structure is a spathe around the actual flowers. It ages and changes color naturally. Removing spent flower stems can tidy the plant, but adding strong fertilizer is not a reliable way to force a new bloom.'),
s('Check before the plant performs a wilt','A peace lily can droop noticeably when dry, but repeated severe wilting is not an ideal watering method. Feel the mix and learn the weight of the pot before it reaches that point. Keep moisture reasonably steady without letting the root zone remain waterlogged.\n\nIf the plant droops while the mix is already wet, pause and investigate. Root damage, temperature stress, or other problems can cause similar symptoms. More water can worsen a wet-root problem even though the leaves look thirsty.'),
s('Review brown tips and yellow leaves methodically','Brown tips can reflect several stresses, including inconsistent moisture or dissolved minerals. Check fertilizer use, water quality, and roots before assuming humidity is the only issue. Existing brown tissue will not become green again, so watch the newest growth.\n\nUse a draining container and a suitable indoor potting mix. When roots are crowded or the medium has deteriorated, repot thoughtfully rather than making a large jump in pot size. Feed according to a suitable product label during healthy growth.'),
s('Keep the plant where it can be checked','A peace lily benefits from accessible placement because moisture checks and cleaning are easier when you can reach the pot. Avoid heating vents, cold drafts, and water left in outer containers.\n\nIts tissues can irritate the mouth if chewed, so keep it away from curious pets and children. Use PlantPal to record the plant’s location and watering observations. The goal is a predictable routine that prevents repeated crises rather than waiting for the next dramatic droop.')
],['how-to-water-houseplants','brown-leaf-tips','bright-indirect-light']),
make('rubber-plant-care','Rubber plant care: light, leaf cleaning, and stable roots','Grow Ficus elastica with good light, careful watering, practical leaf cleaning, and gradual adjustments to its environment.','A rubber plant responds well to adequate light and consistent conditions. Check roots and recent changes when leaves start dropping.',[
s('Choose a bright, stable home','Rubber plants have substantial leaves that make a strong indoor presence. Place the plant where it receives useful bright light, and acclimate it gradually if the location includes direct sun. Variegated forms can have different light responses from solid-green plants.\n\nLeave room for new growth and keep foliage away from cold windows or strong air-conditioning drafts. A plant may shed leaves after a major environmental change, so track what changed before deciding it needs a treatment.'),
s('Let the medium partly dry between waterings','Check moisture below the surface and lift the container if practical. A large pot can remain damp at depth even when the surface appears dry. Water when the plant’s root zone has reached an appropriate drying point, then let excess drain completely.\n\nIf leaves drop while the mix stays wet, inspect drainage and roots. If the root ball has become very dry and water runs around its edges, rehydrate it carefully rather than repeating quick surface splashes.'),
s('Clean leaves gently','Dust can build up on broad foliage. Support each leaf and wipe with a soft damp cloth, checking the underside at the same time. Use plain water and avoid household oils or polishing products that are not intended for living foliage.\n\nCleaning is also an opportunity to inspect for pests or damage. Do not scrub emerging leaves. If pruning is necessary, use clean tools and handle the milky sap carefully; it can irritate skin and should be kept away from eyes and mouths.'),
s('Support growth at the roots','Use a stable pot with drainage and a suitable container mix. Repot when crowding or medium condition warrants it, with a modest size increase. Feed an established plant according to the product label while it is growing, considering any nutrients already in the mix.\n\nKeep the plant away from pets and children who may chew or handle damaged tissue. Track new leaves and care changes in PlantPal. A clear history helps you avoid reacting to every fallen leaf with several simultaneous changes.')
],['cleaning-houseplant-leaves','repotting-houseplants','overwatering-vs-underwatering']),
];
