export const plantGameCopy = {
  he: {
    eyebrow: 'הרפתקה קטנה. הרבה שמש.', title: 'צמח קטן.', titleEmphasis: 'הרפתקה גדולה.',
    intro: 'שלושה גנים, שמשות לאסוף וקוצים לעבור. עד כמה רחוק יגיע ה־PlantPal שלכם?',
    stagesLabel: 'שלבי המשחק', regionLabel: 'משחק הגינה של PlantPal',
    levels: [
      { name: 'אחו הבוקר', subtitle: 'לומדים לזוז', description: 'לומדים לזוז, קופצים בין האבנים ואוספים את כל השמשות.' },
      { name: 'מעבר הקוצים', subtitle: 'מתחמקים וקופצים', description: 'האבנים קטנות יותר והקוצים זזים. קפצו מעל המכשולים הכתומים.' },
      { name: 'מרוץ שעת הזהב', subtitle: 'נגד השעון', description: 'שבע שמשות, אבנים גבוהות וקוצים מהירים. כל קפיצה חשובה.' },
    ],
    stage: (n: number) => `שלב ${n}`, stageOf: (n: number, total: number) => `שלב ${n} מתוך ${total}`,
    score: (n: number, total: number) => `אספתם ${n} מתוך ${total} שמשות`,
    time: (n: number) => `נותרו ${n} שניות`, lives: (n: number) => `נותרו ${n} ניסיונות`,
    unmute: 'הפעלת צליל', mute: 'השתקת צליל', soundOff: 'הצליל כבוי', soundOn: 'הצליל פועל',
    restart: 'התחלת השלב מחדש', pause: 'השהיית המשחק', loadingTitle: 'הגינה הקטנה צומחת.', loading: 'טוענים את PlantPal',
    paused: 'אפשר לנשום. השעון עצר.', start: (n: number) => `מתחילים שלב ${n}`, resume: 'ממשיכים לשחק',
    stats: (seconds: number, suns: number, lives: number) => `${seconds} שניות · ${suns} שמשות · ${lives} ניסיונות`,
    allComplete: 'סיימתם את כל שלושת השלבים', completeTitle: 'עוד קצת שמש.', wonTitle: 'יש לכם את זה.',
    hitTitle: 'זהירות מהקוצים.', timeoutTitle: 'השמש שקעה.',
    complete: (suns: number, seconds: number) => `אספתם ${suns} שמשות ונשארו ${seconds} שניות. גינה חדשה מחכה לכם.`,
    won: 'אספתם שמונה־עשרה שמשות וסיימתם שלושה שלבים. PlantPal גאה בכם!',
    lost: 'מנסים שוב, קופצים מעל הקוצים הכתומים ונוחתים על כל אבן לפני שהזמן נגמר.',
    next: 'לשלב הבא', replay: 'לשחק שוב מההתחלה', retryStage: 'לנסות שוב את השלב',
    errorTitle: 'הגינה לא נפתחה.', error: 'נסו שוב או הפעילו גרפיקה תלת־ממדית בדפדפן.', retry: 'ניסיון נוסף', guide: 'בינתיים אפשר לקרוא מדריך', guideHref: '/he/learn',
    touch: 'פקדי מגע למשחק', directions: { up: 'תנועה למעלה', down: 'תנועה למטה', left: 'תנועה שמאלה', right: 'תנועה ימינה' },
    jump: 'קפיצה', or: 'או', moveHint: 'לתנועה', space: 'רווח', jumpHint: 'לקפיצה', pauseHint: 'להשהיה',
    instructions: 'אוספים את כל השמשות וקופצים מעל הקוצים הכתומים. אפשר לשחק גם במגע.',
    wonStatus: 'כל השלבים הושלמו!', completeStatus: 'השלב הושלם. ממשיכים לגינה הבאה.', lostStatus: 'מנסים שוב את השלב.',
  },
  en: {
    eyebrow: 'A little adventure. A lot of sunshine.', title: 'Little plant.', titleEmphasis: 'Big adventure.',
    intro: 'Three gardens, sunshine to collect, and thorns to jump over. How far will your PlantPal go?',
    stagesLabel: 'Game stages', regionLabel: 'PlantPal garden game',
    levels: [
      { name: 'Morning Meadow', subtitle: 'Learn to move', description: 'Learn to move, jump between the stones, and collect all the sunshine.' },
      { name: 'Thorn Passage', subtitle: 'Dodge and jump', description: 'Smaller stones and moving thorns. Jump over the orange obstacles.' },
      { name: 'Golden Hour Race', subtitle: 'Beat the clock', description: 'Seven suns, taller stones, and faster thorns. Every jump counts.' },
    ],
    stage: (n: number) => `Stage ${n}`, stageOf: (n: number, total: number) => `Stage ${n} of ${total}`,
    score: (n: number, total: number) => `${n} of ${total} suns collected`,
    time: (n: number) => `${n} seconds remaining`, lives: (n: number) => `${n} lives remaining`,
    unmute: 'Turn sound on', mute: 'Mute sound', soundOff: 'Sound off', soundOn: 'Sound on',
    restart: 'Restart stage', pause: 'Pause game', loadingTitle: 'Your little garden is growing.', loading: 'Loading PlantPal',
    paused: 'Take a breath. The clock is paused.', start: (n: number) => `Start stage ${n}`, resume: 'Resume playing',
    stats: (seconds: number, suns: number, lives: number) => `${seconds} seconds · ${suns} suns · ${lives} lives`,
    allComplete: 'All three gardens complete', completeTitle: 'A little more sunshine.', wonTitle: 'You did it.',
    hitTitle: 'Watch out for thorns.', timeoutTitle: 'The sun has set.',
    complete: (suns: number, seconds: number) => `You collected ${suns} suns with ${seconds} seconds to spare. A new garden is waiting.`,
    won: 'Eighteen suns. Three gardens. One very happy PlantPal.',
    lost: 'Try again, jump over the orange thorns, and land on every stone before time runs out.',
    next: 'Next stage', replay: 'Play again from the start', retryStage: 'Try this stage again',
    errorTitle: 'The garden could not open.', error: 'Try again or enable 3D graphics in your browser.', retry: 'Try again', guide: 'Read a plant care guide while you wait', guideHref: '/learn',
    touch: 'Game touch controls', directions: { up: 'Move up', down: 'Move down', left: 'Move left', right: 'Move right' },
    jump: 'Jump', or: 'or', moveHint: 'to move', space: 'Space', jumpHint: 'to jump', pauseHint: 'to pause',
    instructions: 'Collect all the sunshine and jump over the orange thorns. You can also use the touch controls.',
    wonStatus: 'All stages complete!', completeStatus: 'Stage complete. Continue to the next garden.', lostStatus: 'Try this stage again.',
  },
};
