import {notFound} from 'next/navigation';
import {Clock,Leaf,ArrowUpRight} from 'lucide-react';
import {findArticle,listArticles} from '@/lib/repository';
import {categories,SITE_URL} from '@/lib/config';
import {readingMinutes} from '@/lib/content';
import {Breadcrumbs,JsonLd,pageMetadata} from '@/lib/seo';
import {ArticleCard} from '@/components/plantpal/library';
import {AppCTA,DownloadButton} from '@/components/plantpal/shared';
export const dynamic='force-dynamic';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const a=await findArticle((await params).slug);if(!a)return {title:'המדריך לא נמצא',robots:{index:false}};return {...pageMetadata(a.title,a.description,`/learn/${a.slug}`),openGraph:{type:'article' as const,title:a.title,description:a.description,url:`${SITE_URL}/learn/${a.slug}`,publishedTime:a.publishedAt,modifiedTime:a.updatedAt,locale:'he_IL'}}}
export default async function ArticlePage({params}:Props){const a=await findArticle((await params).slug);if(!a)notFound();const c=categories.find(c=>c.slug===a.category)!;const all=await listArticles();const related=a.related.map(slug=>all.find(x=>x.slug===slug)).filter(Boolean).slice(0,3);return <main id="main"><div className="shell article-shell"><Breadcrumbs items={[{name:c.name,href:`/${c.slug}`},{name:a.title,href:`/learn/${a.slug}`}]} /><header className="article-header"><span className="eyebrow">{c.name}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><span><Leaf size={16}/> מאת {a.author}</span><span>עודכן {new Date(a.updatedAt).toLocaleDateString('he-IL',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}</span><span><Clock size={15}/>{readingMinutes(a)} דקות קריאה</span></div></header><div className="article-layout"><article className="article-prose"><div className="takeaway"><span className="eyebrow">מה חשוב לזכור</span><p>{a.takeaway}</p></div>{a.sections.map((s,i)=><section id={`section-${i+1}`} key={i}><h2>{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}{a.sources.length>0&&<section className="sources"><h2>מקורות וקריאה נוספת</h2><p>פרטי מוצרים עשויים להשתנות. יש לפעול לפי התווית העדכנית של המוצר שנמכר באזורכם.</p><ul>{a.sources.map(s=><li key={s.url}><a href={s.url} rel="noopener noreferrer" target="_blank">{s.title} <ArrowUpRight size={14}/></a></li>)}</ul></section>}<div className="editorial-note"><Leaf size={20}/><p>המידע נכתב במקור עבור PlantPal. תנאי הגידול משתנים, ולכן כדאי לשלב את המדריך עם תצפית בצמח שלכם. <a href="/editorial">כך אנחנו כותבים את התוכן</a>.</p></div></article><aside className="article-sidebar"><div className="toc"><span className="eyebrow">במדריך הזה</span>{a.sections.map((s,i)=><a href={`#section-${i+1}`} key={i}><span>{String(i+1).padStart(2,'0')}</span>{s.heading}</a>)}</div><div className="sidebar-app"><img src="/images/app-icon.webp" width="56" height="56" alt="אפליקציית PlantPal"/><h3>הופכים את הידע<br/>לשגרת טיפול.</h3><p>מדריכים, תזכורות ועזרה חכמה תמיד בהישג יד.</p><DownloadButton/></div><a className="glossary-link" href="/glossary">נתקלתם במושג חדש?<br/><strong>למילון הצמחים <ArrowUpRight size={15}/></strong></a></aside></div>{related.length>0&&<section className="related-section"><span className="eyebrow">ממשיכים לגדול</span><h2>עוד כמה דברים שכדאי לקרוא.</h2><div className="library-grid">{related.map(a=><ArticleCard key={a!.slug} article={a!}/>)}</div></section>}</div><AppCTA/><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:a.publishedAt,dateModified:a.updatedAt,inLanguage:'he-IL',author:{'@type':'Organization',name:a.author,url:SITE_URL+'/editorial'},publisher:{'@type':'Organization',name:'PlantPal',url:SITE_URL},mainEntityOfPage:SITE_URL+'/learn/'+a.slug,articleSection:c.name}}/></main>}
