import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.TEST_ORIGIN||'http://localhost:5173';
const bundle=await build({stdin:{contents:"import {articles} from './lib/content';import {plantArticles} from './lib/plant-content';import {extraArticles} from './lib/extra-content';import {glossary} from './lib/glossary';export const all=[...articles,...plantArticles,...extraArticles];export {glossary};",resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'node'});
const {all,glossary}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
assert.equal(new Set(all.map(a=>a.slug)).size,all.length,'Duplicate seed slug');
assert.equal(new Set(all.map(a=>a.title)).size,all.length,'Duplicate seed title');
for(const a of all){for(const slug of a.related)assert(all.some(b=>b.slug===slug),`Missing related ${slug}`);assert(a.sections.length>=3);}
for(const t of glossary)assert(all.some(a=>a.slug===t.related),`Missing glossary link ${t.related}`);
const routes=['/','/app','/learn','/learn?page=2','/learn?q=yellow','/plant-guides','/plant-care','/soil-fertilizer','/troubleshooting','/tips','/glossary','/glossary?q=node','/editorial',...all.map(a=>'/learn/'+a.slug),...glossary.map(t=>'/glossary/'+t.slug)];
const failures=[];for(let i=0;i<routes.length;i+=5){await Promise.all(routes.slice(i,i+5).map(async route=>{const r=await fetch(origin+route);const html=await r.text();if(r.status!==200||!/<h1[\s>]/.test(html)||html.includes('The library needs a moment.'))failures.push({route,status:r.status});if(!route.includes('?'))assert(html.includes('rel="canonical"')||route==='/',`Missing canonical ${route}`);}));}
assert.deepEqual(failures,[]);
const sitemap=await fetch(origin+'/sitemap.xml');assert.equal(sitemap.status,200);const xml=await sitemap.text();for(const a of all)assert(xml.includes('/learn/'+a.slug));for(const t of glossary)assert(xml.includes('/glossary/'+t.slug));
const robots=await (await fetch(origin+'/robots.txt')).text();assert(robots.includes('Sitemap:'));
assert.equal((await fetch(origin+'/learn/this-does-not-exist')).status,404);
assert.equal((await fetch(origin+'/glossary/this-does-not-exist')).status,404);
assert.equal((await fetch(origin+'/no-such-category')).status,404);
assert.equal((await fetch(origin+'/api/content',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);
const key=process.env.CONTENT_API_KEY;assert(key,'Run with --env-file=.env to test authenticated publishing.');
const headers={'Content-Type':'application/json','Authorization':`Bearer ${key}`};
const request=(path,body,method='POST',extra={})=>fetch(origin+path,{method,headers:{...headers,...extra},body:JSON.stringify(body)});
assert.equal((await request('/api/content',{})).status,422);
const clean=(({slug,title,category,description,takeaway,sections,related,sources,author,status})=>({slug,title,category,description,takeaway,sections,related,sources,author,status}))(all[0]);
assert.equal((await request('/api/content',{...clean,slug:'verification-duplicate-seed'})).status,409);
const slug='verification-'+Date.now();const payload={...clean,slug,title:'Local verification article for publishing checks',status:'draft',sections:clean.sections.map((s,i)=>({...s,paragraphs:s.paragraphs.map((p,j)=>i===0&&j===0?`Local integration verification ${slug}. ${p}`:p)}))};
const first=await request('/api/content',payload);assert.equal(first.status,201);const saved=await first.json();
assert.equal((await fetch(origin+'/learn/'+slug)).status,404,'Draft exposed');
assert(!(await (await fetch(origin+'/sitemap.xml')).text()).includes(slug),'Draft in sitemap');
assert.equal((await request('/api/content',payload)).status,200,'Retry not idempotent');
assert.equal((await request('/api/content',{...payload,title:'A conflicting title for the same slug'})).status,409);
assert.equal((await request('/api/content',{...payload,slug:slug+'-copy'})).status,409,'Duplicate body allowed');
const malicious={...payload,slug:slug+'-xss',title:'<script>alert(1)</script>'};assert.equal((await request('/api/content',malicious)).status,422);
assert.equal((await request('/api/content/'+slug,payload,'PUT')).status,428);
assert.equal((await request('/api/content/'+slug,{...payload,status:'published'},'PUT',{'If-Match':'wrong'})).status,412);
const scheduled={...payload,status:'published',publishedAt:'2099-01-01T00:00:00.000Z'};const future=await request('/api/content/'+slug,scheduled,'PUT',{'If-Match':saved.revision});assert.equal(future.status,200);const futureData=await future.json();
assert.equal((await fetch(origin+'/learn/'+slug)).status,404,'Future post exposed');
const publish={...scheduled,publishedAt:'2026-01-01T00:00:00.000Z'};const publicResponse=await request('/api/content/'+slug,publish,'PUT',{'If-Match':futureData.revision});assert.equal(publicResponse.status,200);const publicData=await publicResponse.json();
const live=await fetch(origin+'/learn/'+slug);assert.equal(live.status,200);assert((await live.text()).includes(payload.title));assert((await (await fetch(origin+'/sitemap.xml')).text()).includes(slug));
assert.equal((await request('/api/content/'+slug,{...publish,status:'draft'},'PUT',{'If-Match':publicData.revision})).status,200);assert.equal((await fetch(origin+'/learn/'+slug)).status,404);
const words=all.reduce((n,a)=>n+a.sections.flatMap(s=>s.paragraphs).join(' ').split(/\s+/).length,0);
const result={articles:all.length,glossary:glossary.length,articleWords:words,routesChecked:routes.length,apiChecks:'passed',sitemap:'passed',draftAndScheduleVisibility:'passed',testSlug:slug};await mkdir('.sites-runtime',{recursive:true});await writeFile('.sites-runtime/verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
